### ISSUE TITLE
raster layer/source

### ISSUE THREAD

**Issue by z0d14c** [alex3165/react-mapbox-gl#101]
From scanning the API, it looks like the layer types (symbol/fill/line etc.) it looks like raster layers are not currently supported. 

Depending on how my week looks I may be able to take a look at implementing this, but I wanted to put it out there either way. Since it isn't already implemented, I suppose there may be a different philosophy about this from the maintainers; perhaps you expect to simply manipulate the style document to handle raster/vector layers/sources, although this doesn't take advantage of the JSX semantics.

**Comment by alex3165** [comment]
Hey @z0d14c I never had the opportunity to work with a raster layer, I think `react-mapbox-gl` should have a component for every `mapbox-gl` feature that need a specific logic for update or user interaction. Do you think a raster layer would actually need this ? If you can give me an example  then I think it make sense to create a component `RasterLayer` eventually.

**Comment by z0d14c** [comment]
@alex3165 I can't say definitely whether raster layers should be a **separate** component altogether (`<RasterLayer/>`) or whether Layer should simply be allowed to support rasters (`<Layer type='raster'/>`). I am leaning towards the latter.

In our application, we have multiple Raster layers that may be actively toggled on and off and manipulated by the user via UI controls (effectively changing their source URL). As such, they are semantically a very important type of layer for us and I think that `<Layer/>` at the very least needs to support them. Let me know if you have a preference towards `RasterLayer` or simply extending `Layer` and I will think about it some more.

**Comment by z0d14c** [comment]
I'm going to take a shot at writing a RasterLayer component or extending the current component, will keep this thread updated.

**Comment by z0d14c** [comment]
I think it's easy to get it working on a basic level. Simply add 'raster' to the list of acceptable types to the `<Layer/>` component and pass in the appropriate `sourceOptions`. That being said, it  its easy to get into a broken state if you pass in the wrong options and I'd like to get a Source component implemented as per #102 so that you can use a Component instead of just sourceOptions.

**Comment by zavan** [comment]
I'm using a raster layer (for legacy purposes) by defining it directly on the map style:

```javascript
import React from 'react';
import ReactMapboxGl from 'react-mapbox-gl';

const token = '...';

const style = {
  version: 8,
  sources: {
    osm: {
      type: 'raster',
      tiles: ['http://a.tile.openstreetmap.org/{z}/{x}/{y}.png'],
      tileSize: 256
    }
  },
  layers: [
    {
      id: 'osmTiles',
      type: 'raster',
      source: 'osm',
      minzoom: 0,
      maxzoom: 19
    }
  ]
};

export default const Map = () => (
  <div>
    <ReactMapboxGl style={style} accessToken={token}>
      // components
    </ReactMapBocGL>
  </div>
);
```
But this is hard to change during runtime, if needed.

**Comment by z0d14c** [comment]
@zavan yeah, we ran into the same thing. would prefer to not manipulate the style so much if we can do it more semantically with a component.

**Comment by z0d14c** [comment]
PR up https://github.com/alex3165/react-mapbox-gl/pull/103

**Comment by z0d14c** [comment]
@alex3165 @philpl please review when you get a chance ^^^

**Comment by alex3165** [comment]
Merged and released, Thanks again for your contribution.
