### ISSUE TITLE
source as separate component

### ISSUE THREAD

**Issue by z0d14c** [alex3165/react-mapbox-gl#102]
A colleague and I are digging into some work and were wondering if this topic has come up before during the development of this and similar projects -- why not separate source out as it's own component?

I am preferential towards keeping source as essentially a parameter/prop passed to a <Layer/> component, but keeping a <Source/> component separate seems more "react-y" on a surface level and I suppose if you had more than 1 <Layer/> component using the same source it may be helpful to have 1 separate source? Idk, like I said, I'm leaning towards the current pattern that exists in this library (using sourceOpts/source as a parameter) but am interested in hearing any thoughts that may exist on the matter and see if anyone has run into practical issues around this problem.

**Comment by alex3165** [comment]
@philpl and I idea was to simplify the use of source and layer by merging everything into one component. It hasn't been raised for now but semantically, it make sense to separate everything into 2 components but it is a consequent amount of work which I can't unsure alone within the upcoming month. Although I can help if you start working on it.

It has been ask to have 1 separated source though which would be possible by having a `Source` component as you propose. Also it would bring clarity to the `Layer` props and as you said it would the correct way to do it in React.

@philpl What do you think about it ?

**Comment by z0d14c** [comment]
one obstacle to this issue is that currently, most of the Components remove their associated Source when they unmount. I have limited experience with mapbox-gl-js, but it seems to me you could associate some metadata `manuallyAdded: true` or something to check for before removing a source. Thoughts? @philpl @alex3165

**Comment by z0d14c** [comment]
PR up https://github.com/alex3165/react-mapbox-gl/pull/103

**Comment by alex3165** [comment]
Merged and released, thank you for you contribution, good job ! https://github.com/alex3165/react-mapbox-gl/releases/tag/v0.27.0
