### ISSUE TITLE
layers probably should have option to not auto-remove their source

### ISSUE THREAD

**Issue by z0d14c** [alex3165/react-mapbox-gl#104]
See title; when using the new ```<Source />``` element, you can get breaking behavior with ```<Layer /```. 

For example, if you have source A and layer A (layer A pointing to source A), and you remove Source A in your JSX right before layer A, an error will be thrown in componentWillUnmount which will also result in a failure to remove the click / mousemove listeners from the map.

should be easy to fix, if you have any suggestions on the approach other than a Layer parameter, feel free to share

**Comment by z0d14c** [comment]
idea -- if you use sourceId instead of passing a source object, don't remove source on unmount

**Comment by z0d14c** [comment]
pr up https://github.com/alex3165/react-mapbox-gl/pull/105 @alex3165 @philpl 

layer / source component interaction is pretty broke without this, so lets converge on a solution sooner than later :)

**Comment by alex3165** [comment]
Hey @z0d14c Thanks for the PR I have juste merged it, sorry for the delay I think we are not on the same timezone 😄
