### ISSUE TITLE
Offsets not working on array when non-zero

### ISSUE THREAD

**Issue by iop280** [alex3165/react-mapbox-gl#109]
Markers/Popups (haven't tested other objects) don't offset with an array parameter if one of the values is 0

***Non-working offset***
```
<Marker
  offset={[0, -7]}
  coordinates={[x, y]}
>
```

***Working offset***
```
<Marker
  offset={[0.01, -7]}
  coordinates={[x, y]}
>
```

I have to resort to using a close to 0 number to achieve offset.

**Comment by alex3165** [comment]
Hey @iop280 sorry for the late reply, this should be fixed with https://github.com/alex3165/react-mapbox-gl/commit/bc275652794956f51d9fb77fbc6c1997569f965c 👍 thanks for reporting the issue
