### ISSUE TITLE
fitBounds parameters should be supported

### ISSUE THREAD

**Issue by z0d14c** [alex3165/react-mapbox-gl#117]
https://www.mapbox.com/mapbox-gl-js/api/#Map#fitBounds

We should be able to support the optional parameters to this function, somehow. I don't mind working on this but wanted to make an issue to elicit any potential roadblocks; it seems like it likely would necessitate the passing of an Array<Args> of multiple arguments instead of the single arg of Array<Coordinates>. 

Also, if there are other features that follow a similar pattern that we aren't supporting, should probably consider that going forward.

**Comment by aleksplus** [comment]
look at props `fitBounds` and `fitBoundsOptions`

**Comment by alex3165** [comment]
@z0d14c as @aleksplus said check if you can achieve what you want with `fitBounds` and `fitBoundsOptions` 👍

**Comment by z0d14c** [comment]
kk, just to be clear -- fitBoundsOptions doesnt currently seem to be supported in this wrapper, so we'll have to add some way to pass it in, right? In that case I will look into adding it in a PR as soon as I can.

**Comment by aleksplus** [comment]
@z0d14c you can direct access to `map` instance of mapbox-gl via refs `this.refName.state.map`

at least fit worked for me `fitBoundsOptions={{padding: 50, linear: true}}`, but props transformation not going well in my use cases (switch between `center` and `fitBounds`)

**Comment by z0d14c** [comment]
ok, so you're saying i can get access to the map object through refs? thats fine, but it would be preferable if I could do this in a more react-y style (passing in params through props).

regarding your transformation issue, we have adapted our project to use fitBounds instead of centering whenever possible.

**Comment by z0d14c** [comment]
Ahh I see that there are fitBoundsOptions that are undocumented in the api. recommend adding them to the API.. will create a PR if I get a sec.

**Comment by z0d14c** [comment]
PR up https://github.com/alex3165/react-mapbox-gl/pull/128

**Comment by alex3165** [comment]
merged thanks @z0d14c 👍
