### ISSUE TITLE
Popup component not available when installing from NPM

### ISSUE THREAD

**Issue by xavcz** [alex3165/react-mapbox-gl#12]
Hi Alex!

First of all, this binding is awesome!! I'll definitely use it on a project of mine, cheers for building this! 💯 

I just noticed that I couldn't import the Popup component => it is not in `node_modules/react-mapbox-gl/src` nor `/dist` folders...

I installed it via `npm install --save react-mapbox-gl` and I'm running on the latest version 0.2.2

**Comment by alex3165** [comment]
Hi Xavier,

Indeed the popup component was missing, i have added it and released a version 0.2.3 but i would like to let you know that the popup is not working well for now i am trying to fix a few things concerning this component, you should avoid rely on it for now. A fully working version of the popup with an advanced example using it should come with a version 3.0.0 of the library.

**Comment by xavcz** [comment]
Ok, thanks for the update and the warning 👍  I'll tell you if I see weird things and succeed in fixing those ;)

Btw, do you know React Storybook? I started to use it, pretty awesome to design UI components! https://github.com/kadirahq/react-storybook

**Comment by alex3165** [comment]
I just updated the library to a version 0.3.1, there was no issue with the popup component itself, just a missing mapbox css file in london-cycle example, you can update the library and use the Popup it should be good.
