### ISSUE TITLE
source needs to update (be removed and re-added) when tiles urls change

### ISSUE THREAD

**Issue by z0d14c** [alex3165/react-mapbox-gl#120]
See title -- for Source options, currently once a source with a given ID has been added, you cannot change it's tile URLs. I have added a PR #119 to address this issue.

**Comment by z0d14c** [comment]
can I please get a review on this ASAP :)

**Comment by alex3165** [comment]
Hey @z0d14c, sorry I probably won't be able to handle it this week-end, I will review it beginning of next week.

**Comment by alex3165** [comment]
See https://github.com/alex3165/react-mapbox-gl/pull/122

**Comment by alex3165** [comment]
@z0d14c Would you have time to try #122 ?

**Comment by z0d14c** [comment]
Yeah ill try and get to it ASAP

**Comment by z0d14c** [comment]
Tested, looks good 👍
