### ISSUE TITLE
Uncaught TypeError: Cannot read property 'prototype' of undefined

### ISSUE THREAD

**Issue by safeiskyshi** [alex3165/react-mapbox-gl#124]
```
import React, { Component } from 'react';

import ReactMapboxGl, { Layer, Feature } from "react-mapbox-gl";
//After i import ReactMapboxGl and refresh the browser the console log showing error
//Uncaught TypeError: Cannot read property 'prototype' of undefined

export default class App extends Component {
  render() {
    return (
      <div>React simple starter</div>
    );
  }
}
```

**Comment by safeiskyshi** [comment]
{
  "name": "redux-simple-starter",
  "version": "1.0.0",
  "description": "Simple starter package for Redux with React and Babel support",
  "main": "index.js",
  "repository": "git@github.com:StephenGrider/ReduxSimpleStarter.git",
  "scripts": {
    "start": "node ./node_modules/webpack-dev-server/bin/webpack-dev-server.js",
    "test": "mocha --compilers js:babel-core/register --require ./test/test_helper.js --recursive ./test",
    "test:watch": "npm run test -- --watch"
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "babel-core": "^6.2.1",
    "babel-loader": "^6.2.0",
    "babel-preset-es2015": "^6.1.18",
    "babel-preset-react": "^6.1.18",
    "chai": "^3.5.0",
    "chai-jquery": "^2.0.0",
    "jquery": "^3.1.1",
    "jsdom": "^9.11.0",
    "mocha": "^3.2.0",
    "react-addons-test-utils": "^15.4.2",
    "webpack": "^2.2.1",
    "webpack-dev-server": "^2.3.0"
  },
  "dependencies": {
    "babel-preset-stage-1": "^6.1.18",
    "lodash": "^4.17.4",
    "react": "^15.4.2",
    "react-dom": "^15.4.2",
    "react-mapbox-gl": "^1.1.0",
    "react-redux": "^5.0.2",
    "react-router": "^3.0.2",
    "redux": "^3.0.4"
  }
}

**Comment by alex3165** [comment]
Hey @safeiskyshi Can you explain when the error occur ?

**Comment by safeiskyshi** [comment]
@alex3165 Hi Alex,
- After i import ReactMapboxGl in App.js 
- Then refresh the browser 
- The console  log showing error (Uncaught TypeError: Cannot read property 'prototype' of undefined)

I dont understand why?

**Comment by alex3165** [comment]
@safeiskyshi Can you send a link to your project ?

**Comment by siamalekpour** [comment]
Hey @alex3165. I get the same error after just importing the library. Nothing else.

```javascript
import ReactMapboxGl from "react-mapbox-gl";

// Using version 1.0.0
Uncaught TypeError: Cannot read property 'prototype' of undefined

// Using latest version 1.3.4
Uncaught TypeError: Object prototype may only be an Object or null: undefined
```

**Comment by alex3165** [comment]
Hey @siamalekpour Can you try to reproduce the issue using https://github.com/alex3165/react-mapbox-gl-debug ?

**Comment by alex3165** [comment]
I will close this issue for inactivity, feel free to open a new one if it is still happening
