### ISSUE TITLE
Feature `onClick` with property id=0 is not clickable

### ISSUE THREAD

**Issue by chafnan** [alex3165/react-mapbox-gl#125]
When a feature that has `id = 0` then it is not clickable.  All other features `onClick` works just fine.

Specifically, the id value is checked to be falsy.  I linked the line that is causing the issue.

https://github.com/alex3165/react-mapbox-gl/blob/aa09871259e9f45ca0a543fe892c7a62a937d863/src/layer.ts#L93

**Comment by alex3165** [comment]
ups, id was optional at some point so to check that it was not undefined I have added it in the condition but it is not anymore true, this commit should fix it https://github.com/alex3165/react-mapbox-gl/commit/94efe7f72a1bd848432b55079b2bbd44abec9911.

Thanks for reporting it is pushed on a new version `1.2.0`

**Comment by alex3165** [comment]
Let me know if it solved

**Comment by chafnan** [comment]
That fixed it, tks for the quick turn around.
