### ISSUE TITLE
Layer's before prop not updating

### ISSUE THREAD

**Issue by z0d14c** [alex3165/react-mapbox-gl#127]
We need to compare prop.before so that it gets updated (map.moveLayer needs to be called) in componentWillReceiveProps

PR up #126 

relevant changes in `layer.ts` -- accidentally branched form another feature branch, so it may list changes from #122

**Comment by alex3165** [comment]
It is in master https://github.com/alex3165/react-mapbox-gl/commit/2277b22573dbd59147affa9fa64d50357f8e5113
