### ISSUE TITLE
Question: How to trigger manually the mapbox resize() function?

### ISSUE THREAD

**Issue by maximelebreton** [alex3165/react-mapbox-gl#13]
Hello @alex3165,

Is there a way to trigger the [mapbox resize() function](https://www.mapbox.com/mapbox-gl-js/api/) function?

Thanks!

**Comment by philpl** [comment]
@maximelebreton The `onStyleLoad={}` prop on map is perfect for this. It'll be called once the map is ready to render, and it received `map` as the first argument. You can store it somewhere and call resize on it.

**Comment by alex3165** [comment]
@maximelebreton Does it solve your problem ? can we close this issue ?

**Comment by philpl** [comment]
@alex3165 @maximelebreton I guess this is resolved
