### ISSUE TITLE
fitBounds burst issue

### ISSUE THREAD

**Issue by pronebird** [alex3165/react-mapbox-gl#136]
Hi,

Did you happen to see that a burst of fitBounds changes would be discarded.

I have the following log from `render()`:

```
bounds: [[-14.956032191681425,27.33871139614223],[-13.151319808318574,29.378776603857773]]

bounds: [[-14.956032191681425,27.33871139614223],[-13.151319808318574,29.378776603857773]]

bounds: [[-14.956032191681425,27.33871139614223],[-13.151319808318574,29.378776603857773]]

bounds: [[-2.8241818150222513,47.1865573870424],[2.5686652150222513,55.8281444129576]]

bounds: [[-2.8241818150222513,47.1865573870424],[2.5686652150222513,55.8281444129576]]
```

What happens is that location remains at `[[-14.956032191681425,27.33871139614223],[-13.151319808318574,29.378776603857773]]` and does not change to `[[-2.8241818150222513,47.1865573870424],[2.5686652150222513,55.8281444129576]]`

Changing bounds manually from console worked though, i.e:

```js
map.state.map.fitBounds([[-2.8241818150222513,47.1865573870424],[2.5686652150222513,55.8281444129576]], { offset: [0, -100]})
```

My code is fairly simple:

```
const mapBounds = this.toLngLatBounds(bounds);
const mapBoundsOptions = { offset: [0, -100] };

<ReactMapboxGl 
  style="mapbox://styles/..."
  accessToken={ accessToken }
  containerStyle={{ height: '100%' }} 
  interactive={ false }
  fitBounds={ mapBounds }
  fitBoundsOptions={ mapBoundsOptions }>
```

I'll try to come up with isolated test case.

**Comment by alex3165** [comment]
Hey @pronebird, same here, can you try to reproduce this issue using https://github.com/alex3165/react-mapbox-gl-debug ?

**Comment by pronebird** [comment]
@alex3165 I will do, sorry for being slow on reproducing this, I have been really busy.

**Comment by z0d14c** [comment]
also having issues with using fitbounds after upgrading from 1.3 -> 1.9

**Comment by gschjetne** [comment]
I have the same problem. When executing `componentWillReceiveProps()` upon receiving the new bounds, it finds `this.state.map` to be `undefined`, so the new bounds are never passed on to Mapbox GL.

It seems the problem is that `this.state.map` is not set until the Mapbox GL instance has finished loading:

```javascript
map.on('load', (evt: React.SyntheticEvent<any>) => {
        if (this._isMounted) {
          this.setState({ map });
        }

        if (onStyleLoad) {
          onStyleLoad(map, evt);
        }
      });
```

So any changes to props issued before that will be lost. Any particular reason for doing it this way, rather than cementing it as part of the component's state right away?

**Comment by alex3165** [comment]
@gschjetne Could you reproduce the problem with https://github.com/alex3165/react-mapbox-gl-debug that would be very helpful

**Comment by gschjetne** [comment]
@alex3165 Here's my reproduction: https://github.com/leanmarine/react-mapbox-gl-debug/blob/master/src/App.js
