### ISSUE TITLE
Support className on Marker component

### ISSUE THREAD

**Issue by wmonk** [alex3165/react-mapbox-gl#139]
hey alex, loving this so far ❤️ , much better than the google maps one I was using before.

Using aphrodite for styling so want to style the `Marker` component using `css`. Can this be supported, is there a reason not to?

**Comment by alex3165** [comment]
Hey, no particular reason, nobody asked for it so far. I just added it you can install the version `1.3.2` 👍

**Comment by alex3165** [comment]
`1.3.3` should be better :)
