### ISSUE TITLE
Gulp: Cannot find module from /dist using browserify

### ISSUE THREAD

**Issue by mark2685** [alex3165/react-mapbox-gl#143]
Running into the same issue noted in [#30](https://github.com/alex3165/react-mapbox-gl/issues/30) using Gulp with Browserify where it cannot find modules from the compiled version of `mapbox-gl-js`. 

```
ERROR: Cannot find module './buffer_group' from '../node_modules/mapbox-gl/dist'
ERROR: Cannot find module '../util/util' from '../node_modules/mapbox-gl/dist'
```

Has anyone been able to get around this?

**Comment by alex3165** [comment]
I don't know much about Gulp, if anyone can help on this one that would be awesome ! 👍

**Comment by alex3165** [comment]
I will close this issue because of inactivity. Feel free to open a new issue if you still have a problem with browserify
