### ISSUE TITLE
extrusion not supported

### ISSUE THREAD

**Issue by Satherial** [alex3165/react-mapbox-gl#150]
Hello,
I think https://www.mapbox.com/mapbox-gl-js/example/3d-buildings/ (extrusions in general), is not supported, am I right?
Have you planned to update the project to support it?
Thank you!

**Comment by alex3165** [comment]
Hey @Satherial , please see https://github.com/alex3165/react-mapbox-gl/issues/79

**Comment by Satherial** [comment]
thanks, it works :D
