### ISSUE TITLE
ES5 require not working

### ISSUE THREAD

**Issue by jonheslop** [alex3165/react-mapbox-gl#151]
Hi there, I’m conditionally requiring `ReactMapboxGL` on the client side only so I can’t use `import` but when I use 
```javascript
var ReactMapboxGl = require("react-mapbox-gl").default // Note the default was necessary too
var Layer = ReactMapboxGl.Layer
var Feature = ReactMapboxGl.Feature
```

I get the following error
```
Uncaught Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in.
```
The map loads ok, but no Layers, Markers or Features show. 

I had a [little google](https://www.google.co.uk/search?q=react+You+likely+forgot+to+export+your+component+from+the+file+it%27s+defined+in.&oq=react+You+likely+forgot+to+export+your+component+from+the+file+it%27s+defined+in.&aqs=chrome..69i57.1077j0j1&sourceid=chrome&ie=UTF-8) and it seems like the [problem might be](https://github.com/Semantic-Org/Semantic-UI-React/issues/1182) to do with transpiled Typescript?

This is the [relevant code](https://github.com/jonheslop/colwiki/blob/apollo/components/Map.js) in my repo 

Thanks in advance for any help

**Comment by alex3165** [comment]
Thanks for the issue, I will look into it when i have some free time

**Comment by philpl** [comment]
This is because you're accessing module.default.Layer instead of module.Layer ;)

**Comment by jonheslop** [comment]
@philpl if I use `module.layer` then the page fails to load entirely, I get the error 
```
Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.
```

**Comment by jonheslop** [comment]
I got it working in the end using

``` javascript
var ReactMapboxGl = require('react-mapbox-gl')
var ReactMapboxGlComponent = ReactMapboxGl.default
var Layer = ReactMapboxGl.Layer
var Feature = ReactMapboxGl.Feature
var Marker = ReactMapboxGl.Marker
```
