### ISSUE TITLE
Watch for `layerOptions.filter` change in props change

### ISSUE THREAD

**Issue by nrako** [alex3165/react-mapbox-gl#153]
I've noticed that the the `<Layer/>` component doesn't watch `layerOptions` changes, more specifically for `filter` changes. https://github.com/alex3165/react-mapbox-gl/blob/c621f8915cbb7f81b8a7d060f0c5305d548a04fb/src/layer.ts#L180

mapbox api does have a `setFilter` method https://www.mapbox.com/mapbox-gl-js/api/#Map#setFilter

For my use case, it would be very helpful to change the `filter` of a layer, in order to filter what's displayed without having to change the source. Is there any technical reason which would prevent that to be implemented?

**Comment by alex3165** [comment]
Hey @nrako There is no technical reason why it is not implemented, that's something that need to be done. I can jump on it when I have some free time or any PR for this is welcome.

**Comment by nrako** [comment]
Hey @alex3165, thanks for the quick feedback. I might need it soon, I might start a PR, I'll let you know.

**Comment by nrako** [comment]
@alex3165 I started to look into this but I run into an issue with TS, the `@types/mabbox-gl` is wrong:
This line https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/mapbox-gl/index.d.ts#L73
Should be something akin to:
`setFilter(layer: string, filter?: any[]): this;`
The filter argument should be nullable.

I'm not very familiar with TS, any way to circumvent that error type? Or must `@types/mapbox-gl` be fixed first?

**Comment by alex3165** [comment]
Why do you want the filter to be optional ? do you need to call `setFilter` without passing a filter ?

if your problem is that your filter array is of type `filter: string[] | undefined` you should make sure it is not undefined and pass it to `setFilter('layer_string', filter)` you can also force the typescript compiler and tell him it will never be undefined by doing `setFilter('layer_string', filter!)`.

Worse case scenario you can bypass the typings by doing `(map as any).setFilter(layer, filter)`

**Comment by nrako** [comment]
Good question, actually to remove an existing filter I'd simply do `map.setFilter('layer-id', null)`, which works. 
But looking at https://github.com/mapbox/mapbox-gl-js/blob/master/src/ui/map.js#L885 make me wonder if there's an more approriate way?

**Comment by alex3165** [comment]
What about defaulting to empty array in order to remove the filter ?

**Comment by nrako** [comment]
Not allowed:
```
Error: layers.layer-10.filter: filter array must have at least 1 element
    at Function.module.exports.emitErrors 
```
https://github.com/mapbox/mapbox-gl-js/blob/master/src/style-spec/validate/validate_filter.js#L20

**Comment by alex3165** [comment]
ok then I guess you would need to fix the typings on definitelyTyped, for now you can do :
```
(map as any).setFilter('layer-id', null);
```

**Comment by alex3165** [comment]
@nrako Any update on this one ? 👍

**Comment by nrako** [comment]
@alex3165 actually I have been able to refactor my code without needing this by using data-driven styles which gave me a better result. So this hasn't been as urgent for me.

However, I can promise to **try* to submit something in the next days if wanted?

**Comment by cmrtn** [comment]
Hey @nrako. I could actually use this if you've got the time to work on it.

**Comment by alex3165** [comment]
@nrako No worries take your time 👍

**Comment by alex3165** [comment]
Should work now with the release `1.5.0`
