### ISSUE TITLE
Existing animation pace is being reset on render

### ISSUE THREAD

**Issue by pronebird** [alex3165/react-mapbox-gl#154]
It seems that existing animation pace is being reset on each render when bounds don't change.

Do you know maybe there is some pencode template that I can use to prototype and reproduce this?

**Comment by alex3165** [comment]
Hey I just created this boilerplate https://github.com/alex3165/react-mapbox-gl-debug you can use it to reproduce your issue

**Comment by pronebird** [comment]
Reproduced this in https://github.com/pronebird/react-mapbox-gl-debug/tree/pace-bug

Animation pace is being reset during `render()`. For example to trigger `render` I use a series of timers that update component's state, i.e:

```js
for(let delay = 200; delay < 2000; delay += 200) {
  this._timers.push(setTimeout(() => {
    this.setState({ randomFieldForUpdate: +new Date() });
  }, delay));
}
```

**Comment by alex3165** [comment]
this is kind of related to https://github.com/alex3165/react-mapbox-gl/issues/160 in the way that I need to add a fix that prevent a re-rendering during an animation of the map

**Comment by alex3165** [comment]
I will close this issue for inactivity. Also I don't think the library should prevent from changing the position of the map while animating. It is better for developers consuming the library to old the re-rendering when the map is animating then listening for moveEnd event to trigger the rendering of the map component and doing any map position update.

**Comment by eballeste** [comment]
@alex3165 how would you approach this? I have an issue where map animations keep getting interrupted by state changes caused by the mouse triggering hover effects of items on the map, the animation is interrupted and then abruptly offset by whatever value the `animationOptions`: `offset` parameter has

**Comment by eballeste** [comment]
actually nevermind, I found that features get an instance of the map on the MouseEnter & MouseLeave events so I check for `map.isMoving()` to decide whether to update the state on hover
