### ISSUE TITLE
TypeError when updating zoom state with onZoom method

### ISSUE THREAD

**Issue by peitalin** [alex3165/react-mapbox-gl#155]
I'm trying to update the zoom with the onZoom prop:

```
<ReactMapboxGl 
    ...
    zoom={[this.state.zoom]}
    onZoom={this.onZoom}
>

onZoom = (map, event) => {
    this.setState({ zoom: map.getZoom() })
}
```

But I'm getting the following errors:
```
Uncaught TypeError: Cannot read property 'call' of undefined
    at e.i._finishEase (mapbox-gl.js:185)
    at e.<anonymous> (mapbox-gl.js:185)
    at o (mapbox-gl.js:221)
```

Feels like I'm doing something very wrong with this approach.

Is there a way to set the initial value of zoom without resorting to updating `this.state.zoom`?

**Comment by peitalin** [comment]
I've resorted to using:
```
map.setCenter([this.props.longitude, this.props.latitude])
map.setZoom(this.props.zoom)
```
Inside the `onStyleLoad` callback for now.

**Comment by alex3165** [comment]
Hi @peitalin In order to update the zoom you have to give a new reference of an array with your zoom value to the `zoom` props of the map. That is why zoom is an array, because we don't necessarily check for value equality in some case.

I have update the doc : https://github.com/alex3165/react-mapbox-gl/blob/master/docs/API.md#properties

**Comment by alex3165** [comment]
I will close this issue but let me know if you still have a problem, if so feel free to open a new issue with en example.

**Comment by peitalin** [comment]
Ah, ok thanks Alex.
I've fixed this issue by replacing:
```
  onZoom = (map: mapboxgl.Map, event: EventData): void => {
    this.setState({ mapboxZoom: [...[map.getZoom()]] })
  }
```
Thanks for making this library, it's made mapboxgl development much cleaner.
