### ISSUE TITLE
Setting center of map

### ISSUE THREAD

**Issue by sohibul** [alex3165/react-mapbox-gl#160]
So I set center using `this.state.center`. I read your code in map.tsx:

```
map[mm]({
  zoom: (didZoomUpdate && nextProps.zoom) ? nextProps.zoom[0] : zoom,
  center: didCenterUpdate ? nextProps.center : center,
  bearing: didBearingUpdate ? nextProps.bearing : bearing,
  pitch: didPitchUpdate ? nextProps.pitch : pitch
});
```

What happen is my `ReactMapboxGl` is rendered several times. The problem is `didCenterUpdate` was false several times after `didCenterUpdate` was true. When `didCenterUpdate` was true, the `center` will be set to new center, but the map was not updated directly. After that, when `didCenterUpdate` was false, `center` will be set with current center (lterally) of the map `(map.getMap())` which is not what I want. I expect center was set by  previous center which is `this.props.center`.

Do you have any workaround idea?

**Comment by alex3165** [comment]
Hey can you reproduce this using https://github.com/alex3165/react-mapbox-gl-debug ? and attach a link to the repo

**Comment by sohibul** [comment]
It turns out the problem is in `didZoomUpdate`. I reproduce it here https://github.com/sohibul/react-mapbox-gl-debug. So I set initial state of center [0, 0], then update it after few seconds. Then set another state to make component re-rendered.

**Comment by alex3165** [comment]
Thanks for taking time to reproduce the bug, it is because you re-render the map while the `flyTo` animation occur then the center of the map at the moment you re-render is different but not the center given by the prop is similar so I assume there is no update and just take as a center the current position of the map so it stop moving. That's a tricky use case, I will see if I can check if the animation occur and act depending on it to fix it.

**Comment by alex3165** [comment]
What you can do for now is waiting for `isMoving` is false before setting your state. https://www.mapbox.com/mapbox-gl-js/api/#Map#isMoving you can get an instance of the map using `mapInit` prop.

**Comment by sohibul** [comment]
ahha, thanks for the workaround

**Comment by alex3165** [comment]
I actually don't think it is up to react-mapbox-gl to solve this, a good way to proceed would be to listen the end of the animation with `onMoveEnd ` and sync your props accordingly
