### ISSUE TITLE
attributionPosition is not used/effective

### ISSUE THREAD

**Issue by lamuertepeluda** [alex3165/react-mapbox-gl#162]
Hi,

by looking at the source code, it seems that the property `attributionPosition` is actually never used. The only property working is `attributionControl` (boolean), which sets attribution controls on or off (but does not affect its position).

I also tried to set the value of `attributionPosition` to `'bottom-left'` but nothing changes.

Did you probably mean to set `options.logoPosition` ?

**Comment by alex3165** [comment]
Yes indeed, I pushed a fix on master : https://github.com/alex3165/react-mapbox-gl/commit/0b7c2e5b2cc0f1132630f3f95c3e53f31378986c

**Comment by lamuertepeluda** [comment]
cool 😃

**Comment by alex3165** [comment]
Published with the patch `1.4.2`
