### ISSUE TITLE
More map event handlers

### ISSUE THREAD

**Issue by lamuertepeluda** [alex3165/react-mapbox-gl#163]
Hi again,

I think you could definitely consider adding a few more event handlers that reflect those of the underlying map instance, i.e.:

* `onLoad` --> https://www.mapbox.com/mapbox-gl-js/api/#map.event:load
* `onError` --> https://www.mapbox.com/mapbox-gl-js/api/#map.event:error

Then probably also more...

An example use case (my use case, actually) for `onLoad` is when using this component with redux and you want to update the map state in the store getting zoom, center and other map settings at the first map render (componentDidMount is not enough).

The `onError` could be handy for mapbox error handling.

**Comment by z0d14c** [comment]
Agreed that we should support more event handlers. Maybe it would be a good idea to just map every event from https://www.mapbox.com/mapbox-gl-js/api/#map.event:resize on down to a handler. I could help with this if needed, thoughts @alex3165 @philpl ?

**Comment by alex3165** [comment]
Well ideally we should support all the event handlers ! 👍 Feel free to open a PR to add everything missing

**Comment by alex3165** [comment]
Should be addressed by https://github.com/alex3165/react-mapbox-gl/pull/242

**Comment by alex3165** [comment]
I will close this issue as it is been resolved with the version 2.0.0. Please use https://github.com/alex3165/react-mapbox-gl/issues/237 to be updated on the state of 2.0.0.
