### ISSUE TITLE
Unhandled TypeError in Layer onClick handler

### ISSUE THREAD

**Issue by lamuertepeluda** [alex3165/react-mapbox-gl#166]
Hi again (don't hate me please! 😄 )

I found out a possible bug here at this line:

https://github.com/alex3165/react-mapbox-gl/blob/master/src/layer.ts#L90

If features is `undefined` (that happens when I remove a layer) the method should exit, otherwise:

`Cannot read property 'forEach' of undefined`.

I know it should be an empty array, but it isn't so if the layer has been removed.

I found it out while toggling a layer on the click event handler of the map component. I can reproduce it using the `react-mapbbox-gl-debug` if you wish, but it seems clear to me by looking at the code.

**Comment by alex3165** [comment]
Should be fixed with the new release `1.5.0`, see : https://github.com/alex3165/react-mapbox-gl/blob/master/src/layer.ts#L92
