### ISSUE TITLE
Cluster component not updating if child Markers change

### ISSUE THREAD

**Issue by drekli** [alex3165/react-mapbox-gl#167]
Thought I'd try out the new Marker and Cluster components (awesome idea!), and noticed that whilst the child Markers show/hide on a query change, the Clusters always remain the same from first load.

Same pointCount and coords, even if the children underneath change or no longer exist. Also means no new Clusters appear for Markers that didn't exist on first load and start with a parent Cluster (or were outside of the getBounds on first load). Tried out the demo and but the data doesn't change so couldn't reproduce the issue there. Looked at the component as well, and only saw mapChange updating the pointCount, but not for a new query.

Seeing as the child Markers update happily along with other map components, I couldn't think what the issue with Clusters not updating.

The chance of html Markers makes me not want to switch back to Layers, so any help is appreciated!

**Comment by alex3165** [comment]
@drekli Can you try out with react-mapbox-gl v2?

**Comment by drekli** [comment]
Sure thing, I'll look forward to testing that! Thanks for the heads up on v2 and all the hard work!

**Comment by marek-sed** [comment]
this is still happening even on version 2

**Comment by alex3165** [comment]
@marek-sed, @Wykks will look into that

**Comment by marek-sed** [comment]
@Wykks I looked at the code I think I found the issue and was able to fix it properly.
Hope it helps
#286

**Comment by alex3165** [comment]
Released with version `2.0.6`
