### ISSUE TITLE
blank page: using this with create-react-app

### ISSUE THREAD

**Issue by lordKnighton** [alex3165/react-mapbox-gl#170]
Im trying this react-mapbox as a component to App.js 

at 1st: 
![screen shot 2017-03-29 at 7 40 08 pm](https://cloud.githubusercontent.com/assets/1773260/24485203/91c8cf6c-14b7-11e7-90bc-20282562a2a2.png)

then i comment out es5 declarations
2nd:
![screen shot 2017-03-29 at 7 41 10 pm](https://cloud.githubusercontent.com/assets/1773260/24485224/cf79fb24-14b7-11e7-9a49-df51d0c2d0ea.png)

then i input import react from 'react
3rd: 
![screen shot 2017-03-29 at 7 43 14 pm](https://cloud.githubusercontent.com/assets/1773260/24485250/087d27e8-14b8-11e7-83a3-7171ec0103ca.png)

then i went back & uncommented out the es5 declarations & commented out the es6 declaration

it was blank page - don't know how to evoke that error again
![screen shot 2017-03-29 at 7 45 17 pm](https://cloud.githubusercontent.com/assets/1773260/24485299/5639fd44-14b8-11e7-9c45-4a8b7fd98d86.png)

**Comment by philpl** [comment]
This very much looks like sth not related to React Mapbox GL itself, but some syntax errors. We can give a shot at helping you, if you can provide your code via a gist or sth :wink:
