### ISSUE TITLE
Map unmounting done wrong?

### ISSUE THREAD

**Issue by lamuertepeluda** [alex3165/react-mapbox-gl#178]
Hi,

I think [this line of map.tsx](https://github.com/alex3165/react-mapbox-gl/blob/master/src/map.tsx#L198) causes a lot of troubles.

According to [MapBox doc](https://www.mapbox.com/mapbox-gl-js/api/#map#remove) that should not be necessary, implying that all the children should care of releasing only their non-mapbox related resources.

It should just call remove. In the children, we may listen to the [remove event](https://www.mapbox.com/mapbox-gl-js/api/#map.event:remove) and, more important, in the componentWillUnmount we should check if `map.getStyle()` returns undefined before removing sources, layers or whatever.

I'm working on a PR.

**Comment by alex3165** [comment]
Good catch @lamuertepeluda 👍  looking forward for your PR

**Comment by alex3165** [comment]
@lamuertepeluda I pushed the changes related to this issue on master from your PR, I hope you don't mind ! see : https://github.com/alex3165/react-mapbox-gl/commit/b792de68eb5c922cb45352d5e81d151fe6b31a75

**Comment by lamuertepeluda** [comment]
@alex3165 of course I don't mind and I'm glad. 😉 
Feel free to grab/adapt anything u like from my PR/fork. I'm sadly a bit busy for contributing with a refactored PR(s) atm. Hope to do that in the next weeks.

**Comment by alex3165** [comment]
I had to revert the commit, doing that break the Layer component.

**Comment by alex3165** [comment]
https://github.com/alex3165/react-mapbox-gl/pull/245 should fix the issue

**Comment by alex3165** [comment]
I will close this issue as it is been resolved with the version 2.0.0. Please use https://github.com/alex3165/react-mapbox-gl/issues/237 to be updated on the state of 2.0.0.
