### ISSUE TITLE
Map displaced when "text-align: center" is set on some parent div

### ISSUE THREAD

**Issue by Pgsuarez** [alex3165/react-mapbox-gl#182]
Hi,
if some parent of the map has set the css property `text-align` to `center` (also `right`, `end`, etc) the map is displaced within his container like if the map was text.

I reproduced it here: https://github.com/Pgsuarez/react-mapbox-gl-debug/tree/text-align-bug

**Comment by alex3165** [comment]
https://github.com/alex3165/react-mapbox-gl/commit/da7c8e06c02de6840d5f7261802c1739f7f0f98f should fix it, check https://github.com/alex3165/react-mapbox-gl/issues/237 to follow the state of v2
