### ISSUE TITLE
upgrading 1.3.0 -> 1.7.0 regressed several issues

### ISSUE THREAD

**Issue by z0d14c** [alex3165/react-mapbox-gl#186]
Sadly, upgrading our `react-mapbox-gl` from 1.3.0 -> 1.7.0 caused several bugs to appear/re-appear for us.
Here are the main ones for us:
* fitBounds property no longer reliable on a page refresh for me; it seems that if the map is loading/rendering (not sure which), fitBounds does not fire properly. However, if I let the map load/stabilize completely and then e.g. navigate to something which creates passes a new fitBounds, it works fine.
* Map style/layer issues; stuff like ```layer 'polygon-fill-2584' does not exist in the map's style and cannot be queried for features```. This could be because of some workarounds we were using to handle map style changing, but I'm not completely sure.
* possibly more, i quit looking as hard to deal with these 2 because they are both app-breaking for us.

I'm writing this to remind myself to look at these and see if they are fixable in this repo's codebase, but also because I want to point out to the community how we probably need some sort of better testing around this to ensure these regressions don't happen. I am not completely sure how to go about that, because it doesn't seem like a unit-testing issue as much as integration testing w/ mapbox-gl, but I thought I'd throw it out there.

**Comment by kn0ll** [comment]
didn't dig too deep (just reverted), but upgrading from 1.4.1 to 1.7.0 broke the clusters implementation described in [this comment from #142](https://github.com/alex3165/react-mapbox-gl/issues/142#issuecomment-283398995).

**Comment by mark2685** [comment]
@kn0ll - I noticed the same issue, and confirmed that its version `1.6.0` that broke that implementation. I'm not seeing any errors, just that Layers tied to a Source by ID were not displaying.

I dropped back to `1.5.2` for now.

**Comment by alex3165** [comment]
I am sorry for that, anyone would have time to point me to the issue using https://github.com/alex3165/react-mapbox-gl-debug ? Thanks

**Comment by alex3165** [comment]
@mark2685 The layer and source component should work nicely togethers again, see https://github.com/alex3165/react-mapbox-gl/issues/194

**Comment by z0d14c** [comment]
tried to upgrade 1.3 -> 1.9 this time, and it worked a lot better 2 main bugs this time:

* for some reason using onClicks on fill layers caused some buggy "x layer does not exist and could not be queried for features" type errors. this was easy to work around for me, but worrying

* this one is worse, fitBounds seemed to not work in our app on a hard refresh for certain pages because state.map of the Map component wouldnt be instantiated (map wouldnt be loaded yet). i dont know why this changed on version upgrade, though. :(

**Comment by z0d14c** [comment]
Gonna try and look at this this weekend... im guessing something happened through the version to make the map load slower so that our fitBounds prop is unreliable now... will try and look this weekend but if anyone has any insight please do share...

**Comment by z0d14c** [comment]
for me a lot of issues are resolved with 1.10, basically the only change i had to make from 1.3 -> 1.10 was change some of the props that had their names changed. other than that, we're gravy. if anyone else wants to chime in with their issues they can, otherwise maybe we can close this?

**Comment by mark2685** [comment]
The issues I was seeing have been resolved as of the 1.8.0 release. Just updated to 1.10, and everything seems gravy as well!

I'm fine with closing.

**Comment by alex3165** [comment]
I will close the issue then, I will try to find time this weekend to resolve some issues, thanks everyone for being active on this project it is really nice to see developers using this library.
