### ISSUE TITLE
onMouseLeave -  Feature event dont work propertly

### ISSUE THREAD

**Issue by ufon** [alex3165/react-mapbox-gl#191]
I noticed that leave event dont fired. But I precisely remember that in older version (js build) this work normal. 
![image](https://cloud.githubusercontent.com/assets/4355972/24878758/153d4f4c-1e3d-11e7-8775-2efb7a4498a3.png)
![image](https://cloud.githubusercontent.com/assets/4355972/24878765/20f3959e-1e3d-11e7-8379-aa86d3682ac3.png)
I have compared a code, but extra diffs i didt noticed. Tnx for help.
P.S. Examples already have this bug (cursor dont hide all time in london-cycle.js)

**Comment by alex3165** [comment]
Gotcha, sorry for that, I will fix it

**Comment by alex3165** [comment]
@ufon I fixed it with the patched version `1.7.4` again sorry for that

**Comment by ufon** [comment]
tnx a lot!
