### ISSUE TITLE
Compile mapbox-gl-js using webpack

### ISSUE THREAD

**Issue by alex3165** [alex3165/react-mapbox-gl#20]
Compile mapbox-gl-js at build time instead of using the compiled file from mapbox.

**Comment by alex3165** [comment]
https://github.com/mapbox/mapbox-gl-js#using-mapbox-gl-js-with-webpack

**Comment by prebenl** [comment]
The precompiled file caused issues for me running a universal app (was complaining window not being available on server side).

I simply cloned the repo and switched the imports to "mapbox-gl", and now it works just fine. (I already had the necessary webpack config in place).

**Comment by alex3165** [comment]
Hi @prebenl, thanks for reporting this issue, i haven't really spend lot of time on this as it was just a warning but i didn't know that the pre-compiled version is failing when doing a server side rendering of the component.

I will have a look as soon as possible.

**Comment by alex3165** [comment]
https://github.com/alex3165/react-mapbox-gl/pull/25/files

**Comment by prebenl** [comment]
As to the exact why, I don't know either, but I think somewhere in the "mapbox-gl" library there is some kind of dynamic switching, allowing the "gl" library (also known as headless gl), to take over when you're on an environment where window / web-gl is not available (i.e. server).

**Comment by DominikLevitsky** [comment]
Hey, any updates on this? Would be really cool to have this fixed.

**Comment by buildbreakdo** [comment]
react-mapbox-gl references https://github.com/mapbox/mapbox-gl-js/blob/master/js/util/browser/browser.js when I believe it should reference https://github.com/mapbox/mapbox-gl-js/blob/master/js/util/browser.js?

**Comment by alex3165** [comment]
@DominikLevitsky Currently on it @philpl is helping on this 👍

**Comment by DominikLevitsky** [comment]
@alex3165 Hi. Any chances for us to get an update in the next couple of days? :)

**Comment by alex3165** [comment]
@DominikLevitsky I will give you an update by the end of the week-end and hopefully come up with a solution :)

**Comment by alex3165** [comment]
So now mapbox-gl-js is compiled using Webpack see https://github.com/alex3165/react-mapbox-gl/pull/43. I think it will still not be possible to render on the server side though because the library is using web worker for some operation and this won't work in a nodejs environment.

**Comment by philpl** [comment]
It's very hard to determine how to "make the switch" to the mocked browser of mapbox-gl. I think technically it's not hard to switch it around, but it's hard to determine, whether React is being rendered in a server-side context. If someone has input on that, I'd appreciate it
