### ISSUE TITLE
NavigationControl

### ISSUE THREAD

**Issue by alpha-beta-soup** [alex3165/react-mapbox-gl#204]
Is it possible to include a [NavigationControl](https://www.mapbox.com/mapbox-gl-js/example/navigation/) component? Currently when the map is rotated or tilted, it is difficult to return back to north-up and straight-down. With the standard Mapbox GL JS controls, you can just click on the compass icon (navigation control) to reset the view at the current zoom. It's possible to workaround with `map.addControl(new MapboxGl.NavigationControl())`, except that it conflicts with the `ZoomControl` component. I note that there's a [`NavigationControl`](https://github.com/alex3165/react-mapbox-gl/blob/463d9c2d059d28d0eb785b79d615cb144a80733d/src/util/mapbox-type.d.ts#L353) which I assumed I'd use in exactly the same way as `ZoomControl` or `ScaleControl` (just with no props) but it doesn't render, and it's not used in any example. So is it possible to include a `NavigationControl`?

**Comment by alex3165** [comment]
There is currently no Navigation control component, I would be happy to see such a component. Although I would use the same approach as `ZoomControl` and `ScaleControl` component and create real React component that reset the pitch and rotation of the map to their initial state manually.
