### ISSUE TITLE
Cluster click implementation

### ISSUE THREAD

**Issue by porchdog** [alex3165/react-mapbox-gl#208]
Hey all.  I'm trying to implement a way to show a popup list of clustered items when a cluster has been clicked.  Problem is, the cluster factory does not get passed the items that make up the cluster.  So when it is clicked, I don't know which items are in that cluster.

Any chance that the API could be modified such that the factory gets passed the array of markers that make up the cluster?  That would continue to provide the number of points (array length) as well as being able to know which markers make up the cluster.

Thanks for the component!

**Comment by alex3165** [comment]
Hey thanks for the issue it would indeed be possible. I can have a look when I have some time or I would be happy to have some help on this.

**Comment by Wykks** [comment]
Hi, I implemented this feature, with minimal changes to the API (no breaking changes).
https://github.com/alex3165/react-mapbox-gl/pull/306

**Comment by alex3165** [comment]
Release with version `2.2.0`, see: https://github.com/alex3165/react-mapbox-gl/releases/tag/v2.2.0
