### ISSUE TITLE
Configuring source, source-layer and filter propertites

### ISSUE THREAD

**Issue by charliedotau** [alex3165/react-mapbox-gl#22]
Hi there,

I can't tell from the examples / documentation if your component supports a tileSet configured like this using the Mapbox GL JS library directly:

    map.addLayer({
            "id": "my-id",
            "type": "fill",
            "source": "myMapboxHostedTileSetSource",
            "source-layer": "victoriaAustralia",
            "layout": {},
            "paint": {
                "fill-color": "#81D8D0",
                "fill-opacity": 0.5
            },
             "filter": ["==", "sub_region", "Gippsland"]

    });

I'm specifically asking about setting the source, source-layer and filter properties.  If this is possible could you provide an example and/or clarify in the documentation.

Thanks
Charlie

**Comment by alex3165** [comment]
Hi Charlie,

Indeed it's not possible to do it right now, the source property of the layer is defined by the id that you pass to the layer react component and used to bind the children elements (feature source) to the parent layer element.

Is your use case to be able to define a layer using a source defined directly in mapbox studio ? Because the react layer logic automatically create a mapbox layer and a mapbox source which is something that can be improved i think.

**Comment by alex3165** [comment]
For the source-layer and filter properties i can easily add it.

**Comment by charliedotau** [comment]
Hi @alex3165 thanks for your reply.    Yeah, I have a core TileSet I've uploaded to Mapbox.  I reference it  by adding a source like this:

    map.addSource('myMapboxHostedTileSetSource', {
        type: 'vector',
        url: 'mapbox://charlie.4fsn42ds'
    });

Then once I have my source I add a number of fill layers for different areas on the map.  I will have a look at defining my source via the id I pass to the layer react component.  As for source-layer and filter, it woul d be wonderful if you could add that.     

Love the component by the way.    So, so useful.

**Comment by alex3165** [comment]
Ok i did the modifications so that it works for this use case without breaking the actual API, can you try the following example using the branch `feature/layer-without-source` of the github repository (to test it).

If it's good i will merge and release a new npm version.

```
        <Layer
          id="my-id"
          sourceId="myMapboxHostedTileSetSource"
          type="fill"
          layerOptions={{
            "source-layer": "victoriaAustralia",
            "filter": ["==", "sub_region", "Gippsland"]
          }}
          layout={{}}
          paint={{ "fill-color": "#81D8D0", "fill-opacity": 0.5 }}/>
```

Ps: You can target the branch of the Github repository using :
```
"react-mapbox-gl": "https://github.com/alex3165/react-mapbox-gl.git#feature/layer-without-source"
````
in your package.json file

**Comment by charliedotau** [comment]
Hi @alex3165.   Thanks. Very much appreciated.

I would say that I'll test it tonight, but I'm a bit stuck.  I don't quite get how I define my source.  E.g the equivalent of this:

    map.addSource('myMapboxHostedTileSetSource', {
        type: 'vector',
        url: 'mapbox://charlie.4fsn42ds'
    });

The bit that most matters here is the URL.   And I don't see where / how I define that with your library.    Could you show me an example.  Thanks kindly

**Comment by fc-io** [comment]
The way I did it was to add the source in `onStyleLoad`

``` js
<ReactMapboxGl
  ...
  onStyleLoad={(map) => {
    map.addSource('data', {
      type: 'geojson',
      data: 'url'
    })
    this.setState({hasAddedSource: true})
  }
/>
  {
    this.state.hasAddedSource && 
    <Layer
      id="my-id"
      sourceId="data"
      type="fill"
      layerOptions={{filter: ['==', 'type', 'building']}}
      layout={{}}
      paint={{'fill-color': '#81D8D0', 'fill-opacity': 0.5}}
    />
  }
</ReactMapboxGl>
```

maybe something similar would work for you. And/or maybe there is a better way...

**Comment by charliedotau** [comment]
No luck for me.    I'm just editing the all-shapes.js file in my local copy of this repo.

My _onStyleLoad function in the allShapes class looks like this

    _onStyleLoad(map) {
        console.log("Style loaded: ", map);
        map.addSource('charlieSource', 
            {
                type: 'vector',
                url: 'mapbox://charlie.ZZZZZZZZ'
            });
     }

My render function in the allShapes class looks like this:

    render() {
        return (
          <ReactMapboxGl
            style={style}
            onClick={this._onClickMap}
            onStyleLoad={this._onStyleLoad}
            accessToken={accessToken}
            center={[144.96, -37.81]}
            movingMethod="jumpTo"
            containerStyle={containerStyle}>
            <ScaleControl/>
            <ZoomControl/>
        
            <Layer
              id="myId"
              sourceId="charlieSource"
              type="fill"
              layerOptions={{
                "source-layer": "victoriaAustralia",
                "filter": ["==", "sub_region", "Gippsland"]
              }}
             layout={{"visibility": "visible"}}
              paint={{ "fill-color": "#81D8D0", "fill-opacity": 0.5 }}/>

          </ReactMapboxGl>
        );
     }

The map appears, but i don't see my layer.    In the console I get:
 Uncaught Error.  There is already a source with this id (mapbox-gl.js ....). I get this message twice.  If I remove the layer altogether the error goes away.

Interestingly in the console I never see the "Style loaded" output.

I updated the package.json - the relevant line looks like this:

    "repository": {
        "type": "git",
        "url": "git+https://github.com/alex3165/react-mapbox-gl.git#feature/layer-without-source"
     }

I'm a total noob at this, so appreciate any insights here. 
thanks all
Charlie

**Comment by alex3165** [comment]
I think it's not necessary to use react-mapbox-gl for this kind of source / layer. If you don't need to interact with it (if it's just a static source like the tiles) you should define it in the map style :

1/

```
<ReactMapboxGl
  style = {{
    // your styles properties
    sources: {
      // your sources
      myMapboxHostedTileSetSource: {
        type: 'vector',
        url: 'mapbox://charlie.4fsn42ds'
      }
    }
  }}
/>
```

However if your style is an url you should define your source directly in mapbox studio, giving this url and the token, mapbox-gl-js automatically download your style and will apply it.

Then for the layer you can either define it on mapbox studio as well or use react-mapbox-gl layer like this :

```
<Layer
  id="my-id"
  sourceId="myMapboxHostedTileSetSource"
  type="fill"
  layerOptions={{
    "source-layer": "victoriaAustralia",
    "filter": ["==", "sub_region", "Gippsland"]
  }}
  layout={{}}
  paint={{ "fill-color": "#81D8D0", "fill-opacity": 0.5 }}/>
```


2/

If you still want to do it manually, as @fc-io mentioned before you can do this (I pushed a modification on the branch `feature/layer-without-source` so that you don't have to use the state) :

```
<ReactMapboxGl
  ...
  onStyleLoad={(map) => {
    map.addSource('data', {
      type: 'geojson',
      data: 'url'
    })
  }
/>
  <Layer
    id="my-id"
    sourceId="data"
    type="fill"
    layerOptions={{filter: ['==', 'type', 'building']}}
    layout={{}}
    paint={{'fill-color': '#81D8D0', 'fill-opacity': 0.5}}
  />
</ReactMapboxGl>
```

To use the correct branch you actually don't need to update the package.json file if you are trying directly on the project, you should just checkout to this branch :
```
git checkout feature/layer-without-source
```

**Comment by alex3165** [comment]
You can look at this commit https://github.com/alex3165/react-mapbox-gl/commit/c344690a2761f9d286d4355e22f38830dad86e89 i have added an example of how to use a source from the style object which is the file `style.json`

**Comment by alex3165** [comment]
The branch is merged on master, you can test everything directly from master

**Comment by charliedotau** [comment]
Happy to report the second option - adding a source explicitly in the OnStyleLoad event - works nicely on master branch.  So thanks very much to @alex3165 and @fc-io.

I'm struggling with the first option though Alex. I.e where you suggest defining the source on the layer itself.   To be clear, I've uploaded geoJSON to Mapbox which creates a vector Tileset for me.   Those tillesets can be reference via a url such as mapbox://charlie.4fsn42ds.     

My client app uses that tileset to create various different layers, based on user interaction.     Imagine a simple app for example that has a dropdown for each state of Australia.    When the user selects say Victoria, then I want to show multiple fill layers, each representing the different sub regions of Victoria.       For these I have multiple layers that will show/hide.  Each of those layers is based off the same source (e.g the tileset for Victoria).  

Where I struggle with your (first) example in your last comment is that it doesn't reference the tileset using the URL.  The id - myMapboxHostedTileSetSource - doesn't have any meaning in Mapbox in and of itself.  That's just an ID just by the client app.   So specifying myMapboxHostedTileSetSource without the URL seems incomplete.  I just don't see how that would work.    You can't do this in the Mapbox GL JS library AFAIK.     

So I think I have what I need to progress, but I would like to resolve my understanding around your first example just so we're on the same page.

Thanks again
Charlie

**Comment by alex3165** [comment]
Ok well i would suggest you to have multiple geojson files for every sub-regions of Victoria, I have just added the possibility to update the style property of the map, i would do something like this :

```
// subregions.json

[
  {
    // Geojson for region 1
  },
  {
    // Geojson for region 2
  }
  //...
]


// all-shapes.js

import Subregions from "./subregions.json";

...

onChangeSubRegion(index) {
  this.state({ subregion: index });
}

render() {
  return (
    <ReactMapboxGl
      style={Subregions[this.state.subregion]}
      accessToken={accessToken}
      center={this.state.center}
      containerStyle={containerStyle}>
      ...
    </ReactMapboxGl>
  );
}


```

React-mapbox-gl API of the layer functionality is more adapted for creating layers and sources that require user interactions.
