### ISSUE TITLE
Module not found

### ISSUE THREAD

**Issue by yarnball** [alex3165/react-mapbox-gl#222]
Hi, I keep getting an error "Module not found". I have followed the instructions and installed `npm install react-mapbox-gl --save` but I still get this error.

I used create-reaact-app as my boiler plate.

Any ideas on how to fix? Thanks

```
Error in ./~/react-mapbox-gl/lib/map.js
Module not found: 'mapbox-gl' in /Users/user1/Dev/A51/Temp/map/node_modules/react-mapbox-gl/lib

 @ ./~/react-mapbox-gl/lib/map.js 21:15-35

Error in ./~/react-mapbox-gl/lib/util/overlays.js
Module not found: 'mapbox-gl' in /Users/user1/Dev/A51/Temp/map/node_modules/react-mapbox-gl/lib/util

 @ ./~/react-mapbox-gl/lib/util/overlays.js 3:18-38
```

**Comment by alex3165** [comment]
Hey you have to manually add `mapbox-gl` to your project `npm i --save mapbox-gl` should solve it
