### ISSUE TITLE
Changing Map style causes existing layers to disappear

### ISSUE THREAD

**Issue by emgeee** [alex3165/react-mapbox-gl#225]
I'm trying to allow someone to toggle between street view and a satellite view. I have several `<GeoJSONLayer>`'s mounted and working fine but when I change the `<Map>` style, those layers appear to disappear.

An error is thrown at line 114 of geojson-layer.ts saying `Uncaught TypeError: Cannot read property 'setData' of undefined`

**Comment by z0d14c** [comment]
currently this is one of the big gotcha's with this lib. you need to remove the layers, change the style, then add the layers back for it to work properly. :(

**Comment by emgeee** [comment]
Well that's unfortunate. Any idea why that is?

**Comment by z0d14c** [comment]
nope, we have an existing bug in our app related to this issue, have fixed several times in our implementation over this lib but it keeps popping up; i dont mind doing the workaround (making sure all layers are removed, changing style, then adding them back), but it kinda sucks that it keeps popping up -- i think getting some guarantees and tests around how the map style changing behaves would be 👍 and if i can possibly find some time I'll try and work on it...

**Comment by emgeee** [comment]
That's fair. I'm still trying to image with that workaround looks like since I imagine when you say "remove all layers, then add them back" you have to have a boolean somewhere that removes all inner components from the Map component, waits for a new `render()`, toggles the style, then toggle the boolean back so all the components are re-added. Did I get that right?

**Comment by z0d14c** [comment]
yeah you got it right -- it looks like this feature is now working for me without the workaround, though. im on version 1.11.0

**Comment by alex3165** [comment]
I will close this issue as it is been resolved with the version 2.0.0. Please use https://github.com/alex3165/react-mapbox-gl/issues/237 to be updated on the state of 2.0.0.

**Comment by alex3165** [comment]
Released a fix from @SBRK with version `2.5.2`
