### ISSUE TITLE
Inspiration and thanks!

### ISSUE THREAD

**Issue by cpsubrian** [alex3165/react-mapbox-gl#226]
After getting a lot of great mileage out of `react-mapbox-gl` I just wanted to say thanks for your awesome work! I also wanted to share something I've been working on that might inspire a few changes here. 

Basically I started with the component/context philosophy of this library, and tried to strip it down to be as close to the `mapbox-gl-js` API as possible. I also took the opportunity to abstract out some basic building blocks into components such as `<MapEvent>`, `<LayerEvent>`, `<Hover>`, etc. I was also able to clean up the map initialization bit by splitting it out into a couple components such as `<MapGL>`, `<MapOptions>` and `<MapEvents>` (which just delegates to a bunch of `<MapEvent>`).

Anyhow, I totally recognize how difficult it is to manage refactors on a library as widely used as yours, and that's largely why I set out to experiment in my own space. Hope it gives you some ideas. It's still going through some major changes but feel free to take a look.

https://github.com/TerraEclipse/react-stack/tree/master/modules/react-mapbox

**Comment by alex3165** [comment]
Hi @cpsubrian, thanks for that. I think it is a good idea but it would make everything a bit more complicated and I wanted to keep everything as simple as possible. Although someone suggested to  separate the static props from the one that get updated across rendering https://github.com/alex3165/react-mapbox-gl/issues/165 and I think this would be my first priority. @philpl any thought about creating components for `Events`?

**Comment by cpsubrian** [comment]
Hey @alex3165 I definitely understand the desire for simplicity. FWIW I moved the repo and you can see what this concept looks like in practice here: https://github.com/TerraEclipse/react-mapboxgl/tree/master/modules/core/src

There are a lot of components but each one is very simple and focused. I personally think it makes the code easier to reason about and adding new map options or other things is a simple affair. For example, I really like how `MapPosition` is responsible for all position-related options as well as calling mapbox-gl-js methods when the position needs to change.

```
import React from 'react'
import PropTypes from 'prop-types'
import _ from 'lodash'

class MapPosition extends React.Component {
  static propTypes = {
    // Map position options.
    center: PropTypes.arrayOf(PropTypes.number),
    zoom: PropTypes.number,
    minZoom: PropTypes.number,
    maxZoom: PropTypes.number,
    maxBounds: PropTypes.array,
    bearing: PropTypes.number,
    pitch: PropTypes.number,

    // Custom position options.
    bbox: PropTypes.oneOfType([
      PropTypes.array,
      PropTypes.object
    ]),
    padding: PropTypes.oneOfType([
      PropTypes.number,
      PropTypes.object
    ]),
    moveMethod: PropTypes.oneOf([
      'jumpTo',
      'easeTo',
      'flyTo'
    ]),
    moveAround: PropTypes.array,
    moveAnimationOptions: PropTypes.object,
    moveFlyToOptions: PropTypes.object
  }

  static defaultProps = {
    // Default map options.
    center: [
      -0.2416815,
      51.5285582
    ],
    zoom: 11,
    minZoom: 0,
    maxZoom: 20,
    bearing: 0,
    pitch: 0,

    // Default custom options.
    moveMethod: 'flyTo',
    moveAnimationOptions: {},
    moveFlyToOptions: {}
  }

  static contextTypes = {
    map: PropTypes.object
  }

  // Called when the map is initally created.
  static getOptions (props) {
    let pickFrom = _.defaults({}, props, MapPosition.defaultProps)
    let picked = _.pick(pickFrom, _.keys(MapPosition.propTypes))
    return _.omit(picked, [
      'bbox',
      'padding',
      'moveMethod',
      'moveAround',
      'moveAnimationOptions',
      'moveFlyToOptions'
    ])
  }

  componentDidMount () {
    let {map} = this.context
    if (this.props.bbox) {
      map.fitBounds(this.props.bbox, {
        padding: this.props.padding || 0
      })
    }
  }

  componentWillReceiveProps (nextProps) {
    const {map} = this.context
    const center = map.getCenter()
    const didCenterUpdate = (
      this.props.center !== nextProps.center && (
        nextProps.center[0] !== center.lng ||
        nextProps.center[1] !== center.lat
      )
    )

    const zoom = map.getZoom()
    const didZoomUpdate = (
      this.props.zoom !== nextProps.zoom &&
      nextProps.zoom !== zoom
    )

    const bearing = map.getBearing()
    const didBearingUpdate = (
      this.props.bearing !== nextProps.bearing &&
      nextProps.bearing !== bearing
    )

    const pitch = map.getPitch()
    const didPitchUpdate = (
      this.props.pitch !== nextProps.pitch &&
      nextProps.pitch !== pitch
    )

    if (didZoomUpdate || didCenterUpdate || didBearingUpdate || didPitchUpdate) {
      let cameraOptions = {
        center: didCenterUpdate ? nextProps.center : center,
        zoom: didZoomUpdate ? nextProps.zoom : zoom,
        bearing: didBearingUpdate ? nextProps.bearing : bearing,
        pitch: didPitchUpdate ? nextProps.pitch : pitch,
        around: nextProps.moveAround
      }
      map[nextProps.moveMethod](_.extend(
        cameraOptions,
        nextProps.moveMethod !== 'jumpTo'
          ? nextProps.moveAnimationOptions
          : null,
        nextProps.moveMethod === 'flyTo'
          ? nextProps.moveFlyToOptions
          : null
      ))
    }

    if (!_.isEqual(this.props.bbox, nextProps.bbox)) {
      map.fitBounds(nextProps.bbox, {
        padding: nextProps.padding || 0,
        linear: nextProps.moveMethod !== 'flyTo'
      })
    }
  }

  render () {
    return null
  }
}

export default MapPosition
```

Anyhow, like I said your work on this module has been outstanding and it's been really fun to iterate on it in my own way.
