### ISSUE TITLE
Zoom resets on State Change

### ISSUE THREAD

**Issue by cmtoomey** [alex3165/react-mapbox-gl#228]
I render a map like normal 
`<ReactMapboxGl
        style="mapbox://styles/"
        accessToken=""
        containerStyle={{
          height: "89vh",
          width: "100vw"
        }}
        center={[-99.456478, 39.878675]}  
        zoom={[4]}
        onClick={this.click.bind(this)}
      >`

I have another drop-down component that updates a redux store with results of a query. When zoom is specified, any time I change the drop-down, the view resets (both zoom and center). It seems like it's always re-rendering to the default.

**Comment by stereobooster** [comment]
Use `onZoomEnd` to capture zoom and store it in redux store.

**Comment by cmtoomey** [comment]
That works - it's a little hacky, but it works.

**Comment by alex3165** [comment]
Hey sorry didn't see your issue before, please read the disclaimer section of the readme. If you don't want your zoom to update, don't break the reference equality between 2 renders, keep a reference to your zoom array somewhere. It doesn't have to sit in the redux store, it could be a class property or in a component state or just a simple constant outside of your class.

**Comment by stereobooster** [comment]
> That works - it's a little hacky, but it works.

You partially right. This is actually idiomatic React. Consider HTML input (not in React) which can update it's state itself. But React's  approach is to use [controlled components](https://facebook.github.io/react/docs/forms.html), which prevent HTML inputs from updating itself state.

The hacky part is that, map with explicitly passed zoom and without zoom processing callback should have zoom locked. 

Like second map on [this page](https://uber.github.io/react-map-gl/#/interactivity).
