### ISSUE TITLE
Overlapping Markers 

### ISSUE THREAD

**Issue by stereobooster** [alex3165/react-mapbox-gl#229]
Not sure if this a bug or a feature

<img width="234" alt="screen shot 2017-05-24 at 00 52 31" src="https://cloud.githubusercontent.com/assets/179534/26379774/51c3e20a-401b-11e7-9161-7793162d8c19.png">

Other problem is how to make sure that "selected" marker is over

<img width="289" alt="screen shot 2017-05-24 at 00 57 30" src="https://cloud.githubusercontent.com/assets/179534/26379939/03d9289c-401c-11e7-9c10-664df5cf1ef3.png">

**Comment by stereobooster** [comment]
Obvious solution is to sort markers:

```js
  .sort((a, b) => {
    if (selected && b.id === selected.id) return -1
    if (selected && a.id === selected.id) return 1
    return b.coordObject.lat - a.coordObject.lat
  })
```

but this kind of contrary to declarative approach. The question is: should library support this out of the box or is it some kind of pattern which can be listed in wiki? Or I miss something and this should be done other way?

**Comment by alex3165** [comment]
Are you using the Marker component? if yes maybe you want to cluster your markers using Cluster component? If you use Layer and Feature components to display your markers, clustering is done for you.

**Comment by stereobooster** [comment]
I'm using `Marker`. Code pretty close to this one https://github.com/alex3165/react-mapbox-gl/pull/207/commits/7b1933194498beeaf46dcbefe6d071ff988b32a2. I will give a try `Cluster` component.

**Comment by stereobooster** [comment]
For some reason cluster doesn't work for me. Plus it just hide overlapping markers instead of tacking them in right order. But my way with `sort` works for me.

**Comment by ats1999** [comment]
> For some reason cluster doesn't work for me. Plus it just hide overlapping markers instead of tacking them in right order. But my way with `sort` works for me.

yes
