### ISSUE TITLE
popup component upgrading from 1.6 -> 1.10

### ISSUE THREAD

**Issue by jenyeeiam** [alex3165/react-mapbox-gl#230]
Just upgraded my version from 1.6 to 1.10, and now the popup is a bar across the top.  Was this intended? 
![selection_024](https://cloud.githubusercontent.com/assets/19957645/26414388/eac13dde-4063-11e7-86f5-7b467426aaf2.png)
![selection_023](https://cloud.githubusercontent.com/assets/19957645/26414395/f01a4870-4063-11e7-832c-ff72b0db1822.png)

**Comment by stereobooster** [comment]
I'm using `1.11.0` and there is no problem. Do you use custom styles for popup contents?

**Comment by jenyeeiam** [comment]
Is your popup a bar across the top? @stereobooster

**Comment by jenyeeiam** [comment]
Oh man it was my classnames!  Note: Don't name your popup mapbox-popup....
