### ISSUE TITLE
GeoJSON click events

### ISSUE THREAD

**Issue by dvreed77** [alex3165/react-mapbox-gl#234]
How can I respond to a click on feature in a GeoJSON Layer, specifically a point feature?  I would like to mimic the behaviour found in the MapboxGL documentation [here](https://www.mapbox.com/mapbox-gl-js/example/popup-on-click/):

```javascript
map.on('click', 'places', function (e) {
        new mapboxgl.Popup()
            .setLngLat(e.features[0].geometry.coordinates)
            .setHTML(e.features[0].properties.description)
            .addTo(map);
    });
```

**Comment by alex3165** [comment]
You can use `onStyleLoad` prop of the map component to get an instance of the map then use it to add you event listener and your popup.

I would suggest to use `Layer` and `Feature` with `Popup` component instead though, have a look at the london-cycle example: https://github.com/alex3165/react-mapbox-gl/blob/master/example/src/demos/londonCycle.tsx
