### ISSUE TITLE
Custom Icon

### ISSUE THREAD

**Issue by warka0** [alex3165/react-mapbox-gl#241]
Hi!

I don't understand how to add a custom icon on a layer.

I try to have a layer of one particular png ! :)

Which part did i missed?

Thx!

**Comment by alex3165** [comment]
You have to add your icon on mapbox studio and define the right icon name to your Layer. see : https://www.mapbox.com/help/custom-images/

**Comment by warka0** [comment]
Thx !

**Comment by JulienMelissas** [comment]
@imasif - This link should be up to date: https://docs.mapbox.com/help/tutorials/markers/

**Comment by mklopets** [comment]
@JulienMelissas I don't think the new tutorial they have really covers this too well.

To add custom images to your Mapbox style:
1) open Mapbox Studio (https://studio.mapbox.com)
2) open the map style you're using
3) open "Images" from the top right menu (or click `i`)
4) hit "Upload SVG image"

The filename of your uploaded icon (minus the extension) will be its icon name. After uploading and refreshing the page, the image manager should show this new icon. Now you can use this icon name to render it on your map, e.g by using a symbol Layer.
