### ISSUE TITLE
How to use another style?

### ISSUE THREAD

**Issue by Alan01252** [alex3165/react-mapbox-gl#243]
I'm pretty sure I'm doing something stupid here, but how do you use a style created in mapglstudio?

I've tried changing the accessToken/style variables in https://github.com/alex3165/react-mapbox-gl-debug but it still seems to display the streets-v7 style regardless.

Any help would be greatly appreciated!

Cheers

Alan

**Comment by alex3165** [comment]
Hey, have a look at https://github.com/alex3165/react-mapbox-gl/blob/master/example/src/demos/switchStyle.tsx it should help you understand how to update the style of the map.
