### ISSUE TITLE
How to get reference to map object?

### ISSUE THREAD

**Issue by stereobooster** [alex3165/react-mapbox-gl#246]
This doesn't seem to work

```js
ref={ map => { this.map = map } }
```

I want to do something like [this](https://www.mapbox.com/mapbox-gl-js/example/scroll-fly-to/), but I need reference for this.

**Comment by aleksplus** [comment]
did you try access map object from state `this.map.state.map`?

refs should work after component is [mounted](https://facebook.github.io/react/docs/refs-and-the-dom.html#adding-a-ref-to-a-dom-element)

**Comment by stereobooster** [comment]
I tried this, but unfortunately it is null 

```js
  componentDidMount() {
    console.log(this.map.state.map)
  }
```

strange thing if I log `this.map` I see `state.map` WAT? Still looking into this

**Comment by stereobooster** [comment]
```js
class ReactMapboxGlCustom extends ReactMapboxGl {
  componentDidMount() {
    ReactMapboxGl.prototype.componentDidMount.call(this)
    this.props.onMount && this.props.onMount(this.state.map) // this.state.map is null
  }
}
```

**Comment by stereobooster** [comment]
For future googlers there is `onStyleLoad` which is called when `map` is available

```jsx
<ReactMapboxGl onStyleLoad={ (map) => { ... } } />
```
