### ISSUE TITLE
Pass pointerEvents: none to markers in examples

### ISSUE THREAD

**Issue by stereobooster** [alex3165/react-mapbox-gl#248]
Pass `pointerEvents: none` to markers in examples (everywhere where zoom with scroll enabled)

Extracted from: https://github.com/alex3165/react-mapbox-gl/issues/237

**Comment by alex3165** [comment]
https://github.com/alex3165/react-mapbox-gl/pull/250 should do the trick

**Comment by alex3165** [comment]
I will close this issue as it is been resolved with the version 2.0.0. Please use https://github.com/alex3165/react-mapbox-gl/issues/237 to be updated on the state of 2.0.0.

**Comment by alex3165** [comment]
I have actually reverted it as I think it is an unexpected behaviour for users that want to click on the marker, see: https://github.com/alex3165/react-mapbox-gl/pull/263

**Comment by stereobooster** [comment]
The question is how they do not make zoom buggy and markers are clickable in this example https://www.mapbox.com/bites/00281/
