### ISSUE TITLE
Expose `css` for import in webpack project

### ISSUE THREAD

**Issue by stereobooster** [alex3165/react-mapbox-gl#249]
Expose `css` for import in webpack project instead of injecting in header. This way it will be minified e.g.

```js
import from "react-mapbox-gl/css";
```

Extracted from: https://github.com/alex3165/react-mapbox-gl/issues/237

**Comment by alex3165** [comment]
I will close this issue as I don't think it would be useful anymore

**Comment by stereobooster** [comment]
Just updated to the latest version. Still same issue. This how my optimised build of CRA project with static render looks like:

```html
<link href="/static/css/main.27ae89a6.css" rel="stylesheet"><style>
  .mapboxgl-map {
      font: 12px/20px 'Helvetica Neue', Arial, Helvetica, sans-serif;
      overflow: hidden;
      position: relative;
      -webkit-tap-highlight-color: rgba(0,0,0,0);
  }

  .mapboxgl-ctrl-top-left,
  .mapboxgl-ctrl-top-right,
...
```
