### ISSUE TITLE
create a draggable marker

### ISSUE THREAD

**Issue by Mencls** [alex3165/react-mapbox-gl#251]
I'm currently wondering what's the best way to create draggable markers.
Easiest way would be to do it like the mapbox example, using ```mouseenter```, ```mouseleave```, ```mouseup```  and ```mousedown```  but I realised you didn't implement the last event.

So I'm a bit confused. Using ```onDrag``` doesn't seem to be a good idea as ``` dragPan.disable()``` needs to be called at some point.

Last solution would be to get the map instance with ```ref``` and use its ```mousedown``` event, which seems a bit hacky.

What's your opinion?

**Comment by alex3165** [comment]
Hey @Mencls, thanks for the issue someone already asked that at some point but I lost track of this feature, I think this is something that could come with the version 2.0.0. In term of API I think it should be a prop you have on the Feature component like so
```jsx
<Feature
  coordinates=[0,0]
  draggable={true}
/>
```
And all the logic that detect `mouseup` / `mousedown` and set the geojson data should sit at the `Layer` level I think.

Just for reference: https://www.mapbox.com/mapbox-gl-js/example/drag-a-point/

**Comment by Mencls** [comment]
I agree, a ```draggable``` prop on the Feature component would be great. Also an ```onDragEnd``` event would definitely be useful, in order to update the data if needed.

Thanks for the update!

**Comment by alex3165** [comment]
https://github.com/alex3165/react-mapbox-gl/pull/256 is a first step toward a draggable feature

**Comment by alex3165** [comment]
https://github.com/alex3165/react-mapbox-gl/pull/257 should do the trick

**Comment by alex3165** [comment]
I will close this issue as it is been resolved with the version 2.0.0. Please use https://github.com/alex3165/react-mapbox-gl/issues/237 to be updated on the state of 2.0.0.

**Comment by cyrilchapon** [comment]
Hey. I'm lost, was a draggable marker created, or were you talking about draggable feature ?

**Comment by alex3165** [comment]
Hey, we were talking about draggable feature
