### ISSUE TITLE
Marker Render Not Smoot when drag and change map position

### ISSUE THREAD

**Issue by nontachaiwebdev** [alex3165/react-mapbox-gl#252]
Hi this repo is awesome but i found a bit of issue.In laptop browser everything look great not any problem But when i switch to iphone to play map when drag for change map position a marker not smoot for change position too.

Do you think About This?

**Comment by alex3165** [comment]
I think it is unlikely it would be an issue with react-mapbox-gl but instead something for mapbox-gl. I would be happy to investigate if you can reproduce your issue with https://github.com/alex3165/react-mapbox-gl-debug

**Comment by alex3165** [comment]
I will close this issue as it is inactive, please feel free to open a new one with the reproduced bug if it is still happening.
