### ISSUE TITLE
Module not found: Error: Can't resolve 'prop-types' in '/node_modules/.registry.npmjs.org/react-mapbox-gl/1.12.0/node_modules/react-mapbox-gl/lib'

### ISSUE THREAD

**Issue by vjpr** [alex3165/react-mapbox-gl#271]
I am using webpack. Why is `prop-types` listed as a devDep if its used in the prod code?

**Comment by alex3165** [comment]
Should be fixed with version `2.0.3`, prop-types is a `peerDependencies`
