### ISSUE TITLE
Clusters misbehaving?

### ISSUE THREAD

**Issue by MindRave** [alex3165/react-mapbox-gl#272]
Hello there!

Thank you for the components, they work as desired and things are looking pretty good. :)

One small issue/question: either I'm misunderstanding something (very probably the case), or Clusters are totally misbehaving for me. When I got only One entry in a Cluster left, shouldn't it go back to being a Marker?

<img width="1053" alt="screen shot 2017-06-18 at 13 43 47" src="https://user-images.githubusercontent.com/4063406/27260424-47601b38-542c-11e7-9a6c-995b67939a64.png">

**Comment by alex3165** [comment]
Hey you can use the v2 `npm i react-mapbox-gl@next` where Cluster component is fixed. Should be released this week.

**Comment by alex3165** [comment]
Should now be fixed with version `2.0.3` on main release
