### ISSUE TITLE
Error with ReactMapboxFactory

### ISSUE THREAD

**Issue by gillioa** [alex3165/react-mapbox-gl#277]
Here is the error I get when I try to use react-mapbox-gl : 
`ReactMapboxFactory(...): A valid React element (or null) must be returned. You may have returned undefined, an array or some other invalid object.`

Here is my code : 
```
render() {
    return (
      <div>
        <ReactMapboxGl
          style="mapbox://styles/mapbox/streets-v8"
          accessToken="token"
          containerStyle={{
            height: '100vh',
            width: '100vw'
          }}>
        </ReactMapboxGl>
      </div>
    )
  }
```
I didn't find any way to make it works.
Thank you for your help.

**Comment by alex3165** [comment]
Hey, have a look at the documentation or at the example to see how to use the Map component. It is a function that return the Map component.

**Comment by gillioa** [comment]
Ok, my bad. I took the example from the 1.12 version. Thank you.
