### ISSUE TITLE
Features do not render until map interacted with when using fitBounds

### ISSUE THREAD

**Issue by superfunkminister** [alex3165/react-mapbox-gl#281]
When using fitBounds I have to interact with the map first (zoom in, pan etc) in order for my features and directions to show.

**Comment by superfunkminister** [comment]
Update: I have tried using `onStyleLoad={this.setBounds.bind(this)}` and then setting the bounds via `map.fitBounds(this.state.boundingBox);` however this seems to have exactly the same effect!

**Comment by alex3165** [comment]
Hey @superfunkminister, could you reproduce the issue with https://github.com/alex3165/react-mapbox-gl-debug, that would be very helpful! thanks

**Comment by alex3165** [comment]
@superfunkminister Can you tell me if the bug is still there with version `2.1.0`?

**Comment by superfunkminister** [comment]
Unfortunately not... I will try reproduce using the debug repo as soon as I get a spare moment!

**Comment by superfunkminister** [comment]
Tried reproducing the issue using the debug app and the problem wasn't there. Seems like you need this exact combination of dependencies for it to work!

```json
"dependencies": {
	"mapbox": "^1.0.0-beta8",
	"mapbox-gl": "^0.37.0",
	"react-mapbox-gl": "^2.1.0"
}
```

**Comment by alex3165** [comment]
Thank you @superfunkminister , you probably don't need `mapbox` though. I will close this issue then.
