### ISSUE TITLE
Get coordinate on click

### ISSUE THREAD

**Issue by Ricardo-C-Oliveira** [alex3165/react-mapbox-gl#285]
How can we get the cursor coordinate using the onClick event on the map?

Here is how I'm trying:

```
_onClickMap(e) {
        console.log(e.lngLat);
    }

render() {
        return <div>
            <Map
                style="mapbox://styles/mapbox/outdoors-v10"
                containerStyle={{
                    height: 400,
                    width: "100vw",
                    marginTop: 60
                }}
                center={[-104.99, 39.75]}
                zoom={[9]}
                onClick={this._onClickMap}/>
           </div>
````
I would expect to be able to access the `lngLat` property similarly to this example: https://www.mapbox.com/mapbox-gl-js/example/mouse-position/

**Comment by alex3165** [comment]
Almost that, sorry it is not clear in the documentation, here is what you need:
```
_onClickMap(e, map) {
  console.log(map.lngLat);
}
```

**Comment by LewisYoul** [comment]
Thanks so much for this!

**Comment by juliotoscano** [comment]
Thanks!!!

**Comment by patofw** [comment]
Could this be implemented in Kepler Gl? Do you have any guide in where should I add this?

**Comment by dstiglr** [comment]
Cool

**Comment by SanHolo101** [comment]
how do i get only the longitude or the latitude?

**Comment by mklopets** [comment]
Just read out the property you care about from `evt.lngLat` @SanHolo101

**Comment by Murtala-1** [comment]
Thanks, You save my day
