### ISSUE TITLE
Module not found: Can't resolve 'mapbox-gl' in '/Users/nsurte/rnd/image-pipeline-ui/node_modules/react-mapbox-gl/lib'

### ISSUE THREAD

**Issue by niksinfinite10** [alex3165/react-mapbox-gl#289]
./~/react-mapbox-gl/lib/map.js is dependent on mapbox-gl to resolve this issue you need to install mapbox-gl manually

**Comment by alex3165** [comment]
It is done on purpose you need to install mapbox-gl yourself, I have updated the readme to make it clearer https://github.com/alex3165/react-mapbox-gl#how-to-start.
