### ISSUE TITLE
Mapbox Attribution Issue

### ISSUE THREAD

**Issue by Yitaek** [alex3165/react-mapbox-gl#291]
Mapbox attribution control is turned off by default (although the doc indicates that it is turned on). If you are building demos using Mapbox, apparently it violates their Terms fo Service.

**Comment by alex3165** [comment]
Hey @Yitaek , the `attributionControl` property is turned on by default as you can see on the examples on Github pages http://alex3165.github.io/react-mapbox-gl/.
