### ISSUE TITLE
Missing onLoad event

### ISSUE THREAD

**Issue by benjaminhon** [alex3165/react-mapbox-gl#295]
it seems to be missing, it is needed for plugins like mapbox gl draw, where you can only do things after the on load event

**Comment by alex3165** [comment]
You can use `onStyleLoad ` which is doing `map.on('load')` under the hood

**Comment by ollyde** [comment]
That's really poor. How can we call 'map' functions from this? For example we are dealing with this bug and there doesn't seem to be a fix in this library https://github.com/visgl/react-map-gl/issues/604
