### ISSUE TITLE
layerOptions.id resets fillPaint in GeoJSONLayer

### ISSUE THREAD

**Issue by anecdote1** [alex3165/react-mapbox-gl#297]
I noticed that if an `id` is passed to a `GeoJSONLayer` using `layerOptions`, the previously set `fillPaint` properties are removed.
~~~~
<GeoJSONLayer
	data={this.state.geoJSON}
	fillPaint={{
		'fill-color': 'rgba(255, 255, 255, 0.15)',
		'fill-outline-color': 'rgba(200, 177, 139, 1)',
		'fill-antialias': true
	}}						
	layerOptions={{
		id: 'foo'
	}}
	>
</GeoJSONLayer>
~~~~

Is this expected behaviour?

**Comment by alex3165** [comment]
Hey @anecdote1, thanks for reporting the issue, it is not expected, I will be in holidays for a month so I won't be able to work on it soon. Any PR is welcome though.

**Comment by alex3165** [comment]
I will close this issue, I couldn't [reproduce it](https://www.webpackbin.com/bins/-KtR-kivuLSTwCwftkLu). If you still have any issue feel free to open a new issue with the issue reproduced using [webpackbin](https://www.webpackbin.com/bins/-KqtJN-qkLs4BPaVX0QS) or the [debug repository](https://github.com/alex3165/react-mapbox-gl-debug). Thanks.
