### ISSUE TITLE
Note: already working mapbox/leaflet implementation for react

### ISSUE THREAD

**Issue by JonathanBergers** [alex3165/react-mapbox-gl#3]
Hi.
I came acros an already working implementation of mapbox in react:
https://github.com/PaulLeCam/react-leaflet

This works with mapbox too, you just need to configure the tile layer for mapbox and you are done..
Maybe use this instead of doing double work ? ^^

**Comment by alex3165** [comment]
Yes I know react-leaflet but this project is based on mapbox-gl-js which
render the map in a canvas instead of using the DOM it make the rendering
more efficient because if is using webgl.

**Comment by JonathanBergers** [comment]
Ah okay, cool!
