### ISSUE TITLE
Docs: Example of using map Events inside a Component 

### ISSUE THREAD

**Issue by swissums** [alex3165/react-mapbox-gl#301]
Could you update the Docs to include an example of how we can actually use events inside our components. I am new to react so maybe this isn't 100% necessary but it would make things much more clear. 

In example pulling the longlat from a onClick.

**Comment by alex3165** [comment]
Hey @swissums, yeah I think it is not clear from the documentation. Events of the Map component have this signature: `(map: Mapbox.Map, evt: Mapbox.event) => void`.
For the events of a Feature component the signature is `(eventPlusMap: any) => void`, `eventPlusMap` is an object that get Event spread and the map instance. If you want to get the lattitude and longitude of a Feature on click, for example it would be:
```jsx
<Feature
  onClick={(eventPlusMap) => console.log(eventPlusMap.feature.geometry.coordinates)}
/>
```

Although if you want the coordinates of the mouse position on click on the map it would probably be something like:
```jsx
<ReactMapboxGl
  onClick={(map, evt) => console.log(evt.lngLat)}
/>
```
See: https://www.mapbox.com/mapbox-gl-js/example/mouse-position/

**Comment by swissums** [comment]
Ah ok now I completely understand. Thanks for that!
