### ISSUE TITLE
Markers not added to the Map in the initial load

### ISSUE THREAD

**Issue by jo-san** [alex3165/react-mapbox-gl#303]
Hi @alex3165,

Am using `Marker` components for custom markup for markers. 

```
<Map
  style="mapbox://styles/mapbox/streets-v9"
  containerStyle={{
   height: "100%",
   width: "100%"
  }}
  fitBounds={this.getBounds(markerPoints)}>
  <Marker><img .../> </Marker>
  <Marker><img .../> </Marker>
</Map>
```

`Marker` component is not added to the DOM until i resize the browser or any action like Zoom or Pan (any action inside the map). is it a known issue? if so whats the workaround for this?

**Comment by alex3165** [comment]
Hey @jo-san, could you reproduce your bug with https://github.com/alex3165/react-mapbox-gl-debug ? thanks

**Comment by alex3165** [comment]
Although this issue might be related to https://github.com/alex3165/react-mapbox-gl/issues/281

**Comment by jo-san** [comment]
It makes even worse after updated to latest `2.1.0` Now `onStyleLoad` event itself is not triggering while the pins aren't plotted. Prev version (2.0.3) i was able to get the map object in `onStyleLoad`

**Comment by alex3165** [comment]
Could you please reproduce your issue @jo-san using https://github.com/alex3165/react-mapbox-gl-debug ? thank you

**Comment by jo-san** [comment]
@alex3165 Can't reproduce the issue on debug project. Used the pointer co-ordinates from my dev application only. Is there anything i can do to figure out why `onStyleLoad` callback event didn't triggered?

**Comment by superfunkminister** [comment]
Hey @jo-san, check my solution to https://github.com/alex3165/react-mapbox-gl/issues/281 and see if that works!

**Comment by alex3165** [comment]
I will close this issue, I don't think there is any problem with `onStyleLoad` atm. Feel free to open another issue maybe a bit more specific if you still experience this.
