### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by munwr** [alex3165/react-mapbox-gl#305]
Node: 8.1.4
NPM: 5.3.0

`npm install react-mapbox-gl mapbox-gl --save`

success: react-mapbox-gl@2.1.0
Failure: mapbox-gl

---

error log for mapbox-gl:

> npm WARN deprecated point-geometry@0.0.0: This module has moved: please install @mapbox/point-geometry instead
npm WARN deprecated vector-tile@1.3.0: This module has moved: please install @mapbox/vector-tile instead
npm ERR! code ENOLOCAL
npm ERR! Could not install from "node_modules/mapbox-gl/src/style-spec" as it does not contain a package.json file.

**Comment by Wykks** [comment]
Upstream issue, use `npm install --save mapbox-gl@0.38.0` for the time being
