### ISSUE TITLE
Clusters with click-handling children

### ISSUE THREAD

**Issue by rhewitt22** [alex3165/react-mapbox-gl#308]
I would like to use the `Cluster` component while supporting click events on individual features.  Can `Feature` components only be nested in `Layer` components?  It doesn't appear that `Layer` components can be nested within a `Cluster`.

I currently have a `Cluster` of `Markers`, but the events the `Marker`s give are not the same as those provided by `Features`.  [The docs just state the following](https://github.com/alex3165/react-mapbox-gl/blob/master/docs/API.md#marker): 

- onClick: `Function` Triggered whenever user click on the marker

What is passed to the event handler? How is this different from a `Feature` onClick event?

![screen shot 2017-07-25 at 3 20 48 pm](https://user-images.githubusercontent.com/3673374/28589620-e1267130-714c-11e7-962a-8a11a31c456a.jpg)

``` javascript
<Cluster ClusterMarkerFactory={clusterMarker}>
  {
    features.map((feature, key) => (
      <Marker
        key={key}
        styles={markerStyles}
        coordinates={feature.geometry.coordinates}
        onClick={(e) => console.log(e)}
      />
        {feature.properties.type}
      </Marker>
    ))
  }
</Cluster>
```

**Comment by rhewitt22** [comment]
Use an arrow function to pass the feature to your click handling function.

``` javascript
const OfficeMarker = ({ feature, coordinates, styles }) => {

  const onMarkerClick = (feat, e) => {
    console.log(feat);
  }

 return (
   <Marker coordinates={coordinates} style={styles} onClick={(e) => onMarkerClick(feature, e)}>
     {feature.properties.name}
   </Marker>
  )
}

**Comment by Wykks** [comment]
The current API of `Marker` doesn"t contain the `feature` in his `props`. So there is no way to send the `feature` that he doesn't have without closure like you just did.
You can cluster `Layer` using the native API of `mapbox-gl`: https://www.mapbox.com/mapbox-gl-js/example/cluster/
I highly recommend you to use that if you don't need very custom HTML to render your markers. It's way more performant than HTML markers.
