### ISSUE TITLE
GeoJSONLayer doesn't update on layerOptions.filter change

### ISSUE THREAD

**Issue by tofuness** [alex3165/react-mapbox-gl#312]
Related to #169. `map.setFilter` was only added to `Layer`.

**Comment by 4xDMG** [comment]
Is it okay if I work on this issue?

**Comment by tofuness** [comment]
@4xDMG That would be awesome. I am currently using Layer + Source instead.

**Comment by Wykks** [comment]
@4xDMG  Sure any PR for this is welcome :)

**Comment by 4xDMG** [comment]
Awesome. I'll give it ago tomorrow.

**Comment by alex3165** [comment]
@4xDMG any update on this by any chance?

**Comment by SBRK** [comment]
Since I need that, I'm also woring on it

**Comment by alex3165** [comment]
Released with version `2.3.0`
