### ISSUE TITLE
Support for multiple cluster layers

### ISSUE THREAD

**Issue by fidiego** [alex3165/react-mapbox-gl#314]
I would like to request a demo in which multiple cluster layers are added to the same map. At the moment, I can only add one `<Cluster>` component to the `<Map>` component. Does this library support adding multiple `<Cluster>` components?

**Comment by alex3165** [comment]
Hey @fidiego in theory you should be able to have multiple cluster, any thought @Wykks ? I can give it a try and confirm as soon as I have some free time

**Comment by Wykks** [comment]
Well, never tried myself, but I don't see anything preventing this. Have you come across any issues while doing that ?

**Comment by alex3165** [comment]
@fidiego You can find an example of a map with 2 Cluster components at the following url https://www.webpackbin.com/bins/-KtmUplkr7W5brK4FPmt

**Comment by fidiego** [comment]
This is great, thank you @alex3165
