### ISSUE TITLE
On onClick doesn't release control until onMouseOut

### ISSUE THREAD

**Issue by anthonyshull** [alex3165/react-mapbox-gl#316]
I am using react-router-redux. When I click on a Feature and trigger a location change, the change is reflected in redux. But, nothing happens until I onMouseOut from the feature. The only thing that I can think is that the component isn't releasing control back to the application. Is there a way to force the map to release control?

**Comment by alex3165** [comment]
Hey @anthonyshull I am not sure but I don't think there is any issue with this library related to click event on the Feature component. Could you clarify and isolate the problem on a different issue if you think there is one? thanks.
