### ISSUE TITLE
onClick event for GeoJSONLayer?

### ISSUE THREAD

**Issue by jussirantala** [alex3165/react-mapbox-gl#325]
In mapbox documentation it seems there's a click event for map layers. I think it should be in the props of GeoJSONLayer component so it could be used.

**Comment by jussirantala** [comment]
Nvm. I can set id for the GeoJSONLayer and use this:
`  map.on('click', 'LayerID', function (e) {
      // do stuff
    });
`

**Comment by jussirantala** [comment]
Oh, the id is set like this:
`private id: string = this.props.id || `geojson-${generateID()}`;`

How I can get the ID which it sets for the layer?

**Comment by alex3165** [comment]
@jussirantala Thank you for the issue and sorry for the late reply. I am happy to have an `onClick` prop on the GeoJson component if anyone want to work on this 👍 . Otherwise I will try to find some times for this asap.

**Comment by alex3165** [comment]
Released with version `2.3.0`

**Comment by rofrol** [comment]
Label `In progress` can be removed
