### ISSUE TITLE
[Popup] bug with className. Custom className override defaultClassName

### ISSUE THREAD

**Issue by lkazberova** [alex3165/react-mapbox-gl#326]
Hi!

Sorry for my english. 
Use case : set className to Popup, for example "my-popup"
Expected result: defaultClassName concated with custom className, for example "my-popup mapboxgl-popup mapboxgl-popup-anchor-bottom"
Actual result:  "my-popup" without defaultClassName

Why: https://github.com/alex3165/react-mapbox-gl/blob/master/src/popup.tsx#L34
computed className overrided with props.className
`<ProjectedLayer className={className} {...props as any}>`
Should be
`<ProjectedLayer {...props as any} className={className} >`

**Comment by alex3165** [comment]
Hey @lkazberova it was a mistake it should be fixed with version `2.2.1` of the library. Feel free to close this issue if it is good now.

**Comment by lkazberova** [comment]
Ok will do with test for popup
