### ISSUE TITLE
Pixel offset for map center

### ISSUE THREAD

**Issue by clairethompson** [alex3165/react-mapbox-gl#328]
We're in the middle of switching from using mapbox-gl-js to react-mapbox-gl and have noticed an issue.

Previously when we wanted to recenter the map, we were using flyTo and passing a pixel offset based on the offset we wanted with respect to addition UI panels on the screen.  [flyTo](https://www.mapbox.com/mapbox-gl-js/api/#map#flyto) takes [AnimationOptions](https://www.mapbox.com/mapbox-gl-js/api/#animationoptions) which allows us to pass in a pixel offset.  We don't see a way to do this with react-mapbox-gl. 

Is there something we're missing or is this a feature that would need to be added?

Thanks!

**Comment by clairethompson** [comment]
For now, we're using the following monkey patch on the `onStyleLoad` property: 
```JS
(map) => {
  const originalFlyTo = map.flyTo;
  map.flyTo = (options, eventData) => {
    const patchedOptions = {...options, offset: [275, 0]};
    originalFlyTo.bind(map, patchedOptions, eventData)();
  };
};
```
It'd be nicer if there was a better way to do this.

**Comment by alex3165** [comment]
Hey @clairethompson thank you for signalling the issue, it is indeed a missing feature. I will work on it asap

**Comment by alex3165** [comment]
I opened a PR to add animationOptions and flyToOptions https://github.com/alex3165/react-mapbox-gl/pull/329

**Comment by alex3165** [comment]
Released with tag `2.2.2` feel free to try it out 👍

**Comment by clairethompson** [comment]
Looks great @alex3165 ! 

One of the options that we were using was the `zoom` level as a [CameraOption](https://www.mapbox.com/mapbox-gl-js/api/#cameraoptions) on flyTo. In the [flyTo doc](https://www.mapbox.com/mapbox-gl-js/api/#map#flyto) they pass `zoom` in as an option as an example. Could that get added as well?

Thanks!

**Comment by clairethompson** [comment]
We could also have this passed in to `flyToOptions`. I could see an implementation where `flyToOptions` takes both animation and camera options as well: 
```js
<ReactMapboxGl {...{
  flyToOptions: {zoom: 2, offset: [100, 100]}
}}/>
```

where `zoom` is a CameraOption and `offset` is an AnimationOption
