### ISSUE TITLE
Question:  Is there a way to render text on the map?

### ISSUE THREAD

**Issue by timfpark** [alex3165/react-mapbox-gl#33]
I need to draw some mileage markers on the map for a set of lines that I am drawing.  Is there any way to do that using a text overlay on map?

Failing that, it looks like I need to use mapbox studio in order to build icons for all of the mileage markers that I will need (roughly 100-150) - is that right?

PS.  Thanks so much for this library - it works great and has been a lifesaver!

**Comment by alex3165** [comment]
Hi @timfpark have you tried something like this ?
```
<Layer
  type="symbol"
  layout={{
    "icon-image": "harbor-15",
    "icon-allow-overlap": true,
    "text-field": "Put the text in here",
    "text-font": ["Open Sans Bold", "Arial Unicode MS Bold"],
    "text-size": 11,
    "text-transform": "uppercase",
    "text-letter-spacing": 0.05,
    "text-offset": [0, 1.5]
  }}>
  <Feature
    coordinates={markerCoord}
    onHover={this._onHover}
    onEndHover={this._onEndHover}
    onClick={this._onClickMarker}/>
</Layer>
```

In case you don't want the image, you can maybe define a transparent symbol on Mapbox studio.
You might have a problem if you display 100 - 150 different layers, you will probably have some perf issues though ...
Let me know if this works anyway.

Thanks for your support 👍

**Comment by timfpark** [comment]
That works great - thank you!
