### ISSUE TITLE
Add custom Image for 'icon-image' for my layer

### ISSUE THREAD

**Issue by theaidem** [alex3165/react-mapbox-gl#342]
like this https://www.mapbox.com/mapbox-gl-js/example/add-image/

how can I call load and adding methods on the react wrapper for mapbox?

```
		const MapBox = ReactMapboxGl({
			accessToken: token
		})
		
		MapBox.loadImage(url) // is not a function
```

**Comment by rlueder** [comment]
[You have to use the onStyleLoad property:](https://github.com/alex3165/react-mapbox-gl/blob/master/docs/API.md#reactmapboxgl)

> To use the original Mapbox API use onStyleLoad property, the callback function will receive the map object as a first arguments, then you can add your own logic alongside react-mapbox-gl. mapbox gl API.

```
<Mapbox
  onStyleLoad={(map) => {
    map.loadImage(url)
  }}
>
  ...
</Mapbox>
```

**Comment by theaidem** [comment]
@rlueder Thank you!

**Comment by alex3165** [comment]
Hey @theaidem , indeed using onStyleLoad is a way to do it but actually I didn't know about those functions `loadImage` and `addImage`, I think that it is a feature that should be added to the layer component.

**Comment by alex3165** [comment]
I have opened a new issue for that: https://github.com/alex3165/react-mapbox-gl/issues/344
