### ISSUE TITLE
Toggling Features vs Toggling Styles

### ISSUE THREAD

**Issue by taystu** [alex3165/react-mapbox-gl#346]
Hopefully someone cant point me in the right direction I've read the docs and looked it up in issues but it still isn't clear to me. So I understand via the docs the ability toggle styles on and off. However I'm still unclear as to how to approach this for features within a style. Such as [here](https://uber.github.io/react-map-gl/#/Examples/dynamic-styling) with the react-map-gl library 

For instance toggling roads, parks, etc. Furthermore the ability to filter these features as shown [here](https://www.mapbox.com/mapbox-gl-js/example/filter-features-within-map-view/)

Any and all suggestions welcome, sorry if the question is vague. Thanks

**Comment by alex3165** [comment]
Hey @taystu, I don't know your exact use case but looking at the 2 examples you added in the issue, here the approaches I would take:

- For the [mapbox example](https://www.mapbox.com/mapbox-gl-js/example/filter-features-within-map-view/) it is actually quite simple to reproduce the same behaviour, for that I would use the `Layer` and `Feature` components and play with mounting / unmounting the `Feature`'s depending on the filter you have.

- For the [react-map-gl example](https://uber.github.io/react-map-gl/#/Examples/dynamic-styling) it is a bit trickier but you can achieve the same by playing with the style prop of the Map component. Basically you would build the style depending on your filter and just trigger a re-render of the `Map` component with your new built style. Checking at the code of react-map-gl example, that's actually what the Uber team is doing. Unfortunately it is not very "React friendly" but I don't see any other way to achieve this in a nice way with React.

If any of this is a bit unclear I can help you to build a working example using the [webpackbin boilerplate](https://www.webpackbin.com/bins/-KqtJN-qkLs4BPaVX0QS)
