### ISSUE TITLE
Layer ordering

### ISSUE THREAD

**Issue by daviestar** [alex3165/react-mapbox-gl#35]
Hey again,

Do you have a suggested approach to ensure layers are always ordered correctly on z axis?

Here is a paste of my messy map JSX:

```javascript
const journeyTotal = journeys.length;
return (
  <MapGL style={MAP_STYLE} accessToken={API_TOKEN} {...this.state.viewport}>{
    journeys.map((type, idx) => (
      <Layer key={idx} type="line" {...type.style}>{
        type.segments.map((segment, idx) => (
          <Feature key={'segment-'+idx} coordinates={segment.coordinates}  />
        ))
      }</Layer>
    ))
    }<Layer key={journeyTotal} type="circle" paint={LOCATION_SHAD_STYLE}>{
      this.props.locations.map((location, idx) => (
        <Feature key={'location-shad-'+idx} coordinates={location.lngLat} />
      ))
    }</Layer>
    <Layer key={journeyTotal+1} type="circle" paint={LOCATION_STYLE}>{
      this.props.locations.map((location, idx) => (
        <Feature key={'location-'+idx} coordinates={location.lngLat} />
      ))
    }</Layer>
    <Popup {...this.props} />
  </MapGL>
);
```
Have a look at the `key` attribute on my layers.  This approach is the only way I found to ensure the layers are ordered as they appear in the JSX.  Without the sequential indexes (I tried arbitrary high numbers like 9999 without success), the layer order is unpredictable.  Once I filter the data using other functionality, the indexes can become out-of-sequence and breaks ordering.

The order of layers in [this array](https://www.mapbox.com/mapbox-gl-style-spec/#root-layers) is how mapbox-gl will render the layers.  The package doesn't appear to take advantage of this, using `componentWillMount` and [`addLayer`](https://github.com/alex3165/react-mapbox-gl/blob/master/src/layer.js#L155), which appears to be asynchronous as my most expensive layers are rendered last / on top (the journey polylines).

Any ideas?

**Comment by philpl** [comment]
This is how react fundamentally works. The key ensures an order and identification for each child element of a React component. We could add sth else that overrides this behavior, but that would just be a redundancy ;)

**Comment by philpl** [comment]
Follow up actually, we can make use of the key actively and pass the elements to mapbox gl in a stable order, but I'm not sure if that adds a lot of value. Can you elaborate on the purpose here a bit?

**Comment by daviestar** [comment]
Sure, 

I have routes which are styled based on transport type - different colours, and flights have an arc. Since styling happens at the Layer level, I've made an array of layer types under `journeys` with their own 'paint' and 'layout' objects along with a LineString.  

Then I have locations which are waypoints along these polylines, and need to sit on top or else they are obscured.

If you can suggest some ideas as to how to fix this I'd be happy to get it done and submit a PR.

**Comment by daviestar** [comment]
This is my first React project, so I'm no expert, but something that's related is it's not obvious how to go about splitting the map layers into different components.  For example it felt natural in this scenario to create a new component for Map, `Journey` Layers, and `Location` Layers.  Using JSX and regular HTML, I could render several items wrapped in a `<div>`, but I couldn't think of an alternative using the `<Map><Layer ... /></Map>` syntax for Journeys.

I'm wondering if what is really needed is a new Source component, as child of Map, which can have multiple Layers as children, and the ability to keep different Sources ordered, and keep it's source data separated (as in `mapbox.getSource()`).

Then the map could be simple and optimised for simple maps, or have a bit more control for more complex maps.

Thoughts?

**Comment by alex3165** [comment]
Hi @daviestar,

I have added support for the before property when adding a layer to the map. https://github.com/alex3165/react-mapbox-gl/commit/f4917fa7cd06374f6f7bc862f3455d8f3487095e

This should solve your problem of ordering the layers, you have to specify the id of another layer (it imply to generate the id yourself and pass through the props) and the layer will be displayed just  before the id of the layer you specified.

**Comment by daviestar** [comment]
Great, that seems like a really nice and simple solution - I have been thinking how I would fix it and had only come up with much more complicated approaches!
