### ISSUE TITLE
Update Features on bounds changed

### ISSUE THREAD

**Issue by amaurymartiny** [alex3165/react-mapbox-gl#351]
I wish to update the features of a layer each time the map changes bounds.

I have looked at @alex3165's [talk](https://pusher.com/sessions/meetup/the-js-roundabout/webgl-map-with-mapbox-and-react), and it' similar to the effect at 14:56. However, one crucial difference: if I understood correctly in the video all the features are loaded at init, and the left pane is only filtering based on bounds.

What I wish to achieve is: since I have a lot of features, I don't want to load them all, but only load the ones that are visible, i.e. in the bounds of the map. And every time I drag/zoom/rotate the map, the list of features updates.

Here's how I would do it:

```javascript
// In the render method
<MyMap
  listings={this.props.listings}
  boundsChanged={map => {
    console.log(map.getBounds()); // This works
    this.getListings(map.getBounds());
  }}
/>
```

Where `this.getListings` is an API call which retrieves listings in the bounds and updates `this.props.listings`.

And here is my implementation of `<MyMap />`:

```javascript
// In the render method
      <Map
        style="mapbox://styles/mapbox/streets-v9" // eslint-disable-line
        containerStyle={{ width: '100vw', height: '100vh' }}
        onDrag={boundsChanged}
        onRotate={boundsChanged}
      >
        <Layer
          type="symbol"
          id="listings"
          layout={{ 'icon-image': 'marker-15' }}
        >
          {listings.map((listing) => (
            <Feature coordinates={[listing.longitude, listing.latitude]} key={listing._id} />
          ))}
        </Layer>
      </Map>
```

However, what happens is that when I drag, the map re-renders, and go back to the initial bounds (around London).

**Comment by alex3165** [comment]
Did you make sure not to break the reference equality of the array you pass as a center to your map?

Also, you can use onMove and onZoom events to define a change of bounds.

You can see the implementation of what I have done for https://monumap.org here: https://github.com/giistr/unesco-map

**Comment by khollund** [comment]
Any time the map renders and you pass center position it will shift to that center. I had some hairy shouldcomponentupdates first, but I ended up passing user initated moves to state, because I need to offset map center anyway. And that was supported now through the flyto offset.

**Comment by alex3165** [comment]
The center will change only if you break the reference of the array of your center prop. The solution if you want to leave mapbox handling the center is to keep your center in the state and do not break the reference between re-render. If you want to take over the control of the center then you just break the reference by creating a new array, even if the value are the same it will update the center to the center you pass as a prop (zoom work the same way).

It is not natural at first and not very well documented (I will work on it) but I think it is better than keeping the viewport in sync with mapbox's viewport which would trigger lot of re-rendering of the map component like react-map-gl is doing.

**Comment by Wykks** [comment]
I think we can improve the way the map component detect changes (ie more than just reference check).
I'll try to look into that.

Also, @amaurymartiny you should consider using a vector tile source containing your feature if you can change your backend. It will fit perfectly for your use case.

**Comment by amaurymartiny** [comment]
@Wykks Yes my bad, that did the trick. I defined Map inside a function component.

And thank you all for all the comments!
