### ISSUE TITLE
Feature draggable not working on mobile

### ISSUE THREAD

**Issue by zeulb** [alex3165/react-mapbox-gl#353]
Tried switch-style example with developer tools device on Chrome and also both Chrome and Safari on iPhone 6 but dragging the marker doesn't seem to work.

**Comment by alex3165** [comment]
Hi @zeulb, indeed dragging a feature wouldn't work on a mobile as we listen for `mouseEnter`, `mouseDown`, `mouseLeave` events to drag. It would need some work to make it working for mobile.

**Comment by zeulb** [comment]
oh yup, will this be implemented real soon? if not, is there any quick workaround?

**Comment by alex3165** [comment]
I will try to get this done and released by the end of next week. There is a quick workaround, you could implement it on your side by getting an instance of the map via `onStyleLoad ` prop of the map and use `map.on('touchstart')`, `map.on('touchmove')`, `map.on('touchend')` with the layer id you want. See: https://www.mapbox.com/mapbox-gl-js/example/drag-a-point/.

Basically you just need to replace mouse events to touch events.

**Comment by alex3165** [comment]
@zeulb I released a version `2.6.0` with features draggable on mobile.
