### ISSUE TITLE
fitBounds does not move to new bounds on change

### ISSUE THREAD

**Issue by dedan** [alex3165/react-mapbox-gl#359]
I have a map that I first center on a certain location. After my data is loaded I want to fit to the bounds of the data, and that works perfectly fine. But when my data changes I want to fit to new bounds which does not work. 

On setting a new value for `fitBounds` I would expect the map to zoom to the new bounds, however what it currently does is that it zooms out and centers on the originally set center. Am I using it wrong or is that a bug? 

Here is a small component to reproduce the behavior:

```js
import React, { Component } from 'react';
import ReactMapboxGl from 'react-mapbox-gl';

// Mapbox Access Token.
const accessToken = 'pk.eyJ1IjoiZGVkYW4iLCJhIjoiY2o3c29wcThlM3ZlZjMzdXdzczQ3bzIwMSJ9.pvxNu-R28kuQ6CXsHJST_w'
const Map = ReactMapboxGl({ accessToken });


const FIRST_BOUNDS = [
  [88.537838, 26.564062],
  [92.325374, 28.488102]
];
const SECOND_BOUNDS = [
  [92.537838, 30.564062],
  [99.325374, 35.488102]
];
const CENTER = [80.2361995, 27.4128857];


class App extends Component {

  constructor(props) {
    super(props)
    this.state = {
      boundingBoxCoordinates: null,
    }
    setTimeout(() => {
      this.setState({boundingBoxCoordinates: FIRST_BOUNDS})
    }, 5000)
    setTimeout(() => {
      this.setState({boundingBoxCoordinates: SECOND_BOUNDS})
    }, 10000)
  }

  render() {
    const {boundingBoxCoordinates} = this.state
    return (
      <Map
        style="mapbox://styles/mapbox/streets-v8"
        zoom={[3]}
        center={CENTER}
        fitBounds={boundingBoxCoordinates}
        containerStyle={{width: 500, height: 500}}>
      </Map>
    );
  }
}
```

**Comment by alex3165** [comment]
@dedan You should not break reference equality for zoom prop, you should manage center and zoom the same way by extracting the instantiation out of the render function or putting them in the state.

You will find your example working [here](https://www.webpackbin.com/bins/-KuZNpaMUFALcK8sH1c2)

**Comment by dedan** [comment]
Hello Alex,

thanks a lot for the explanation and your example, now it all works.
