### ISSUE TITLE
Is possible to update each feature style on click event ?

### ISSUE THREAD

**Issue by intelcoder** [alex3165/react-mapbox-gl#368]
Currently passing data type FeatureCollection of polygons and I would like to update each polygon's fill color on click event. Is this possible or I have to create GeoJSONLayer for each feature to achieve this ? 

```
<GeoJSONLayer
   data={neighbourhoods}
   fillLayout={{ visibility: "visible" }}
   fillPaint={{
     "fill-color": "red",
     'fill-opacity': this.state.filled ? 0.2 : 1,
   }}
   fillOnMouseDown={(e)=>{
          console.log(e)

   }}
/>
```

**Comment by alex3165** [comment]
I am afraid you gonna have to create a `GeoJSONLayer` for each polygon in this case. Not sure if we could expose a better `GeoJSONLayer` API for this use case, I am happy to debate any suggestion.

**Comment by intelcoder** [comment]
Thank you @alex3165 
Unfortunately, I do not have any suggestion at this moment.

**Comment by Wykks** [comment]
Don't create one layer for each polygon. You can do that with two layer : https://www.mapbox.com/mapbox-gl-js/example/queryrenderedfeatures-around-point/

**Comment by alex3165** [comment]
My bad I thought each of your polygons needed a different color as 1 color = 1 layer
