### ISSUE TITLE
How do i do something like the following

### ISSUE THREAD

**Issue by suyesh** [alex3165/react-mapbox-gl#391]
`map.addControl(draw);`

i have a function that i saw in the mapbox gl documentation. Is it even possible?

**Comment by rlueder** [comment]
If you're interested specifically on the Draw control, take a look at this:
https://github.com/amaurymartiny/react-mapbox-gl-draw

**Comment by hobofan** [comment]
From the [docs](https://github.com/alex3165/react-mapbox-gl/blob/6ccfd044045ad15617b33cf83f80cdc17abf6f7b/docs/API.md):

> To use the original Mapbox API use onStyleLoad property, the callback function will receive the map object as a first arguments, then you can add your own logic alongside react-mapbox-gl.

So you can extract a reference to the internal `map` object, and then use the usual functions from the mapbox-gl documentation.

**Comment by alex3165** [comment]
@hobofan pointed is right you can use the map instance from `onStyleLoad`, alternatively, any children component of the map will receive an instance of the map in the context 👍
