### ISSUE TITLE
Issues with sizing of the canvas in a flexbox

### ISSUE THREAD

**Issue by basharov** [alex3165/react-mapbox-gl#395]
Canvas sets some default size on load and the map looks like this:

![image](https://user-images.githubusercontent.com/625090/30959137-f211011c-a447-11e7-8783-b4f6269ea8ac.png)

When I resize the window, the canvas sets its size to the whole pink area, as should do from the start.
![image](https://user-images.githubusercontent.com/625090/30959185-0bb53322-a448-11e7-9a4d-92c243eb8076.png)

How do I fix it?

**Comment by alex3165** [comment]
Do you pass a `containerStyle` with a `height` and a `width` to the map? Could you reproduce the issue with https://www.webpackbin.com/bins/-KqtJN-qkLs4BPaVX0QS

**Comment by alex3165** [comment]
I will close this issue for inactivity, please open a new issue with the bug reproduced with webpackbin if it is still happening.

**Comment by dongapplyboard** [comment]
Getting the same issue, I have         

```
containerStyle={{height: "100%", width: "100%"}}
```

**Comment by devnoot** [comment]
I have the same issue. I have a drawer on the left side of the map that will expand and close with a button.

When the drawer expands / contracts, the map does not resize with the container.

I have this as suggested in #372 but it does not work unless I actually resize the window.
```
// Create the base ReactMapbox instance
const MapboxMap = ReactMapboxGl({
    accessToken: Config.mapbox.accessToken,
    minZoom: 8,
    maxZoom: 15,
    onStyleLoad: map => map.resize()
})
```

**Comment by austencm** [comment]
Using `onStyleLoad` + `resize()` on the map component worked for me:
```
<Map
  ...
  onStyleLoad={(map) => map.resize()}
>
```

**Comment by nandorojo** [comment]
I did something like this to avoid the flicker:

```jsx
const [hasMapMounted, setMapMounted] = useState(false)

<MapBox
  containerStyle={{
    opacity: hasMapMounted ? 1 : 0,
    height: '100%',
    width: '100%'
  }}
  onStyleLoad={(map) => {
    map?.resize?.()
    setMapMounted(true)
  }}
/>
```

**Comment by trungnguyencmu** [comment]
I got problem with width of map when drawer collapse
I have same question with @devnoot 
I found #13
