### ISSUE TITLE
Support API_URL for mapbox-gl

### ISSUE THREAD

**Issue by wlindner** [alex3165/react-mapbox-gl#396]
I need the ability to set a custom Mapbox API URL ([this is supported by mapbox-gl]( https://github.com/mapbox/mapbox-gl-js/blob/ca243c7bf2ff664e4692ab0557a6c27e5aa917b7/test/unit/util/mapbox.test.js#L33-L42)), but I don't see any way to do that with this React wrapper. Is it possible to set the API_URL on the mapbox-gl instance?

**Comment by alex3165** [comment]
Sorry for the late reply, I was busy for the last 2 days. How is Mapbox exposing it? I can't find it in the documentation and this is a link to the tests which uses the source files, if you have a code example for the implementation with mapbox-gl that would be helpful.

**Comment by wlindner** [comment]
I can't really find any documentation about it, but it's necessary when you host your own Atlas Server so you can change the API URL from api.mapbox.com to wherever you host your server. It is mentioned in [this issue](https://github.com/mapbox/mapbox-gl-js/pull/4995). It's also mentioned in the [CHANGELOG.md](https://github.com/mapbox/mapbox-gl-js/blob/244d1e77e20b815a4834c54858053ea473e5c62c/CHANGELOG.md#breaking-changes-7). I made this [codepen example](https://codepen.io/wlindner/pen/qPXWeK) to show that it works. Just open that codepen example with DevTools open and you'll see that it's trying to connect to 'https://example.com' because I configured it with `https://example.com`. You can see a screenshot of what I mean [here](https://snag.gy/dt72C1.jpg).

**Comment by alex3165** [comment]
Could you quickly check https://github.com/alex3165/react-mapbox-gl/pull/399 and tell me if you think it is fine?

**Comment by alex3165** [comment]
I merged the PR and published the changes with version `2.5.3` 👍

**Comment by wlindner** [comment]
That's great, I'll try this out on Monday. Thanks for your quick work!

**Comment by SkylinR** [comment]
I also wanted to use my won tiles server and 
`MapboxGL.config.API_URL = 'myOwnTailsURL';`
is working perfectly :)
