### ISSUE TITLE
Option to turn off CSS injection

### ISSUE THREAD

**Issue by hobofan** [alex3165/react-mapbox-gl#397]
At project we are currently working on, we are styling the Mapbox map via CSS, on multiple pages. On the pages without the React version, everything is fine, but on those with, this library injects the CSS and destroys the styling of the map to some degree.

I feel like there should be at least an option to turn off the CSS injection since that is somewhat intrusive.

**Comment by alex3165** [comment]
Yes I agree, it should probably be a parameter of the Map factory function I guess. PR welcome, I think it is an easy fix, it is just about moving https://github.com/alex3165/react-mapbox-gl/blob/master/src/index.ts#L15 to the map factory function, and inject the css or not depending on the given parameter.

What about `injectCss` as a parameter name?

**Comment by hobofan** [comment]
Yeah, I also think that that would be the way to go,  but I think it still would be a breaking change as soon as the injectCss call is removed from the index.tsx.

I think the only way to make it a truly backward compatible change would be to allow the user to set a global variable before importing the library that deactivates the `injectCss` call, which can then be fully removed at a future point in time.

I'll see what I can do and submit a PR in the coming days. :)
