### ISSUE TITLE
Convert the project to typescript

### ISSUE THREAD

**Issue by alex3165** [alex3165/react-mapbox-gl#40]
Create and publish a type definition file for react-mapbox-gl.

https://github.com/DefinitelyTyped/DefinitelyTyped

**Comment by Wykks** [comment]
Why not convert the project to typescript ?

**Comment by alex3165** [comment]
Yes I thought about it as well, I would like to have the opinion of the maintainers on this one.

**Comment by alex3165** [comment]
WIP https://github.com/alex3165/react-mapbox-gl/pull/114
