### ISSUE TITLE
Add markers from an array of objects

### ISSUE THREAD

**Issue by martin056** [alex3165/react-mapbox-gl#411]
I have an array of objects and each object has it's coordinates and other data. How can I add a simple marker by that coordinates? I just iterate over the array and create markers from it and it doesn't work. If I try with just the first element of the array it works. Why? Do I need a "Cluster"?

**Comment by alex3165** [comment]
Use the component `Layer` and `Feature`, check this example: https://github.com/alex3165/react-mapbox-gl/blob/master/example/src/demos/londonCycle.tsx

**Comment by martin056** [comment]
Thank you for the fast response! @alex3165
