### ISSUE TITLE
Feature: onDragStart

### ISSUE THREAD

**Issue by MadalenaGoncalves** [alex3165/react-mapbox-gl#412]
Can you add this method into Features? I want to add an image bellow a marker when this is being dragged and hide it onDragEnd. I tried with the onClick method but it isn't very suitable in this case. Or do you have any other suggestion to solve this issue?

**Comment by alex3165** [comment]
Hi @MadalenaGoncalves, yes that's something we should add, it would require some times though. Any help welcome!

**Comment by MadalenaGoncalves** [comment]
Hey @alex3165! Thanks for answering. It turned out I could go around this issue for a while but I'm sure it will be useful in the future. I will be glad to take a look at it in my free time ;)

**Comment by cyrilchapon** [comment]
@MadalenaGoncalves 

> It turned out I could go around this issue for a while

Did you just give up on your feature or did you manage to find a workaround ? :)

**Comment by cyrilchapon** [comment]
@alex3165 can you explain on `onDragEnd` strategy so I may have a chance to contribute on `onDragStart` ?

**Comment by MadalenaGoncalves** [comment]
Hey @cyrilchapon, we decided to go with the workaround, which doesn't require this method at all. But as I said, it seems quite useful and it's good to have someone working on it

**Comment by cyrilchapon** [comment]
Pushed something in #517 

Need help there :)

**Comment by cyrilchapon** [comment]
Expanding on this, maybe MouseEnter, MouseOut, and Drag (DragMove or something) could be useful ?

I just realized that, for example, I need a specific cursor over feature, and DragStart / DragEnd won't be enough to highlight hovered features.

**Comment by alex3165** [comment]
`onDragStart` and `onDrag` events have been added to react-mapbox-gl version `3.8.0`, thanks very much @cyrilchapon for your help 👍
