### ISSUE TITLE
Markers disappeared after reload the route. 

### ISSUE THREAD

**Issue by ptchiangchloe** [alex3165/react-mapbox-gl#419]
Hi guys, 
I have trouble with the markers after reloading the page. My state shows all the values and there are no marker divs after the page is reloaded. 
And also do you have the source code for the monumap.org? 

Thanks,

Han

**Comment by alex3165** [comment]
Hi @ptchiangchloe, hum difficult to say, do you use the `Marker` component?

The code for monumap is accessible here: https://github.com/giistr/unesco-map

**Comment by ptchiangchloe** [comment]
Hi Alex,

Thanks for the response, I found out the problem that I use state instead of the props to store the markers so after reload the component state did not setState again (which I found odd) so I use the props directly which solved the problem. 

Thanks,

Han
