### ISSUE TITLE
Popup anchors not being added when anchor is unset

### ISSUE THREAD

**Issue by Valid** [alex3165/react-mapbox-gl#421]
[Demo here](https://www.webpackbin.com/bins/-KwcaCrN_eZWX_STxo8H)

According to Docs:
> When not set, the anchor is automatically calculated to keep the content of the popup visible.

This does not appear to be the case -- the anchor does not show up at all when the `anchor` prop is not passed, and it also does not auto-adjust based on viewport.

passing `anchor={null}` **does** auto-adjust, but doesn't add an anchor.

Are the docs incorrect, or am I misunderstanding how it should work?

**Comment by alex3165** [comment]
Hey @Valid Sorry for the late reply, this is a bug I think, I will add this to the v3 milestone

**Comment by Valid** [comment]
Thanks @alex3165 - do you have an ETA for v3 milestone?

**Comment by alex3165** [comment]
If by ETA you mean all the changes included to this milestone, you can see every open issues marked as v3. I would really like to get it done by end of November but I found difficult to work on OSS lately. I will do my best although any help is appreciated 👍 there are some tasks marked as `ready to work` feel free to branch off `v3` and work on an issue marked as `ready to work` and `help wanted`.

**Comment by alex3165** [comment]
https://github.com/alex3165/react-mapbox-gl/pull/450 should fix it

**Comment by alex3165** [comment]
Released from tag `3.0.0`

**Comment by troqru** [comment]
Im ending up with class of "mapboxgl-popup-anchor-null" set to popup if null is passed as an anchor, or "mapboxgl-popup-anchor-undefined", if anchor is not set at all. Is this correct? It results in element "mapboxgl-popup-tip" not being visible at all.

**Comment by alex3165** [comment]
@troqru Sorry this is a regression, could you open a new issue for that?
