### ISSUE TITLE
Is there a way to Cluster markers only if they have same Coordinates and other same properties?

### ISSUE THREAD

**Issue by suyesh** [alex3165/react-mapbox-gl#422]
Like in this case, I have 3 markers in same coordinate so i am not being able to click. I couldn't  find any doc related to click event in situation like this. what i am trying to achieve is, when there is markers in same coordinates, i want to click on the cluster display marker or anything, maybe a spider like effect 

<img width="843" alt="screen shot 2017-10-17 at 12 50 41 pm" src="https://user-images.githubusercontent.com/3803603/31677811-f81ecff2-b339-11e7-9722-55e844ffd8b9.png">

**Comment by Wykks** [comment]
You can use `onClick` on clustered `Marker`, you can see how to do that is the demo app.
For the spider effect, I think it could probably be implemented later (but only after v3 is out)

**Comment by suyesh** [comment]
Thank you. Thats exactly what i did and got it worked out.

**Comment by SabirAmeen** [comment]
Is there any update on implementating spider effect?

**Comment by Wykks** [comment]
Not yet, I may take a look this week

**Comment by yassinejebli** [comment]
any news regarding spider effect?
