### ISSUE TITLE
UMD support (unpkg.io)

### ISSUE THREAD

**Issue by krabbypattified** [alex3165/react-mapbox-gl#423]
I'd like to make a CodePen using react-mapbox-gl, but I can't.
Can you bundle your code (i.e. with Rollup) so I can include it as a <script>?

**Comment by alex3165** [comment]
Hey @krabbypattified , thank you for the suggestion, react-mapbox-gl used to be UMD compliant but I actually removed Webpack as it was lot of overhead to me and I don't think many peoples are using it as a global dependency today. I am open to the discussion though if there is a real need I can work on it.

Alternatively you can use [webpackbin](https://www.webpackbin.com/bins/-KqtJN-qkLs4BPaVX0QS)
