### ISSUE TITLE
Question about definition

### ISSUE THREAD

**Issue by guzhongren** [alex3165/react-mapbox-gl#424]
![image](https://user-images.githubusercontent.com/8743692/31758890-dca5ab20-b4e1-11e7-9074-8399abc87078.png)
like this; i wrote codes in react component using typings; No matter how to write， there is no definition of ReactMapboxGL; 

Please give me an example obout typescript-mapbox-gl, thank you .

**Comment by alex3165** [comment]
You don't need to specify the type of your Mapbox variable, it will be inferred by the compiler.

**Comment by guzhongren** [comment]
the question has resolved with this [doc ](https://github.com/alex3165/react-mapbox-gl/blob/archive/1.12/docs/API.md) 
![image](https://user-images.githubusercontent.com/8743692/31778045-34557414-b522-11e7-9921-db4fbf5bf5ce.png)

, thank you
