### ISSUE TITLE
Hiding .mapboxgl-missing-css breaks marker position calculation

### ISSUE THREAD

**Issue by radeno** [alex3165/react-mapbox-gl#425]
Hello,

Mapbox 0.41 adding new CSS checking by adding a DIV element with class `.mapboxgl-missing-css` above div element with `.mapboxgl-canvas-container` class.
Everything should be OK with hiding this block adding `display: none` to this class as original Mapbox CSS do also.

Issue is that after hiding this block, every maker on map is pushing lower on every zoom level about that block height.
Fox example if block `.mapboxgl-missing-css` (depend on global CSS) is 20px height every marker on map is positioned with this extra dimension lower.

Not hiding works OK.
![screen shot 2017-10-20 at 09 10 09](https://user-images.githubusercontent.com/58521/31809123-85d56dc2-b576-11e7-8b8e-54ab5291d453.png)

![screen shot 2017-10-20 at 09 12 00](https://user-images.githubusercontent.com/58521/31809186-c640d310-b576-11e7-8fe6-3934a5045a73.png)

**Comment by Brentox** [comment]
To resolve the missing css error, I imported the css from the mapbox-gl node_module

`import 'mapbox-gl/dist/mapbox-gl.css';`

**Comment by radeno** [comment]
No, you dont understand. As you can see i have included default css, because logo Mapbox in bottom left corner.

Problem is that hiding that line about missing CSS moving Marker about 20px down. First image is with correct position, second image is with bad position. On every zoom level is marker moved with 20px down. When i zoom out more and more i get pin in Hungary, but correct position is in Slovakia :)

**Comment by JLeggatt** [comment]
Do you not just need to pass an `anchor="bottom-left"` to the Marker component? This will anchor the marker to the bottom left of the image you've got?

**Comment by radeno** [comment]
Looks like version 3.0 fixing this.
Its great :)
