### ISSUE TITLE
Automatically prevent control overlap

### ISSUE THREAD

**Issue by bcherny** [alex3165/react-mapbox-gl#430]
This is our use case (I imagine it's pretty common):

```js
<Map>
  <ZoomControl position="bottomLeft" />
  <ScaleControl measurement="mi" position="bottomLeft" style={{ left: 48 }} />
</Map>
```

Both `ZoomControl` and `ScaleControl` are position on the bottom left, and without the manual `style` adjustment they overlap by default. It may be a good idea to automatically add offsets when two controls overlap.

For reference, here it is with the manual style adjustment:

<img width="323" alt="screen shot 2017-10-24 at 4 11 56 pm" src="https://user-images.githubusercontent.com/1761758/31972549-14b0162a-b8d6-11e7-819e-4182da9315ac.png">

And without:

<img width="295" alt="screen shot 2017-10-24 at 4 11 21 pm" src="https://user-images.githubusercontent.com/1761758/31972525-ff4c8e1c-b8d5-11e7-8780-4a6c4862b89d.png">

**Comment by alex3165** [comment]
Hey @bcherny Thanks for reporting the issue, it make sense and it should be an easy fix. I will have a look when I have some time otherwise any PR welcome.

**Comment by alex3165** [comment]
After a closer look, I am not sure it make sense to include this feature, each components are independents and shouldn't be aware of other components, you can fix it manually by adding a style to the scale component, for example:

```jsx
<ScaleControl style={{ left: 30 }}>
```

See https://github.com/alex3165/react-mapbox-gl/blob/master/example/src/demos/allShapes.tsx#L114
