### ISSUE TITLE
[Question]Need help for drawing route 

### ISSUE THREAD

**Issue by StevanCakic** [alex3165/react-mapbox-gl#432]
Hi, 

I have a question. I need help for this problem:

![image](https://user-images.githubusercontent.com/13205146/32162536-a8ae919e-bd59-11e7-8a35-8d5b2321a92a.png)

but I want this:

![image](https://user-images.githubusercontent.com/13205146/32162281-b931328e-bd58-11e7-91b2-fe9ea955b939.png)

So I want to change direction for the route if curve goes to another "map" (same map but boundaries are exceeded). Any suggestions?

Note: Red line is imaginary line which represents map boundaries(max/man lat and lng)

**Comment by alex3165** [comment]
Hey @StevanCakic I think this is more a question for the mapbox-gl-js team I think and I have seen you already posted an issue on their repository [here](https://github.com/mapbox/mapbox-gl-js/issues/5551). Let's keep it open as a follow up.

**Comment by StevanCakic** [comment]
This solves my problem: https://github.com/Turfjs/turf/issues/1063

**Comment by alex3165** [comment]
Thanks, I will close this then
