### ISSUE TITLE
Upgrade to Mapbox-gl 0.41

### ISSUE THREAD

**Issue by alex3165** [alex3165/react-mapbox-gl#433]

**Comment by UJKhokhar** [comment]
Would this include heatmaps?

**Comment by alex3165** [comment]
@UJKhokhar Yes this will include heatmap functionality 👍

**Comment by alex3165** [comment]
PR merged into v3 branch: https://github.com/alex3165/react-mapbox-gl/pull/441

**Comment by alex3165** [comment]
Released from tag `3.0.0`
