### ISSUE TITLE
Is it possible to render a react component on the map like shown?

### ISSUE THREAD

**Issue by jesster2k10** [alex3165/react-mapbox-gl#435]
I'm wondering if something like this can be implemented because if it can't then I'll have to switch to Google maps 

https://github.com/istarkov/google-map-react

**Comment by bnjmnjns** [comment]
The Marker component can be used to render a component to a position on the map. Is that what you're looking for?
https://github.com/alex3165/react-mapbox-gl/blob/master/docs/API.md#marker

**Comment by jesster2k10** [comment]
Yes with hover effects, etc but I’ve started using google maps now

**Comment by alex3165** [comment]
Hey @jesster2k10, @bnjmnjns was right you could use Marker component to render anything at a given position.
