### ISSUE TITLE
How can i get current zoom and bounds of box?

### ISSUE THREAD

**Issue by SkylinR** [alex3165/react-mapbox-gl#437]
How can i get current zoom and bounds of box?

**Comment by redbmk** [comment]
If you're not controlling it, I think you would need to get it from the map itself, which is passed into events. For example

```
<Map onZoom={map => this.setState({ zoom: map.getZoom() })} />
```
You can get the current bounding box using `map.getBounds()`

**Comment by SkylinR** [comment]
I’ve made it in this way exactly 😊 Thanks a lot !

Wysłane z aplikacji Poczta dla Windows 10

Od: Braden Kelley
Wysłano: poniedziałek, 13 listopada 2017 21:10
Do: alex3165/react-mapbox-gl
DW: SkylinR; Author
Temat: Re: [alex3165/react-mapbox-gl] How can i get current zoom and boundsof box? (#437)

If you're not controlling it, I think you would need to get it from the map itself, which is passed into events. For example
<Map onZoom={map => this.setState({ zoom: map.getZoom() })} />
You can get the current bounding box using map.getBounds()

**Comment by alex3165** [comment]
Thanks @redbmk for helping 👍
