### ISSUE TITLE
Issues with resizing (potentially due to flexbox container)

### ISSUE THREAD

**Issue by romeboards** [alex3165/react-mapbox-gl#445]
Echoing #395, there seems to be issues when the container resizes due to new elements / the window itself resizing. Not sure if this webpackbin is 100% replicating what I'm seeing on my end, but it does show how the map can fail to resize (both with and without a manual call to the mapbox `.resize()` function (try commenting out line 37).

I've also tried to not use flexbox (and instead have the container use inline-block) but the issue still arises.

https://www.webpackbin.com/bins/-KyrdSeFI0dpMmkHEuCx

Happy to add more details if necessary! Attached also is a screenshot of the issue on my current build; it arises when you toggle the tabs on the top left to hide/show the map view. If you drag to resize the window it corrects.

![image](https://user-images.githubusercontent.com/627751/32754241-0b39c4ce-c89e-11e7-92c8-0998c68edfad.png)

**Comment by alex3165** [comment]
@romeboards Sorry for the late reply, you need to resize after you actually update the style of the container, see: https://www.webpackbin.com/bins/-KzVbA5I7NKGyiSNEVhL

**Comment by oznekenzo** [comment]
^that wasn't much help as the link is broken.
