### ISSUE TITLE
cameraOptions

### ISSUE THREAD

**Issue by alpha-beta-soup** [alex3165/react-mapbox-gl#449]
Is it possible to set the [camera options](https://www.mapbox.com/mapbox-gl-js/api/#cameraoptions)? For example, I would like to set a camera option for the Map, common to all moving methods, such that moving (flying, easing, etc.) to a new map centre will also change the zoom and pitch, not just the centre of the map. It is already possible with this library to set the [animation options](https://www.mapbox.com/mapbox-gl-js/api/#animationoptions).

**Comment by alex3165** [comment]
Hey, you can already set `bearing`, `zoom`, `center`, `pitch`, however `around` is actually missing I will open a new issue for that.

**Comment by alex3165** [comment]
cf: https://github.com/alex3165/react-mapbox-gl/issues/454

**Comment by alpha-beta-soup** [comment]
I only searched the source for "cameraOptions", I assumed it would be distinct. Thanks!
