### ISSUE TITLE
Custom components as markers

### ISSUE THREAD

**Issue by AlexLourenco** [alex3165/react-mapbox-gl#45]
Hello,

According to the following, https://www.mapbox.com/blog/custom-markers-mapboxgl/, it is now possible to render html markup as a marker.
Are there any plans on implementing this? I am currently hacking my way through; trying to implement is as another Feature component. 

Thanks!

**Comment by alex3165** [comment]
Oh neat I haven't followed I will have a look this week-end but it's definitely something that should be implemented.

**Comment by AlexLourenco** [comment]
I was able to get a sample to work. An issue that I am having is that when we give the DOM element to Mapbox, it will re-allocate it and wrap it in another div with its respective absolute positioning.
The problem with this is that the view of the virtual DOM is now incorrect so if we add/remove a new marker, React will attempt to clear the previous children which are not longer where they are expected to be, throwing an exception.

My current workaround is to duplicate the markers. React children are appended to the canvas (rendering them invisible) and then on ComponentWillReceiveProps I check if a view should be added/remove and handle that accordingly (by cloning it and passing the clone to MapboxGL).
This approach isn't very elegant due to the duplication and the fact that when we clone the DOM we are missing all the event handlers (e.g onClick) that the react view might have.

**Comment by philpl** [comment]
@AlexLourenco The marker seems easy enough to implement, as long as we pass it a DOM element I think. It looks similar to how the popups work. Do you think it's possible to copy the popup implementation and adapt it?

https://github.com/alex3165/react-mapbox-gl/blob/master/src/popup.js

**Comment by AlexLourenco** [comment]
Hey @philpl,

Unless I am missing something obvious, we need to perform the calls from react-mapbox-gl side due to the following:

https://github.com/mapbox/mapbox-gl-js/blob/335a0208e3293d910cf558dac0a9d129b50ab995/js/ui/marker.js#L43#L45#L70

As far as I know, if something manipulates the DOM (in terms of moving/removing nodes) outside reacts scope, exceptions will be thrown (the virtual DOM references will no longer be correct).

My take on this was to implement https://github.com/mapbox/mapbox-gl-js/blob/335a0208e3293d910cf558dac0a9d129b50ab995/js/ui/marker.js#L153-L154 on the library's side.

Keep in mind that this is an issue only if you are required to update/change the markers, if everything is static then no render updates would be made and therefore no exceptions would be raised.

**Comment by joshwcomeau** [comment]
Hi @AlexLourenco 

I need custom markers for a project I'm working on, and it's OK in my case if they're static (no updates needed).

Is your fork of the project currently working for this purpose? If so, I'd like to use it as a stop-gap until this feature is officially implemented.

(Also, @alex3165, loving these bindings. Much better than the other implementations I've seen :) )

**Comment by alex3165** [comment]
I have added a Marker component, you can now use the custom marker feature of mapbox-gl-js. I haven't tested it in deep so I will be available the next days to fix any issue you would encounter.

The feature is available with the version 0.14.0 of react-mapbox-gl

**Comment by alex3165** [comment]
Also there is no support for the attach popup feature for now I will work on it asap https://github.com/alex3165/react-mapbox-gl/issues/50
