### ISSUE TITLE
Feature Request - getBounds()

### ISSUE THREAD

**Issue by iambalaam** [alex3165/react-mapbox-gl#456]
Hi,

I have seen [`getBounds()`](https://www.mapbox.com/mapbox-gl-js/api/#map#getbounds) in the mapboxgl js docs and it would be so useful to have this exposed at the React level.

At the moment I am getting the `MapboxGl.Map` object manually and using the `getBounds()` on that, but I don't like bypassing the react.

**Comment by alex3165** [comment]
Hey @iambalaam, how would you see the API for that?

**Comment by iambalaam** [comment]
I've only seen that the `ReactMapboxGl`component has the map in its state, and it passes this down to all child components in their context.  You can call `getBounds()` on this.  I have only been doing this manually though, and haven't managed to get this to work in my code.

Would it be possible to pass in a custom child component to access this context?

**Comment by iambalaam** [comment]
Ah! apologies, I didn't realise these events exposed the whole map object.  

I want to call an api to get features to pass in a `GeoJSONLayer` to the map.  So this helps when the map is in use, but what would be the best way to initialise the features.  I've now looked closer in your docs at this, am I correct in assuming that `onStyleLoad` will be the first to fire?

**Comment by alex3165** [comment]
yes that's the one you should use
