### ISSUE TITLE
Popup anchors classes are not being set when anchor is unset

### ISSUE THREAD

**Issue by troqru** [alex3165/react-mapbox-gl#458]
[Demo here](https://www.webpackbin.com/bins/-KzxxXI85KpOj8G8SuoD)

When using Popup with auto-anchors, i'm ending up with class of "mapboxgl-popup-anchor-null" set to popup if null is passed as an anchor, or "mapboxgl-popup-anchor-undefined", if anchor is not set at all. 
This results in element "mapboxgl-popup-tip" not being visible.

**Comment by redbmk** [comment]
@troqru Do you have a backup of the demo? I tried to fork it to showcase another issue I ran into and it looks like I somehow converted it to an empty `Hello world` project!

**Comment by troqru** [comment]
@redbmk, when you save, it generates new link, so provided demo is still ok

**Comment by redbmk** [comment]
Oh, phew, it's still there. That's how I assumed it worked, but I had clicked on the link quite a few times, even in incognito, and it kept showing me Hello World.

**Comment by alex3165** [comment]
https://github.com/alex3165/react-mapbox-gl/pull/463/files should fix it

**Comment by alex3165** [comment]
`react-mapbox-gl@3.2.1` should have the fix 👍
