### ISSUE TITLE
Prevent automatic recentering.

### ISSUE THREAD

**Issue by nmccrea-db** [alex3165/react-mapbox-gl#461]
Apologies in advance for my React n00bdom.

I have a map with a `center` property define. On the same page I have a panel of controls, some of which update what is being rendered on the map (a fill extrusion layer, in this case).

Steps to reproduce:
- Load the map. In it's initial state it is rendered correctly.
- Drag the map around to view it from different angles.
- Manipulate something in the control panel, causing the objects on the map to be redrawn.

Desired behavior:
- The map camera position does not change.

Actual behavior:
- The map resets its center and zoom level.

I feel pretty certain I am missing something simple and I'm just a big dummy but I have Googled this extensively to no avail, so any help would be great.

Thanks in advance.

**Comment by redbmk** [comment]
I believe props like `center` and `zoom` use `===` equality to check if two items are the same.

```
const center = [0, 0];
console.log(center === center) // true
console.log(center === [0, 0]) // false
console.log([0, 0] === [0, 0]) // false
```

If you create a new array on every render, (e.g. `<Map center=[0, 0] />`), it will recenter every time it renders. so the solution would be to use a value defined outside the render (e.g. `this.state.center`, `this.props.center`, or a `const` defined outside the class).

I had the same issue and only realized what I was doing wrong after finding a similar issue that's been closed. It's [sort of mentioned in the README](https://github.com/alex3165/react-mapbox-gl#why-are-zoom-bearing-and-pitch-arrays-), but I think it could be a little more clear somehow to help keep this issue from resurfacing. Maybe specifically showing "good" and "bad" examples of how to set static values without causing the map to update on rerenders.

**Comment by nmccrea-db** [comment]
@redbmk, that did the trick! We now reference pre-defined arrays on render, rather than declaring the arrays inline, and the problem appears to be solved.

Thank you so much!
