### ISSUE TITLE
Help  with live updating

### ISSUE THREAD

**Issue by suyesh** [alex3165/react-mapbox-gl#465]
I have a streetview container on the right and the street view marker on the map on left, the marker is the Marker component inside Map and uses the streetview's current position. It moves as you move through the street view. My only problem is the whole map is refreshing, how to i make the streetview marker smoothly move as you move through the streetview, without reloading the entire map? 

What am i looking for? the approach? 

![streetview](https://user-images.githubusercontent.com/3803603/33497089-a453a60c-d69a-11e7-86f1-13f459eff8b1.gif)

**Comment by alex3165** [comment]
@suyesh if the map reload it is probably because you create a new instance of the Map everytime you render your component. Make sure you use the factory outside of the render function of your component:
```
const Map = ReactMapboxGl({
  accessToken: "pk.eyJ1IjoiZmFicmljOCIsImEiOiJjaWc5aTV1ZzUwMDJwdzJrb2w0dXRmc2d0In0.p6GGlfyV-WksaDV_KdN27A"
});

const MapWrapperComponent = () => (
<Map
  style="mapbox://styles/mapbox/streets-v9"
  containerStyle={{
    height: "100vh",
    width: "100vw"
  }}>
    <Layer
      type="symbol"
      id="marker"
      layout={{ "icon-image": "marker-15" }}>
      <Feature coordinates={[-0.481747846041145, 51.3233379650232]}/>
    </Layer>
</Map>
);

```

**Comment by suyesh** [comment]
Thank you so much. That worked.

**Comment by suyesh** [comment]
@alex3165  That worked great. But now i am having another issue, When i click on streetview, the map is split into two and then the streetview is centered, Now the map doesn't seem to resize. Is there a way to re reload the factory itself?

**Comment by alex3165** [comment]
You have to manually call `map.resize` if you want to make the map take the full size of it's container. You can get an instance of the map as a first parameter of any events

**Comment by suyesh** [comment]
i have 'this.map' ref, what is map.resize? this.map doesnt have any property called resize

**Comment by alex3165** [comment]
see https://github.com/alex3165/react-mapbox-gl/blob/master/example/src/demos/index.tsx#L63

**Comment by suyesh** [comment]
Thank for you help @alex3165 . I really appreciate it. Best wishes for whatever you are up to :)

**Comment by robmarshall** [comment]
How do you get access to the "map" const? The example doesn't show where it gets passed from.

I have set up a map as specified, but cannot get access to .resize

**Comment by mklopets** [comment]
@robmarshall see "Using the original Mapbox API" in [the docs](https://github.com/alex3165/react-mapbox-gl/blob/master/docs/API.md#using-the-original-mapbox-api)

**Comment by robmarshall** [comment]
Nice one! Massive help.
