### ISSUE TITLE
Map style according to state crashes app

### ISSUE THREAD

**Issue by amitassaraf** [alex3165/react-mapbox-gl#466]
When doing something like this:
`style={this.props.mapMode.mapStyle}`

and also rendering a Layer with an inline source (Specifically I am using GeoJSONLayer but this happens on all layers)

`<GeoJSONLayer
           data={.... inline source}
            ....`

Everything works fine until the mapStyle changes, then an error is thrown:

`Uncaught TypeError: Cannot read property 'setData' of undefined
    at GeoJSONLayer../node_modules/react-mapbox-gl/lib/geojson-layer.js.GeoJSONLayer.componentWillReceiveProps (geojson-layer.js:128)`

Easily reproducible, just change mapstyle while using geojson

**Comment by amitassaraf** [comment]
@alex3165 This actually happens no matter if it's an inline source or not. Basically why switching map style when any react mapbox component is mounted, everything breaks :(

**Comment by alex3165** [comment]
Hey @amitassaraf Could you reproduce your problem with webpackbin: https://www.webpackbin.com/bins/-L-Y88sONY3CSP38tpHW I can't reproduce it with react-mapbox-gl v3

**Comment by amitassaraf** [comment]
@alex3165 I will do this tonight :)

**Comment by sergei-zelinsky** [comment]
Hi, guys!

I have the same problem.

This is my quick reproduction - https://www.webpackbin.com/bins/-L0phWZaJPfO_5rUcP0o

When you change style it is ok, but when you wanna change style and data for GeoJSON layer simultaneously it causes map crash.

I tried to fix this in https://github.com/alex3165/react-mapbox-gl/pull/478.

Thanks!

@alex3165 @amitassaraf

**Comment by alex3165** [comment]
Hey @sergei-zelinsky Thank you very much for reproducing the issue, I created a PR to fix it https://github.com/alex3165/react-mapbox-gl/pull/481

**Comment by alex3165** [comment]
Hey @sergei-zelinsky, thank you for reproducing / creating the PR, it is the right approach but I also made a few changes on this bit of code, I hope you don't mind. Here is the PR https://github.com/alex3165/react-mapbox-gl/pull/481

**Comment by alex3165** [comment]
react-mapbox-gl version 3.4.1 should include this fix. Thanks @sergei-zelinsky for pointing out the issue! 👍

**Comment by 4xDMG** [comment]
I'm still experiencing this bug after updating to 3.4.1

**Comment by sergei-zelinsky** [comment]
@4xDMG In my case, after update to version 3.4.1, this bug has disappeared.

**Comment by 4xDMG** [comment]
@sergei-zelinsky I must be doing something wrong. I have three seperate maps in my app. It works on one but not on the other 2. Spent a few hours yesterday trying to work it out. If I use the GeoJSONLayer component it works. If I get some time next year I'll investigate more and see if it's just me being stupid or if its some weird edge case.
