### ISSUE TITLE
Where are lighting properties defined?

### ISSUE THREAD

**Issue by nmccrea-db** [alex3165/react-mapbox-gl#467]
I'm having some trouble determining which component parameters I can use to specify mapbox-gl lighting properties, as defined [here](https://www.mapbox.com/mapbox-gl-js/style-spec/#light). Would someone mind *illuminating* the situation?

**Comment by alex3165** [comment]
Hey @nmccrea-db light is a prop to pass to the style of the map. If you use Mapbox studio and point to the style using a string:
```jsx
<Map style="my_style">
```

I would suggest you to download your style from Mapbox studio and add your light property, then pass it to the component like this:
```jsx
<Map style={myStyleObject}>
```

**Comment by nmccrea-db** [comment]
I see. That looks like it does the trick. Thanks so much @alex3165.
