### ISSUE TITLE
Set fitBounds only initially

### ISSUE THREAD

**Issue by mastertinner** [alex3165/react-mapbox-gl#469]
I want to set initial `fitBounds` when the map loads for the first time. If I do so, the map goes back to these bounds whenever data changes (it's supposed to be a live map with moving `Feature`s). That's annoying to the user because they might be browsing the map by manually moving the view port and zooming. Whenever there's an update, they're back at the position computed from `fitBounds`.

What's the best way of initially setting `fitBounds` but then don't go back to these bounds on update?

**Comment by alex3165** [comment]
Hey @mastertinner , you should not break reference equality between rendering meaning you should keep the reference of the array of your fitbounds:
Dont do:
```
<map fitBounds={[...]}>
```

Instead do:
```
<map fitBounds={this.state.fitBounds}>
```

**Comment by bradsimantel** [comment]
Adding on to what @alex3165 said, you can also store the reference outside of your component/render function.

```javascript
const bounds = [...]
const Component = () => {
    return <Map fitBounds={bounds} />
}
```

**Comment by mastertinner** [comment]
Thanks for your answers! @alex3165, is this what you had in mind?

```javascript
class MyMap extends Component {

  constructor(props) {
    super(props);
    this.state = { fitBounds: props.initialFitBounds };
  }

  componentDidMount() {
    this.setState({ fitBounds: null });
  }

  render() {
    return (
      <Mapbox
        style="mapbox://styles/mapbox/streets-v9"
        containerStyle={{ height: '100vh', width: '100vw' }}
        fitBounds={this.state.fitBounds}
      >
      </Mapbox>
    );
  }

}
export default MyMap;
```

**Comment by alex3165** [comment]
@mastertinner Kind of, you can remove the componentDidMount, as long as you keep the reference of `fitBounds` in the state (or anywhere outside of the render function) and don't change the values, react-mapbox-gl shouldn't change your bounds. Feel free to reproduce your issue with https://www.webpackbin.com/bins/-KqtJN-qkLs4BPaVX0QS if it is unclear I will have a look

**Comment by mastertinner** [comment]
Thanks, @alex3165! That worked perfectly.
