### ISSUE TITLE
Implementation of latitudeDelta / longitudeDelta

### ISSUE THREAD

**Issue by Kornflexx** [alex3165/react-mapbox-gl#470]
Hello Alex,

First of all, I want to thanks you for your amazing work on this project.
I was wondering why this module didn't implement latitudeDelta & longitudeDelta. This feature is pretty important to me because other map like react-native-map include it (it seems to be kind of a standard).

Do you know how I can translate deltas to zoom ?

Have a nice day.

**Comment by alex3165** [comment]
Hello @Kornflexx, Do you have some links to the mapbox-gl-js documentation about that? I never came across this feature. Could you describe your use case?

**Comment by Kornflexx** [comment]
I register location on a phone app using https://github.com/react-community/react-native-maps . It's giving me latitude/longitude/latitudeDelta/longitudeDelta. I want to set the zoom prop of your module depending of deltas. I tried to translate zoom to delta but relation between zoom and deltas is not linear.

Mapbox seems to handle deltas (see this file: https://github.com/mapbox/mapbox-gl-native/blob/master/platform/darwin/src/MGLGeometry.h) but not exposing it.

I am starting thinking that you can not help me if there is no mapbox-gl api for that.

**Comment by khollund** [comment]
I would assume he doesn't want to add something Mapbox-gl-js doesn't have. But you should be able to calculate it yourself and use fitbounds to set the view to the wanted area. This will also take into account any other parameters your view has got, like padding.

**Comment by Kornflexx** [comment]
Implementing react-native-mapbox-gl in my phone app was pretty fast and fix all the issues I had.

**Comment by alex3165** [comment]
I will close this issue, as I don't think this is something which should be solved in react-mapbox-gl. The philosophy behind `react-mapbox-gl` is to match `mapbox-gl-js` features and turn them into react friendly way.
