### ISSUE TITLE
How to style a GeoJSONLayer

### ISSUE THREAD

**Issue by redixhumayun** [alex3165/react-mapbox-gl#474]
Hi, I'm using GeoJSONLayers to render some json data points, but I want these data points to be styled with a specific icon rather than a generic circle or any other polygon shape.
How do I go about this?

**Comment by redbmk** [comment]
@redixhumayun You can style it according to the [mapbox style spec](https://www.mapbox.com/mapbox-gl-js/style-spec). According to [the docs](https://github.com/alex3165/react-mapbox-gl/blob/master/docs/API.md#geojsonlayer) you just need to add props for the layer you need and whether you're styling for Layout or Paint. e.g.

```
<GeoJsonLayer
  symbolLayout={{
    'icon-image': 'restaurant-11',
  }}
/>
```

**Comment by daniel-hauser** [comment]
Closing because the question was answered.
