### ISSUE TITLE
Setting fitBounds from state with onMoveEnd causes infinite loop

### ISSUE THREAD

**Issue by bradsimantel** [alex3165/react-mapbox-gl#476]
When I set `fitBounds` from state, updating it `onMoveEnd`, I end up in an infinite loop. I set up a very simple demo [here](https://github.com/bradsimantel/react-mapbox-gl-debug).

I'm looking at `didFitBoundsUpdate` in `map.tsx` to see if there's a bug there, but I wanted to open an issue in case I'm just overlooking something simple.

**Comment by bradsimantel** [comment]
Checking out `didFitBoundsUpdate`, it looks like if `fitBounds !== nextProps.fitBounds`, `didFitBoundsUpdate` is set to true, which means we call `map.fitBounds`, which triggers a move event, which causes me to call `setState` and update the bounds, which gets me into my loop.

Seeing that, it seems like I'm misunderstanding how I should do what I want to do, which is to programmatically/declaratively set `fitBounds` while also tracking where the center of the map is if the user moves it. To me that meant passing `fitBounds` from state (which could be updated by other user actions outside the map) and tracking the map's position with `onMoveEnd` if the user moved the map.

Clearly that's not going to work, though. Do you have any suggestions?

**Comment by khollund** [comment]
It's pretty tricky to solve this especially if you need to have camera functions for UI as well (we use dynamic padding etc.). I ended up solving it by only using map center in state, not the bounds. It can get a bit complicated as you need to know when you want to and don't want to update the map position. But I kind of needed to anyway.

**Comment by bradsimantel** [comment]
Closing this issue since it's not really a bug or a feature request. I ended up just writing my own basic wrapper component for Mapbox GL JS.

**Comment by dalisalvador** [comment]
Hi,

I think I had the same issue. The way I solved it was to avoid using `fitbounds `and only use `zoom `and `center` as @khollund mentioned. 
I  used [geo-viewport](https://github.com/mapbox/geo-viewport#boundsviewport-zoom-dimensions-tilesize) package to get `{center, zoom}` from `bounds `or viceversa.

Cheers.

**Comment by olso** [comment]
Maybe this can help https://github.com/alex3165/react-mapbox-gl/pull/711
