### ISSUE TITLE
Render a large number of Features in a Layer simultaneously

### ISSUE THREAD

**Issue by kylebebak** [alex3165/react-mapbox-gl#486]
I've been using this library for a few weeks and I like it a lot. I have a question regarding `Marker` vs `Feature`.

So, I can render ~800 `Feature`s on my map without any problem. However, as @benrudolph mentioned in #457 , rendering ~800 `Marker`s on the map slows my browser to a crawl.

One problem with using a combination of `Layer` and `Feature` **is that not all the features are rendered to the map simultaneously** -- to see all 800 markers I have to zoom in very close and pan the map around. As you can see in the image below, if I'm zoomed out, only a small, seemingly random subset of the features I want to display are rendered.

<img width="650" alt="screen shot 2017-12-28 at 12 17 55 am" src="https://user-images.githubusercontent.com/1524088/34404803-a08793a6-eb64-11e7-9fcc-91edf7c46ad3.png">

I'd like to be able to render all 800 features on the map at once. If this isn't possible, this is a little surprising to me. Rendering this many markers to a map is a very common use case. I was able to do it years ago using Google Maps, as is demonstrated in the image below, without slowing the frame rate of the browser significantly.

<img width="849" alt="screen shot 2017-12-28 at 12 17 37 am" src="https://user-images.githubusercontent.com/1524088/34404857-ebc0ae7a-eb64-11e7-997d-569a33e92f3c.png">

Thank you for your help!

**Comment by Wykks** [comment]
Hi !

Of course, never use markers if you don't need html to render your symbols.

Take a look at layer symbol config to change the default behavior of mapbox-gl:
https://www.mapbox.com/mapbox-gl-js/style-spec#layers-symbol

**Comment by kylebebak** [comment]
@Wykks 
Thanks! Passing `'icon-size': true,` to the `layout` prop of `Layer` did the trick.

While we're on the subject, I had another question: is there a way to style individual features within a layer, so they can be displayed with a different color/size/icon?

Thanks again!

**Comment by alex3165** [comment]
Hi @kylebebak I don't think there is any good solution for this use case 500+ markers of 5 / 10 different types. What I have done so far is to create 5 / 10 different layers.

Any PR welcome to add a warning in the doc specifying that Marker have bad performances when using 100+ of them (maybe even less, I haven't benchmarked it).

**Comment by Wykks** [comment]
You totally can display symbol in the same layer with different color/size/icon/...
It's the feature called data driven styling. You have an example right here: https://www.mapbox.com/mapbox-gl-js/example/data-driven-circle-colors/

**Comment by kylebebak** [comment]
@Wykks @alex3165 

I don't mean to beat a dead horse, but I created a video to help you guys diagnose what might be happening.

Here's my code, it's totally standard. It is, in fact, the exact code Alex recommends for adding markers to map (wrap a bunch of features in a layer, instead of using the marker component).

```

**Comment by Wykks** [comment]
Humm there's a lot going on indeed.Your `render` function looks fine (just a react tip: try to avoid arrow function/bind inside `render`). Could you reproduce theses issues using the webpackbin template attached in the readme? or by forking react-mapbox-gl-debug?

**Comment by kylebebak** [comment]
@Wykks @alex3165 
Again, thanks for writing the library, but I can't continue to sink time into this. All of us know the issues I mentioned have nothing to do with an arrow function/bind inside `render`.

As for reproducing the issues, it's really easy. Just render some `Feature`'s inside a map and throw a `Popup` in there.

You guys ought to reopen this issue, or split it into several issues. It seems like these problems are are due to `react-mapbox-gl` and not `mapbox-gl-js`.

**Comment by hughlomas** [comment]
@Wykks I'm having very similar issues with onMouseEnter firing multiple times for popups on Features in a symbol Layer.

**Comment by tmcintire** [comment]
I have a similar performance problem.  We are looking to switch over from Leaflet to MapBoxGL.  In leaflet, when I instantiate a new Marker class I'm able to give it an HTML element to render as the marker, and using the leafletmarkerclusterer library am able to cluster those html elements.  From there we use plain old javascript to update the markers as we need to, and its lightning fast.  

In previous iterations, we used angular to render our markers, which was extremely while panning, zooming, and even slower when loading (you're talking 9-10 seconds for a layer with 400 markers to appear, and during this time the user is blocked)

So, I think the performance issue here is that we are trying to render a react component for a marker, when a standard HTML element with plain old javascript would do the trick and be much, much faster.  Is there/will there ever be a way to pass an html element into the cluster component instead of having to render a `Marker` component each time?  I think that's why the performance hit is so large.  Thanks

**Comment by bondom** [comment]
@kylebebak  @tmcintire  What did you choose instead of this library? I need to render about 200 custom markers with hover and popup functionalities. What would do you suggest?

**Comment by compwright** [comment]
Check out this demo: https://github.com/istarkov/google-map-thousands-markers

**Comment by CSFlorin** [comment]
Anyone wondering about the original question: the prop to now use to show all features regardless of overlap is "icon-ignore-placement"
