### ISSUE TITLE
Issue changing style of map with layer that has images

### ISSUE THREAD

**Issue by benrudolph** [alex3165/react-mapbox-gl#487]
This library throws an error if you try to change the style of the react map that contains a layer with loaded images

For example:

```
<ReactMap
  style={this.props.style}
  ...
>
  <Layer id="my-features" images={myImages}>
   {features}
  </Layer>
</ReactMap>
```

Then when you change `this.props.style`, the `Layer` throws an error because it tries to add the same images.

I believe the fix is to add a check for `hasImage` here: https://github.com/alex3165/react-mapbox-gl/blob/master/src/layer.ts#L181

**Comment by alex3165** [comment]
Hi @benrudolph Sorry for the late reply but there is an open issue for that https://github.com/alex3165/react-mapbox-gl/issues/464 I was waiting to get some types from definitelyTyped to be merged but it seems quite critical so I might go ahead with a temporary hack around the types. In the meantime you can directly upload your images in mapbox studio if you are using it, they will be downloaded with your style
