### ISSUE TITLE
Uncaught TypeError: Cannot read property 'transition' of undefined

### ISSUE THREAD

**Issue by erick-otenyo** [alex3165/react-mapbox-gl#496]
Getting this error on the console when setting fitBounds on Map Component.

**Comment by alex3165** [comment]
Hi @erick-otenyo, could you reproduce the issue with the webpackbin boilerplate in the readme?

**Comment by erick-otenyo** [comment]
Here is the fork https://github.com/erick-otenyo/react-mapbox-gl-debug

also the fork is live at https://react-mapbox-debug.surge.sh

Am using google chrome. The error shows on the chrome console

**Comment by jthetzel** [comment]
I'm also seeing this in the react-mapbox-gl demo, before and after 0.43.0 upgrade. Possibly related to mapbox/mapbox-gl-js#1970 .

**Comment by SBRK** [comment]
Also getting this after updating from react-mapbox-gl 2.7 to 3.5 and mapbox-gl-js to 0.43

**Comment by SBRK** [comment]
I don't have the problem with 0.44, and the rest seems to be working without problems

**Comment by redbmk** [comment]
I was actually seeing this when running the demos in the `examples` folder. Upgrading the peer dependency to `0.44.0` fixed it though - do we know of any breaking changes from 0.43 to 0.44?

**Comment by sachinhd517** [comment]
Uncaught TypeError: Cannot set property 'transition' of undefined
