### ISSUE TITLE
Example fails to build due to typescript errors

### ISSUE THREAD

**Issue by jthetzel** [alex3165/react-mapbox-gl#499]
Example does not build after commit d9359a15ee6ebe6afec759bcc6e0edae54289fdc . Various TS2403 and TS2605 errors reported.

[typescript.txt](https://github.com/alex3165/react-mapbox-gl/files/1649254/typescript.txt)

**Comment by jthetzel** [comment]
I have this fixed locally, will submit a pull request shortly.

**Comment by alex3165** [comment]
Released with tag `3.5.0` of [react-mapbox-gl](https://github.com/alex3165/react-mapbox-gl/releases/tag/v3.5.0)
