### ISSUE TITLE
Rendering to a PureComponent

### ISSUE THREAD

**Issue by canfie1d** [alex3165/react-mapbox-gl#505]
I am attempting to render a map to a regular react component but it is rendered twice on each page load (which leads to 2 map stylesheet imports and 2 map api requests). My first thought was to use a pure component which indeed stopped the 2nd render but now my map doesn't center in the same place as the marker i placed (which _does_ show up in the correct spot). It seems as though that 2nd render adjusts the final position of the map, maybe?

I've tried a few different API hooks to force an update but no luck yet. Does this sound like an implementation issue or a bug? 

Here is my component code.
```import React from 'react';
import ReactMapboxGl, { Marker, ZoomControl } from "react-mapbox-gl";

export default class Map extends React.PureComponent {
  render() {
    const lngLat = [-122.341960, 47.658608];
    const Map = ReactMapboxGl({
      accessToken: process.env.REACT_APP_MAPBOX_ACCESS_TOKEN,
      scrollZoom: false
    });

    return (
      <Map
        zoom={[13]}
        style={this.props.mapStyles}
        className='map'
        center={lngLat}
      >
        <Marker coordinates={lngLat} anchor="bottom">
          <img className='map__pin' src={''} alt='' />
        </Marker>
        <ZoomControl />
      </Map>
    );
  }
}
```

**Comment by Wykks** [comment]
[Do not](https://github.com/alex3165/react-mapbox-gl/issues/465) [instanciate](https://github.com/alex3165/react-mapbox-gl/issues/350#issuecomment-330178189) [the map](https://github.com/alex3165/react-mapbox-gl/issues/313) [in the render fonction](https://github.com/alex3165/react-mapbox-gl/issues/461#issuecomment-347386140) :smile:

**Comment by canfie1d** [comment]
The same behavior exists when holding center in state.

**Comment by canfie1d** [comment]
Ah, of course. Thank you.
