### ISSUE TITLE
Please sit around a table and talk

### ISSUE THREAD

**Issue by cyrilchapon** [alex3165/react-mapbox-gl#511]
- https://github.com/AlpacaTravel/react-map-gl-alt
- https://github.com/uber/react-map-gl
- https://github.com/alex3165/react-mapbox-gl

Both MapboxGL.js and React are 4 years old. There are currently 3 different, active and maintained, libraries out there trying to implement a React friendly API for Mapbox. While each of them is pretty great and hard work, each of them lack features. When coming from a raw MapboxGL.js background, new to react, this is pretty critical and hard to make a reliable choice. I guess coming from a React background and discovering MapboxGL and making the same choice is also hard.

This seems pretty much complicated, as governance, paradygms, workflows and many stuff are different in each of the repos. But it also feels like there is so much relevant and valuable thing to do with all that hard work, than 3 different and incompatible libraries..

The beauty of opensourcing is that everything is possible, isn't it ? So hey, what about sitting around a table and talking ?

Related :
- https://github.com/uber/react-map-gl/issues/87
- https://github.com/uber/react-map-gl/issues/176
- https://github.com/alex3165/react-mapbox-gl/issues/97

Same issue duplicated :
- https://github.com/AlpacaTravel/react-map-gl-alt/issues/16
- https://github.com/uber/react-map-gl/issues/451

**Comment by alex3165** [comment]
Hey @cyrilchapon, thanks for your suggestion, I agree it would be great to have a complete working single solution indeed and to be honest I would be happy to help on such a thing if someone else want to drive the discussion / project. I think it should come from Mapbox as they have all the knowledges to make it right (they have peoples using React internally for Mapbox studio and own mapbox-gl-js). However I am not sure it is their priority but you can suggest it again and see what they think about it.

**Comment by khollund** [comment]
Personally I am glad they are different and it feels like react-mapbox-gl has matured with mapbox and my own app and does everything I wanted it to do, something uber/react-map-gl isn't and doesn't want to from my impression. It's ok to do things differently too, as long as from the github intro page it's clear what it does and doesn't do or want to do.

**Comment by cyrilchapon** [comment]
Closed in favor of more followed discussion inside [official mapbox-gl.js repo](https://github.com/mapbox/mapbox-gl-js/issues/6090)
