### ISSUE TITLE
map blink when center of map change(movingMethod Not working)

### ISSUE THREAD

**Issue by spybaby1** [alex3165/react-mapbox-gl#512]
Hi!!! I'm try to update version of react-mapbox-gl from v2 to v3 but i found a problem when props that store center location was changed but every change of this state map is blink everytime that not apply with movingMethod props.

**Comment by nontachaiwebdev** [comment]
I found this problem too.

**Comment by alex3165** [comment]
Did you make sure you don't call the map factory in the `render` method of your react component: https://github.com/alex3165/react-mapbox-gl/blob/master/example/src/demos/londonCycle.tsx#L11

**Comment by alex3165** [comment]
I will close this issue in favour of https://github.com/alex3165/react-mapbox-gl/issues/534

**Comment by spybaby1** [comment]
Thank @alex3165, My problem was solved.
