### ISSUE TITLE
Feature.onDragStart ?

### ISSUE THREAD

**Issue by cyrilchapon** [alex3165/react-mapbox-gl#514]
Is Feature.onDragStart observable in any way ?

Is there a workaround ?

Thanks :)

**Comment by alex3165** [comment]
Hey @cyrilchapon, I meant to work on it but I haven't found time to do it. I will close this issue in favour of https://github.com/alex3165/react-mapbox-gl/issues/412

**Comment by cyrilchapon** [comment]
Oh sorry hadn't seen this one.

For our use case in here, it would be to highlight hovered features during drag time, if you want an idea :)
