### ISSUE TITLE
The examples are not working ? 

### ISSUE THREAD

**Issue by aziz-boudi4** [alex3165/react-mapbox-gl#52]
1- After following all the steps in the readme file, I tried to run the examples and I got this error :

		        `throw new WebpackOptionsValidationError(webpackOptionsValidationErrors);
		        ^
        WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
         - configuration.resolve.extensions[0] should not be empty.
            at webpack (/Users/Downloads/react-mapbox-gl-  master/example/node_modules/webpack/lib/webpack.js:16:9)
            at Object.<anonymous> (/Users/Downloads/react-mapbox-gl-master/example/server.js:5:16)
            at Module._compile (module.js:409:26)
            at Object.Module._extensions..js (module.js:416:10)
            at Module.load (module.js:343:32)
            at Function.Module._load (module.js:300:12)
            at Function.Module.runMain (module.js:441:10)
            at startup (node.js:139:18)
            at node.js:968:3
        [nodemon] app crashed - waiting for file changes before starting...`

2- After some research I managed to make it work by doing this : 
               
                `npm uninstall webpack --save-dev`
                `npm install webpack@2.1.0-beta.22 --save-dev`

3- This resolved the issue but now I'm getting another error : 

        ERROR in ./src/all-shapes.js
        Module not found: Error: Can't resolve 'react-mapbox-gl' in '/Users/Downloads/react-mapbox-gl-master/example/src'
         @ ./src/all-shapes.js 8:0-99
         @ ./src/index.js
         @ multi main

        ERROR in ./src/geojson-example.js
        Module not found: Error: Can't resolve 'react-mapbox-gl' in '/Users/Downloads/react-mapbox-gl-master/example/src'
         @ ./src/geojson-example.js 8:0-89
         @ ./src/index.js
         @ multi main
 
        ERROR in ./src/london-cycle.js
        Module not found: Error: Can't resolve 'react-mapbox-gl' in '/Users/Downloads/react-mapbox-gl-master/example/src'
         @ ./src/london-cycle.js 10:0-84
         @ ./src/index.js
         @ multi main

4- Question:
 How can I make the example work ?

**Comment by alex3165** [comment]
Yes apparently it is failing with a version greater than beta.21, I have updated the package .json to only use the .21 version of webpack https://github.com/alex3165/react-mapbox-gl/commit/4542935dcac896af6c116c81754cab1a3de211ff I will try to figure out what is happening with the next versions

**Comment by alex3165** [comment]
Thank you for the issue 👍

**Comment by philpl** [comment]
The latest version of webpack 2 is actually for the first time validating the config files. I will update them accordingly this weekend. 🙌
