### ISSUE TITLE
README.md should have a link to http://alex3165.github.io/react-mapbox-gl/

### ISSUE THREAD

**Issue by rotoglup** [alex3165/react-mapbox-gl#523]
I did initially miss the link which is in the project description, and only followed the link to the API doc.

It would be helpful to have a clear link to this excellent introduction site.

I'm not sending a PR as I don't want to presume too much about the README format.

**Comment by alex3165** [comment]
Thanks @rotoglup for the suggestion, I have added a link to the demos in the readme 👍 https://github.com/alex3165/react-mapbox-gl/commit/31af6fe80eb1125d4bc543c9a6c369b76f74fcf7
