### ISSUE TITLE
Map cannot fit within canvas with the given bounds, padding, and/or offset.

### ISSUE THREAD

**Issue by nikkiczx** [alex3165/react-mapbox-gl#529]
Does the warning

> Map cannot fit within canvas with the given bounds, padding, and/or offset.

mean too far or too near? Cos it works when the two coordinates are very, very close, but when it's like a kilometer away, or even 500 meters away, it gives me this warning message.

**Comment by alex3165** [comment]
This is a warning triggered by [mapbox-gl-js](https://github.com/mapbox/mapbox-gl-js), I would suggest you to raise an issue on their repository or ask on [Stackoverflow](https://stackoverflow.com/), I don't think it is related to react-mapbox-gl.
