### ISSUE TITLE
GeoJSONLayer data does not accept uploaded File object

### ISSUE THREAD

**Issue by crunchex** [alex3165/react-mapbox-gl#536]
GeoJSONLayer data does not accept a File object uploaded from a file upload form input. I am using a vanilla React form input component of type "file" and can confirm this File object gets set into my component's state and then passed into the GeoJSONLayer as a data prop.

But from here, I get the error:
```
index.js:2177 Error: Error: Input data is not a valid GeoJSON object.
    at Actor.receive (mapbox-gl.js:501)
```

The exact same file works if I just import it using an ES6 import statement, so I'm not sure what the difference is here. Do I need to read the File object into a JSON object? If that's the case, then the documentation should reflect that.

**Comment by crunchex** [comment]
Was a little tricky, but I was correct in that there were a couple steps to get this to work:
```
<input type="file" onChange={
  (e) => {
    const file = e.target.files[0]
    const fr = new FileReader()
    fr.onload = (e) => {
      const data = e.target.result
        this.setState({ data: JSON.parse(data) })
    }
    fr.readAsText(file)
  }} />
```

**Comment by arnaudambro** [comment]
Hi there,
I got the same error, but my config is less complex than yours : I just pass a props.mapBoxId (a string) to `MyMap` component, which renders a `<Map>` component from `react-mapbox-gl`.


        import React from 'react';
        import ReactMapboxGl from 'react-mapbox-gl';

        const Map = ReactMapboxGl({
          accessToken: `${process.env.REACT_APP_MAPBOX_ACCESS_TOKEN}`,
        });

        class MyMap extends React.Component {

          render() {

            return(
              <Map 
              style={this.props.mapBoxId}
              ...other props
              />
            )
          }
        }

As a style, I tried some stuff, with different results.
Let's say the props is `"mapbox://styles/mapbox/streets-v10"`

- `style={this.props.mapBoxId}` returns `Error: Error at Actor.receive (mapbox-gl.js:501)`
- `style={JSON.stringify(this.props.mapBoxId)}` returns `GET http://localhost:3000/%22mapbox://styles/arnaudambro/cjb3vyq6k04yg2rmx0k1vye3o%22 404 (Not Found)`
- `style={JSON.parse(this.props.mapBoxId)}` returns `Uncaught SyntaxError: Unexpected token m in JSON at position 0`
- `style={JSON.parse(JSON.stringify(this.props.mapBoxId))}` returns `Error: Error at Actor.receive (mapbox-gl.js:501)`

How should I put it ?
