### ISSUE TITLE
There are no suggestions results after input.

### ISSUE THREAD

**Issue by gercog1** [alex3165/react-mapbox-gl#540]
I created my components like it was shown at https://github.com/alex3165/react-mapbox-gl/issues/123,

my Geocoder components looks like: 

import { createElement, Component } from 'react';
import mapboxgl from 'mapbox-gl';
import PropTypes from 'prop-types';
import '@mapbox/mapbox-gl-geocoder/dist/mapbox-gl-geocoder.css';
import * as MapboxGeocoder from '@mapbox/mapbox-gl-geocoder';

mapboxgl.accessToken = 'accessToken ';

class Geocoder extends Component {
    static contextTypes = { map: PropTypes.object.isRequired };

    componentDidMount() {
      const { map } = this.context;

      map.addControl(new MapboxGeocoder({
          accessToken: mapboxgl.accessToken,
      }));
    }

    render() {
      return null;
    }
}

export default Geocoder;

my Map component look like : 
import React, { Component } from 'react';
import ReactMapboxGl, { ZoomControl } from 'react-mapbox-gl';
import mapboxgl from 'mapbox-gl';
import '@mapbox/mapbox-gl-geocoder/dist/mapbox-gl-geocoder.css';
import { connect } from 'react-redux';
import sandSiteImg from '../../../../public/img/icons/from.png';
import Geocoder from './Geocoder';

mapboxgl.accessToken = 'accessToken';

const Map = new ReactMapboxGl({
  accessToken: mapboxgl.accessToken,
});

class MapBox extends Component {
  constructor(props) {
    super(props);
    this.state = {

    };
  }

  render() {
    return (
      <Map
        style="mapbox://styles/mapbox/satellite-v9"
        movingMethod="jumpTo"
        containerStyle={{
                    height: 250,
                    width: `${100}%`,
                }}
        center={[-79.4512, 43.6568]}
        onStyleLoad={(map) => {

            map.loadImage(sandSiteImg, (error, image) => {
                if (error) throw error;
                map.addImage('sandSiteImg', image);
            });
            map.on('click', (e) => {
                console.log(JSON.stringify(e.lngLat));
                map.on('result', (e) => {
                    map.getSource('single-point').setData(e.lngLat);
                });
            });
  }}
      >
        <ZoomControl position="top-left" />
        <Geocoder />
      </Map>

    );
  }
}
function mapStateToProps(state) {
  return ({

  });
}

function mapDispatchToProps(dispatch) {
  return ({

  });
}

export default connect(mapStateToProps, mapDispatchToProps)(MapBox);

i have the same response from api that in example on official site, but on screen i just observe infinty loading animation of serach form. Any ideas how to fix? thx.

**Comment by daniel-hauser** [comment]
Looks like a problem with the `mapbox-gl-geocoder` control, I see nothing in the code that interacts with it so it's probably not related to `react-mapbox-gl`
