### ISSUE TITLE
initialize GeoJSONLayer

### ISSUE THREAD

**Issue by dariarse** [alex3165/react-mapbox-gl#541]
Hi guys! Forgive me if this question has been asked before. I have cheked the documentation and some issues but I could not figure out how to display a geojson layer.

I'm currently trying to display a geojson layer but I'm getting this error:
`Uncaught TypeError: Cannot read property 'addSource' of undefined
`
I've tried several things but I think the main issue is that I'm not defining well the source options. Currently I have:

``` 
    <GeoJSONLayer
        id = 'someId'
        data={this.state.data}
        lineLayout={{
          'visibility': 'visible',
          "line-join": "round",
          "line-cap": "round"
        }}
        linePaint={{
          'line-width': 6,
          "line-color": '#f8f9fa'
        }}
        sourceOptions = {{
          'type': 'geojson'
        }}
      />
```

I've tried to check your source code and the mapbox-gl one, but I'm still unable to set corectly the source options to display a LineString.  Could you give me a hint, please? 
Thank you!

**Comment by daniel-hauser** [comment]
Sounds like a React `Context` issue, make sure that `<GeoJSONLayer>` is in the children tree of `<Map>`

**Comment by mklopets** [comment]
The `sourceOptions.type` shouldn't have to be redefined. Other than that, closing as this is not reproduceable.
