### ISSUE TITLE
hi, How do you get the coordinates of the click?

### ISSUE THREAD

**Issue by laiyiyi** [alex3165/react-mapbox-gl#546]
![image](https://user-images.githubusercontent.com/12541388/36784554-cc759cf6-1cba-11e8-81a6-898d6dbe5588.png)
![image](https://user-images.githubusercontent.com/12541388/36784563-d3a107ea-1cba-11e8-90fe-21947a7d8979.png)

Nothing here...

![image](https://user-images.githubusercontent.com/12541388/36784605-fae9498e-1cba-11e8-80b3-4d8e6dd82c9e.png)

**Comment by khollund** [comment]
Do you want to get the click on the marker or anywhere in the map? Looks like you are mixing two different things. You can just use onClick on the marker if you want the former.

**Comment by laiyiyi** [comment]
@khollund Yes，I want to get the coordinates of the click position。but，Use onClick can only get center coordinates,

**Comment by khollund** [comment]
You can call an event on Map onClick, then in that use functionname(map,evt) and then log like: 
`console.log('Map clicked!',evt.lngLat.lat,evt.lngLat.lng);`

Works anywhere in the map, and you can show features under the click using the same functionality.

**Comment by laiyiyi** [comment]
OK，thank you

**Comment by mklopets** [comment]
Seems like the question got answered by @khollund (thanks!).
