### ISSUE TITLE
Detect when raster layer has retrieved all tiles

### ISSUE THREAD

**Issue by ishiland** [alex3165/react-mapbox-gl#548]
Is it possible to detect when a raster layer has finished retrieving all tiles?  My particular use case is to update the state when the raster layer is retrieving tiles and then again when it has finished. 

here is my layer/source setup:
```
         <Source id={ "raster_source"}
                onSourceLoaded={e => this.rasterLayerLoaded(e)}  // Only fired when initially loaded
                tileJsonSource={{
                          type:  "raster",
                          tiles: "https://myTileServer.com/xyz/{z}/{x}/{y}.png8",
                          tileSize: 256
                      }}/>,
               <Layer
                    type={"raster"}
                     id={"raster_layer"}
                    sourceId={ "raster_source"}
                />
```

**Comment by kdedakia** [comment]
I'm also attempting to do the same thing and am unable to figure out a good solution.
I've been trying to use mapbox's built in events but `map.areTilesLoaded()` is set to true before the raster tiles have actually been loaded and rendered.

```
this.map.on('sourcedata', (e) => {
   if (this.map.areTilesLoaded()) {
      // Do stuff here
   }
}

```

Please let me know if you find a solution!

**Comment by ishiland** [comment]
Looks like this has been an open issue for awhile now in mapbox/mapbox-gl-js#1715. I will track the progress there.
