### ISSUE TITLE
Mapboxgl already in use in an app

### ISSUE THREAD

**Issue by awhenderson** [alex3165/react-mapbox-gl#570]
I'm working with a complex website that loads the mapbox-gl library elsewhere, as well as react-mapbox-gl for some specific React based components and I want to avoid loading the library twice.  Can I setup react-mapbox-gl to use either the already loaded mapbox-gl library or even a global version of mapbox-gl?

**Comment by mklopets** [comment]
mapbox-gl is a peer dependency – it doesn't include its own. This means you can indeed have a single mapbox-gl in your code.
