### ISSUE TITLE
Add unit test

### ISSUE THREAD

**Issue by alex3165** [alex3165/react-mapbox-gl#58]
@philpl Should we mock `mapbox-gl` in order to only test the `react-mapbox-gl` layer so that we don't have to worry about rendering the map on the server side ?

**Comment by philpl** [comment]
Probably. That might be a lot of work though. Maybe we should resort to testing `Layer` and the other sub-components using mocks, and the map itself using a very minimal functional test?

**Comment by alex3165** [comment]
Ok yes sounds good, most of the logic is on the Layer anyway. What about the `Popup` and the `Marker` ? they use `mapbox-gl` as well

**Comment by alex3165** [comment]
https://github.com/alex3165/react-mapbox-gl/pull/71 wip
