### ISSUE TITLE
Not compatible with Node 10

### ISSUE THREAD

**Issue by mashaal** [alex3165/react-mapbox-gl#592]
Recently updated to Node 10 and was not able to install this package.

` The engine "node" is incompatible with this module. Expected version ">=4 <=9"`

**Comment by danielreiser** [comment]
Is this related to upath?

**Comment by mklopets** [comment]
While this is the case, you can use `--ignore-engines` w/ yarn.

**Comment by wadouk** [comment]
Just installed as a dependency with node 10 / yarn and it doesn't shout.
Maybe only on dev dependencies ? just had an issue with that and removing package-lock for npm or `yarn upgrade` fix the trick for an other project.

**Comment by mklopets** [comment]
I'm actually using this with Node 10 in multiple projects, so this issue should be invalid at this point.
