### ISSUE TITLE
Setting default languages

### ISSUE THREAD

**Issue by vaz9** [alex3165/react-mapbox-gl#593]
Hi, how set languages to map?

**Comment by valjusha** [comment]
No one knows?

**Comment by Wykks** [comment]
Use `setLayoutProperty` (the layer must contains the language)
For example: https://www.mapbox.com/mapbox-gl-js/example/language-switch/

**Comment by vaz9** [comment]
well and how do I do this?

I have a plugin:

```
import FactoryReactMapboxGl from 'react-mapbox-gl';

export default class MapBoxHelper extends React.Component<IMapBoxHelperProps, {}> {
    MapboxGl;

    constructor(props) {
        super(props);

        this.MapboxGl = FactoryReactMapboxGl(this.factoryProps);

        // don't working
        this.MapboxGl.addControl(new MapboxLanguage({
            defaultLanguage: 'ru',
        }));

        // don't working too
        this.MapboxGl.setLayoutProperty(
            'country-label-lg',
            'text-field',
            ['get', 'name_ru']
        );
    }
}
```

I do not understand what I'm doing wrong = (

**Comment by mklopets** [comment]
From [docs/API.md](https://github.com/alex3165/react-mapbox-gl/blob/master/docs/API.md):
>To use the original Mapbox API use the onStyleLoad property. The callback function will receive the map object as a first argument, then you can add your own logic alongside react-mapbox-gl. mapbox gl API.

The factory function returns the react-mapbox-gl map component, but not the mapbox-gl Map instance.

**Comment by dearamerican** [comment]
Hi @vaz9 @Wykks @mklopets anyone have a working solution to this? I have tried both the avenues proposed [here](https://github.com/alex3165/react-mapbox-gl/blob/master/docs/API.md#using-the-original-mapbox-api) for working with the original mapbox API, and followed docs [here](https://docs.mapbox.com/mapbox-gl-js/example/language-switch/) for implementation; I've also tried [Mapbox GL Language plugin](https://blog.mapbox.com/how-to-localize-your-maps-in-mapbox-gl-js-da4cc6749f47). Nothing I've tried seems to work. Any tips would be super appreciated!

Specifically, I need to dynamically set the map language react-mapbox-gl. 

Thank you!
