### ISSUE TITLE
Map gets stuck on mouse moving

### ISSUE THREAD

**Issue by ScriptArtist** [alex3165/react-mapbox-gl#594]
On map moving some times its stuck. After release and click again its continue moving.
it happens randomly with a probability of 1/10
Console is empty. 
Reproduced on demo page too.

![ezgif-2-f05fe8cefa](https://user-images.githubusercontent.com/30506483/40326043-960f435c-5d46-11e8-84c1-a3a956577ddd.gif)

**Comment by ScriptArtist** [comment]
Found reason. It happened after upgrade to mapbox-gl 0.44
https://github.com/alex3165/react-mapbox-gl/commit/4eaf7bb416e93ce6926d61829944030aeeeca060

**Comment by mklopets** [comment]
Cannot reproduce.
