### ISSUE TITLE
Color and size by with thousands of data points

### ISSUE THREAD

**Issue by caldwellweb** [alex3165/react-mapbox-gl#597]
Not an issue but a question about how to accomplish color/size by with this map. The images below of what I'm after are from mapbox.

![screen shot 2018-06-07 at 8 11 51 am](https://user-images.githubusercontent.com/20992883/41101922-26ebab2c-6a2b-11e8-8f39-19d04030becb.png)

![screen shot 2018-06-07 at 8 12 15 am](https://user-images.githubusercontent.com/20992883/41101927-282fc220-6a2b-11e8-8b71-b929b8a6f2c6.png)

**Comment by rlueder** [comment]
Take a look at [Mapbox Expressions](https://www.mapbox.com/mapbox-gl-js/style-spec/#expressions) docs and here's a basic example of how you'd implement using a GeoJSONLayer component (assuming the circles above are based on a property "year"):

```
<GeoJSONLayer
    data={data}
    id="circles"
    circlePaint={{
        "circle-color": [
            "match",
            ["get", "year"],
            "2018",
            "#a09fbc",
            "2017",
            "#a98190",
            "2016",
            "#76b3bd",
            "#000" // default color, must be set
        ],
        "circle-radius": 4
    }}
/>
```

**Comment by mklopets** [comment]
Yep, expressions and [mapbox-gl functions](https://www.mapbox.com/mapbox-gl-js/style-spec/#other-function) should match your needs.
