### ISSUE TITLE
Centering an HTML marker

### ISSUE THREAD

**Issue by aratcliffe** [alex3165/react-mapbox-gl#600]
Hi, I have a simple HTML marker that should be positioned relative to the center of the marker div.

The marker div is styled like this:

````
const markerStyle = {
  color: '#fff',
  backgroundColor: '#2a9aeb',
  borderRadius: '50%',
  border: '2px solid #fff',
  boxShadow: '0 3px 14px rgba(0,0,0,0.4)',
  width: 20,
  height: 20,
  textAlign: 'center'
};
````
I know this should be simple but I cannot get it correctly positioned. I've tried both setting negative margins in the div style as well as using the Marker offset property but neither works.

How can I do this?

**Comment by aratcliffe** [comment]
Setting a negative margin-bottom value half the marker height achieves this.

**Comment by aratcliffe** [comment]
There is a better solution. Although undocumented, specifying "center" for the marker `anchor` prop works.

**Comment by mklopets** [comment]
Documented the `center` value in 3cb4bdf7c85141ea089eaf2bcc3cc27b8d8c82f3
