### ISSUE TITLE
how get MapboxGl method? ReactMapboxGl

### ISSUE THREAD

**Issue by valjusha** [alex3165/react-mapbox-gl#605]
Hi, i use `ReactMapboxGl`:

```
import FactoryReactMapboxGl from 'react-mapbox-gl';
import { FactoryParameters } from 'react-mapbox-gl/lib/map';

class extends React.Component<FactoryParameters, {}> {
    constructor(props) {
        super(props);

        this.MapboxGl = FactoryReactMapboxGl(this.factoryProps);

       this.MapBoxGl.addControl({ ... }) // Error !!!
    }

   get factoryProps(): FactoryParameters {
        return this.props;
   }
}
```

How get map from mapboxGl? Then added Languages Control?
Many thanks

**Comment by chayanbhaisare** [comment]
you'll have to use onStyleLoad callback of react-mapbox-gl.
` <Mapbox`
       `   style={defaultStyle}`
        `  containerStyle={defaultContainerStyle}`
       `   onStyleLoad={this.mapDidLoad}`
      `    maxZoom={maxZoom}`
      `    maxBounds={defaultBounds}`
     `   >`
     `     {layers}`
      `    {sources}`
     `   </Mapbox>`
` mapDidLoad(mapbox) {`
          // add navigation control
`       mapbox.addControl(new MapboxGL.NavigationControl(), 'top-left');`
`}`

You can also add a custom navigation control on map - https://www.mapbox.com/mapbox-gl-js/api/#icontrol

**Comment by mklopets** [comment]
@chayanbhaisare is correct, you can use the `onStyleLoad` callback that is called with the map instance when the map is ready.

```
import * as React from 'react';
import FactoryReactMapboxGl from 'react-mapbox-gl';

const Map = FactoryReactMapboxGl({
  accessToken: '<your token>',
});

class extends React.Component {
  onMapLoad = (map: any) => {
    map.addControl({ ... });
  };

  render() {
    return (
      <Map
        onStyleLoad={this.onMapLoad}
        style='<your style url>'
      />
    );
  }
}
```

For language switching, see https://www.mapbox.com/mapbox-gl-js/example/language-switch/.
