### ISSUE TITLE
Popup implementation uses ReactDOM.render for children, loosing Context

### ISSUE THREAD

**Issue by kmamykin** [alex3165/react-mapbox-gl#61]
The popup component I am implementing requires access to React context objects, and therefore must be rendered as children of the component that provides the context. The Popup component uses ReactDOM.render to render children into a div outside of the app hierarchy, and the popup children receive no context.

Is there a way to may be use [MapboxGL.Popup.setDOMContent](https://www.mapbox.com/mapbox-gl-js/api/#Popup#setDOMContent) together with using React's ref?

There are other issues related to the Marker/Popup components, is it something you may address in the near future?

**Comment by philpl** [comment]
There is no direct way to solve it and we chose the easy way out.

React with its refs doesn't work since the Virtual DOM has to take all ownership of the node. We can't attach it somewhere else and just hope for the best, unfortunately.

There might be smarter solutions, where we mock the DOM api to get around this limitation.

**Comment by kmamykin** [comment]
Shit.

I think the solution may be to re-implement [mapbox's popup](https://github.com/mapbox/mapbox-gl-js/blob/master/js/ui/popup.js) functionality in pure React. It looks like the popup is reacting to map's 'move' event, then projects popup's latlng on the map, and calculates the offset/position and transforms.

**Comment by philpl** [comment]
@kmamykin Good point! Getting rid of what's broken, instead of fixing it ;)

**Comment by kmamykin** [comment]
I am working on it.

**Comment by philpl** [comment]
@kmamykin Cheers! Just ping us if you need any more help for it. Really stoked to see this being picked up by you :)

**Comment by alex3165** [comment]
Ready for review https://github.com/alex3165/react-mapbox-gl/pull/74

**Comment by alex3165** [comment]
The PR has been merged and published, see https://github.com/alex3165/react-mapbox-gl/releases/tag/v0.19.0
