### ISSUE TITLE
Can't run examples

### ISSUE THREAD

**Issue by singingwolfboy** [alex3165/react-mapbox-gl#614]
I just tried to clone the repository and run the examples, and I'm getting a webpack error. [Traceback is in a gist here.](https://gist.github.com/singingwolfboy/87bf49c486bd57c6bb342ba91d25cfa8) Can you take a look?

**Comment by singingwolfboy** [comment]
No, even after I `npm install` in the root of the repository, I get the same error. Are you able to reproduce that?

**Comment by mklopets** [comment]
Think I found the problem: the main module of the project's package.json is `lib/index.js` which is built from the TypeScript source. After a fresh clone and install, the compiled JS file doesn't exist.

Run `npm run-script build` at the root and that should (I swear this time) fix it.

**Comment by singingwolfboy** [comment]
Yes! That works. However, I had to inspect the `dev.server.js` file to figure out that I needed to visit port 3001 to actually _view_ the examples. It seems like this workflow needs some more documentation. What's the best place to put that documentation?

**Comment by cdesch** [comment]
How does this work again? I'm running into the same issue. To run the demos I need to:

- run `npm install` in the repo root
- run `npm run-script build` in the repo root
- run `npm start` in `/examples`

Is this correct?

**Comment by cdesch** [comment]
I got it to work through some fiddling, deleting, installing...etc. 

So, the process should be?

- run `npm install` in the repo root
- run `npm run-script build` in the repo root
- run `npm install` in `/examples`
- run `npm start` in `/examples`

**Comment by mklopets** [comment]
Yes, that looks right

**Comment by jasonlbw** [comment]
> I got it to work through some fiddling, deleting, installing...etc.
> 
> So, the process should be?
> 
> * run `npm install` in the repo root
> * run `npm run-script build` in the repo root
> * run `npm install` in `/examples`
> * run `npm start` in `/examples`

i got an error:

ERROR in /.../react-mapbox-gl/example/src/demos/htmlCluster.tsx
./src/demos/htmlCluster.tsx
[tsl] ERROR in /.../react-mapbox-gl/example/src/demos/htmlCluster.tsx(80,7)
      TS2322: Type 'React.CSSProperties' is not assignable to type 'import("/.../react-mapbox-gl/node_modules/@types/react/index").CSSProperties'.
  Types of property 'outlineStyle' are incompatible.
    Type 'string | undefined' is not assignable to type '"hidden" | "none" | "inherit" | "-moz-initial" | "initial" | "revert" | "unset" | "dashed" | "dotted" | "double" | "groove" | "inset" | "outset" | "ridge" | "solid" | "auto" | undefined'.
      Type 'string' is not assignable to type '"hidden" | "none" | "inherit" | "-moz-initial" | "initial" | "revert" | "unset" | "dashed" | "dotted" | "double" | "groove" | "inset" | "outset" | "ridge" | "solid" | "auto" | undefined'.

ERROR in /.../react-mapbox-gl/example/src/demos/htmlCluster.tsx
./src/demos/htmlCluster.tsx
[tsl] ERROR in /.../react-mapbox-gl/example/src/demos/htmlCluster.tsx(131,15)
      TS2322: Type 'React.CSSProperties' is not assignable to type 'import("/.../react-mapbox-gl/node_modules/@types/react/index").CSSProperties'.
