### ISSUE TITLE
trackResize: true wrecks window resize performance

### ISSUE THREAD

**Issue by ScottDikowitz** [alex3165/react-mapbox-gl#630]
trackResize causes window resize to be really janky, even when it doesn't have to resize the map. I think there's a lot of room for improvement in the performance there.

**Comment by daniel-hauser** [comment]
The `trackResize` options it sent to `mapbox-gl-js` that handles the resizing of the map.

You can open an issue in the [`mapbox-gl-js` repo](https://github.com/mapbox/mapbox-gl-js/issues) if still relevant
