### ISSUE TITLE
Background Pattern in LinePaint

### ISSUE THREAD

**Issue by ikosar** [alex3165/react-mapbox-gl#632]
const linePaint = MapboxGL.LinePaint = {
            'line-color': '#EF6C00',
            'line-width': 5
        };
Hi guys, i use this code and this is work fine , but i want to add bg pattern to line .
Example Please.

**Comment by ikosar** [comment]
Can you give an example?

**Comment by mklopets** [comment]
This is a mapbox-gl question, not react-mapbox-gl specific. Please refer to their docs and/or issues.
