### ISSUE TITLE
How to highlight line in <GeoJSONLayer/>

### ISSUE THREAD

**Issue by suyesh** [alex3165/react-mapbox-gl#634]
I have this code, Lines are drawn. But I want to highlight a line when hovered or clicked. 

```
        {Object.keys(this.props.pavements).length > 0 && (
          <GeoJSONLayer
            data={this.props.pavements}
            linePaint={{
              'line-color': ['get', 'color'],
              'line-width': 10,
            }}
            lineLayout={{
              'line-cap': 'round',
            }}
            lineOnClick={e => this.populateInfobox(e)}
            lineOnMouseEnter={e => this.populateInfobox(e)}
          />
        )}
```

What can I do in lineOnClick to change the color of the clicked line?

**Comment by ikosar** [comment]
+1

**Comment by suyesh** [comment]
I did it by saving the color property of GeoJson in redux and changing the color of the selected feature

**Comment by mklopets** [comment]
I assume this can then be considered closed.

**Comment by rlueder** [comment]
The "Mapbox" way of doing this would be to use ``setFeatureState`` but that's not possible at the moment, see https://github.com/alex3165/react-mapbox-gl/issues/652
