### ISSUE TITLE
How to implement onClick Popup's on markers? 

### ISSUE THREAD

**Issue by Kolhar730** [alex3165/react-mapbox-gl#636]
I've placed a Popup component inside of a Marker and now I'd like to trigger the popup whenever I click the marker. Could I get some help in knowing how it is done and I also have a hard time using the offset parameter as well. 

Any help is appreciated. Thank you.

**Comment by Kolhar730** [comment]
@mklopets I want to recreate something like this example [here](https://www.mapbox.com/help/custom-markers-gl-js/) and so I needed some help regarding the same.

**Comment by mklopets** [comment]
Not sure what you specifically need help with. You can use app state to figure out whether or not to display a `<Popup>` component.
