### ISSUE TITLE
Expose Mapbox's native clustering in favor of Marker clustering

### ISSUE THREAD

**Issue by tstirrat15** [alex3165/react-mapbox-gl#638]
Mapbox now has [native clustering](https://www.mapbox.com/mapbox-gl-js/example/cluster/), which means that it should be possible for the clustering in this library to take advantage of that rather than reimplementing it using supercluster.

This is a feature that I'll want in the future, and I'm happy to put in some work on it, but I wanted to open an issue first to discuss.

Should it supersede the existing API, or should it be in addition to the existing API?

**Comment by Wykks** [comment]
It's not new at all.
The difference between native clustering and the clustering implemented in react-mapbox-gl using supercluster is that you can use react component with the latter.

You totally can use native clustering today. As long as you do not need html inside your markers.

We can add a note to the docs about that

**Comment by tstirrat15** [comment]
Ah, makes sense. Thank you for clarifying.
