### ISSUE TITLE
How to set zoom to default after jumpTo ?

### ISSUE THREAD

**Issue by abraztsov** [alex3165/react-mapbox-gl#647]
In docs https://www.mapbox.com/mapbox-gl-js/api/#map#jumpto `jumpTo` has options where you can set `zoom` that will be applied after jump to location. How to do it in this lib?

After setting new `center` zoom doesn't changes to initial value.

I tried this as initial options on `Map`component.
```
jumpTo: {
    zoom: [9]
},
flyTo: {
    zoom: [9]
}
```

**Comment by rlueder** [comment]
Setting `jumpTo` and `flyTo` as initial options won't work as you expect, you should fire those events already with the options you want, in this case the zoom level, for example:

```
circleOnClick={e => {
    map.flyTo({
        center: e.features[0].geometry.coordinates,
        zoom: [9]
    });
}}
```

**Comment by mklopets** [comment]
@rlueder's answer should help.
