### ISSUE TITLE
Store coordinates onClick Event: Cannot read property 'setState' of undefined

### ISSUE THREAD

**Issue by iizMerk** [alex3165/react-mapbox-gl#648]
in the console.log(evt.lngLat) i had the output why i can store it?

    _onClickMap(map, evt) {
        console.log(evt.lngLat);
        this.setState({coordinates: this.evt.lngLat});
      }

    
      
    render () {
        return(
            <div>
               <AuthStatus/>
                <MapContainer>
                    <Map
                    style="mapbox://styles/mapbox/streets-v9"
                    containerStyle={{ height: "50vh",  width: "50vw"}}
                    onClick={this._onClickMap}>
                    </Map>
                </MapContainer>
                {this.state.coordinates}
            </div>
        ) 
    }

**Comment by mklopets** [comment]
Doesn't look like a react-mapbox-gl issue but a generic JS/React one. `this` does not refer to your class instance any more when called by third parties.

Either bind the `_onClickMap` method in the constructor of the class:
```
constructor(props) {
  super(props);
  this._onClickMap = this.onClickMap.bind(this);
}
```

or use arrow functions as class properties to avoid the binding (better style-wise but I believe it's considerably worse performance-wise):

```
class SomeClass extends React.Component {
  _onClickMap = (map, evt) => {
     console.log(evt.lngLat);
     this.setState({coordinates: this.evt.lngLat});
  }
  
  render() {
    return <whatever>
  }
{
