### ISSUE TITLE
Cannot Read map of Undefined 

### ISSUE THREAD

**Issue by iizMerk** [alex3165/react-mapbox-gl#650]
I have a Collection of Data from Firestore and it contains all the coordinates.
How i can show all Positions?

`const MapBox = ({posts} , props) => {
      
    const thisMarker = () => {
        return(
            <Marker
                key={posts.id}
                coordinates={[posts.lat,posts.lng]}
                style={styles.clusterMarker}
            ></Marker>
        )
    }
        return(
            <div>
               <AuthStatus/>
                <MapContainer>
                    <Map
                    style="mapbox://styles/mapbox/streets-v8"
                    containerStyle={{ height: "20vh",  width: "400px"}}
                    >
                    <Cluster ClusterMarkerFactory={thisMarker}>
                        {posts.map((post) => {
                            return( <Marker
                            key={post.id}
                            style={styles.marker}
                            coordinates={[post.lat,post.lng]}
                            >
                            <div title={post.title}>
                                {post.title.name[0]}
                            </div>
                            </Marker>)
                        })}
                    </Cluster>
                    </Map>
                </MapContainer>
                
            </div>
        ) 
}

export default MapBox`

**Comment by rlueder** [comment]
This seems to be an issue with how your component is set up and not specific to react-mapbox-gl, add a guard or a loading state to your component until data is available to be rendered, the error message you're getting is a good hint, "posts" is not available for React to render it.

**Comment by wisyr** [comment]
You've probably mistaken map (function which belongs to `Array` prototype) with Map (react-mapbox-gl component). Solution you are looking for may look like: `Array.isArray(posts) && posts.map({ ... });`.

**Comment by mklopets** [comment]
This doesn't seem to be a react-mapbox-gl issue.
