### ISSUE TITLE
Export MapContext to support custom controls 

### ISSUE THREAD

**Issue by daniel-hauser** [alex3165/react-mapbox-gl#654]
Using the new context API added in #619, the only way for a custom component to get the mapbox map instance is to get the `Map` ref, then extract the map from the state.

Using `MapContext.Consumer` (or alternatively, `withMap`) will make the code of custom controllers better.

**Comment by amaurymartiny** [comment]
I believe this can be closed?

**Comment by mklopets** [comment]
Released this in [v4.4.0](https://github.com/alex3165/react-mapbox-gl/releases/tag/v4.4.0)
