### ISSUE TITLE
Set Feature active state onClick

### ISSUE THREAD

**Issue by wellnine** [alex3165/react-mapbox-gl#656]
Hi guys. Thanks for your awesome work.

Is there exist a possibility to change the custom Feature active state? 

Eg. I want to change the Icon when I'm clicking on it or programmatic way - slick on some button with the Feature ID and highlight it by settiag status = Active.

Thanks for any help.

**Comment by daniel-hauser** [comment]
Use a paint expression that uses [`feature-state`](https://www.mapbox.com/mapbox-gl-js/style-spec#expressions-feature-state).
The state can be set with [`map.setFeatureState`](https://www.mapbox.com/mapbox-gl-js/api#map#setfeaturestate).

**Comment by lkleuver** [comment]
might be wrong but the makeFeature in layer.ts puts the id in the feature properties, it seems that mapbox looks in feature.id instead of feature.properties.id ?

**Comment by daniel-hauser** [comment]
You can set [`generateId`](https://www.mapbox.com/mapbox-gl-js/style-spec/#sources-geojson-generateId) in the `sourceOptions`

**Comment by lkleuver** [comment]
totally missed that! took some digging in the mapbox docs. 
for reference:
`          <Layer
            geoJSONSourceOptions={{
              generateId: true
            }}>`
Thanks!

**Comment by jedifunk** [comment]
`generateId` does not work. id still shows as undefined
