### ISSUE TITLE
Change icon-color in symbolLayout with GeoJSONLayer

### ISSUE THREAD

**Issue by matsomo** [alex3165/react-mapbox-gl#667]
I'm trying to color a marker and at the same time have a corresponding text in a different color beneath the marker.

I can't get the icon-color property to work when using icon-image. I tried creating the marker with plain text, but I can't figure out how to change only a part of a string using data-driven styling.
See example: https://stackblitz.com/edit/react-shs5l2

Creating multiple layers seems to only generate the layer that was added last.

Any ideas on how this can be done? 
Thanks!

**Comment by daniel-hauser** [comment]
The `icon-color` paint property can be used to color [`sdf`](https://blog.mapbox.com/drawing-text-with-signed-distance-fields-in-mapbox-gl-b0933af6f817) icons only

> **`icon-color`**
> _Paint property. Optional color. Defaults to "#000000". Requires icon-image. Transitionable._
> The color of the icon. This can only be used with sdf icons.
> ([Source](https://www.mapbox.com/mapbox-gl-js/style-spec#paint-symbol-icon-color))
