### ISSUE TITLE
Changelog / documentation for version 4.0?

### ISSUE THREAD

**Issue by benrudolph** [alex3165/react-mapbox-gl#668]
Great to see that 4.0 was published and excited to upgrade to it. Is there an updated Changelog or documentation I can view? Or is that still in works?

**Comment by mklopets** [comment]
Honestly, the docs are still somewhat out of date. The main thing in v4 was the new usage of React context (see https://github.com/alex3165/react-mapbox-gl/pull/619). There's a short changelog: https://github.com/alex3165/react-mapbox-gl/releases/tag/v4.0.0

Keeping this open as we do need to take another look at the docs.

**Comment by mklopets** [comment]
Updated the [docs](https://github.com/alex3165/react-mapbox-gl/blob/master/docs/API.md) a bit, including about the context API.

**Comment by benrudolph** [comment]
Thanks
