### ISSUE TITLE
Master is broken

### ISSUE THREAD

**Issue by AbrahamArun** [alex3165/react-mapbox-gl#67]
On `npm install`, I get the below error.

<img width="542" alt="screen shot 2016-11-14 at 9 26 52 pm" src="https://cloud.githubusercontent.com/assets/5391059/20271212/1205bb80-aab0-11e6-9703-0d37f71080a0.png">

**Comment by philpl** [comment]
We've just updated the library to use Mapbox GL JS 0.27, which was released 3 days ago.
Please make sure that your cache / proxy / etc is up to date. ;)

- https://github.com/mapbox/mapbox-gl-js/releases/tag/v0.27.0
- https://www.npmjs.com/package/mapbox-gl
