### ISSUE TITLE
Don't pin peerDependencies

### ISSUE THREAD

**Issue by pixelass** [alex3165/react-mapbox-gl#670]
AFAIK `peerDependencies` should not be pinned.

**Why?**

I get warnings for `peerDependencies` (My versions are compatible [semver] but later releases). While it's fully ok to pin `dependecies` and `devDependencies` to ensure a stable build and release, `peerDependecies` should not force exact versions.

```bash
warning "workspace-aggregator-8ff153bc-bc61-4fd3-b3af-d3d822314b14 > website > react-mapbox-gl@4.0.2" has incorrect peer dependency "mapbox-gl@0.51.0".
warning "workspace-aggregator-8ff153bc-bc61-4fd3-b3af-d3d822314b14 > website > react-mapbox-gl@4.0.2" has unmet peer dependency "prop-types@15.6.2".
warning "workspace-aggregator-8ff153bc-bc61-4fd3-b3af-d3d822314b14 > website > react-mapbox-gl@4.0.2" has incorrect peer dependency "react@16.5.2".
warning "workspace-aggregator-8ff153bc-bc61-4fd3-b3af-d3d822314b14 > website > react-mapbox-gl@4.0.2" has incorrect peer dependency "react-dom@16.5.2".
```

**Suggested changes:**

https://github.com/alex3165/react-mapbox-gl/blob/master/package.json#L70-L75

**Before:**

```json
{
  "peerDependencies": {
    "mapbox-gl": "0.51.0",
    "prop-types": "15.6.2",
    "react": "16.5.2",
    "react-dom": "16.5.2"
  }
}
```

**After:**

```json
{
  "peerDependencies": {
    "mapbox-gl": "^0.51.0",
    "prop-types": "^15.6.2",
    "react": "^16.5.2",
    "react-dom": "^16.5.2"
  }
}
```

**Comment by pixelass** [comment]
> One piece of advice: peer dependency requirements, unlike those for regular dependencies, should be lenient. You should not lock your peer dependencies down to specific patch versions. It would be really annoying if one Chai plugin peer-depended on Chai 1.4.1, while another depended on Chai 1.5.0, simply because the authors were lazy and didn't spend the time figuring out the actual minimum version of Chai they are compatible with.

[Source: nodejs.org/](https://nodejs.org/en/blog/npm/peer-dependencies/)

**Comment by mklopets** [comment]
Makes sense. Mind creating a PR?
