### ISSUE TITLE
zoomTo isn't available in react-mapbox

### ISSUE THREAD

**Issue by Adeeljavedvirk** [alex3165/react-mapbox-gl#674]
https://www.mapbox.com/mapbox-gl-js/example/change-building-color-based-on-zoom-level/

Want to achieve this but zoomTo function isn't available in react mapbox. How can i achieve this in react?

**Comment by daniel-hauser** [comment]
You can change the zoom level by changing the `zoom` prop of the <Map> component.
Regarding the zoom duration of the animation, I think you can pass an `animationOptions`

**Comment by daniel-hauser** [comment]
Closing the issue, the question was answered
