### ISSUE TITLE
Working with LocationIQ maps?

### ISSUE THREAD

**Issue by brianhilst** [alex3165/react-mapbox-gl#677]
I am trying to use map tiles from Locactioniq.com, but not sure what to set as the apiURL when creating the map?  Here is the URL they show in their documentation for using MapBoxGL: https://{s}-tiles.locationiq.org/v2/obk/r/{z}/{x}/{y}.png?key={Your_Access_Token}

They also point to this as an example:  https://tiles.unwiredmaps.com/v2/samples/

If you know anything about this, I would appreciate the information.
Thanks!

**Comment by daniel-hauser** [comment]
I looked in the examples you attached.
looks like you don't need to add the URL, just use  `unwired.getLayer("streets")` as the `style` prop of the `<Map>` component

```jsx-harmony
<Map style={unwired.getLayer("streets")} />
```

**Comment by mklopets** [comment]
@daniel-hauser's reply seems correct, though I haven't used LocationIQ myself. Closing this as there's been no reply for a long time, assuming & hoping you got it sorted.
