### ISSUE TITLE
Example's webpack dependencies are out of date

### ISSUE THREAD

**Issue by AbrahamArun** [alex3165/react-mapbox-gl#68]
**Installation of deps:** `cd/example && npm install`

<img width="867" alt="screen shot 2016-11-14 at 11 28 46 pm" src="https://cloud.githubusercontent.com/assets/5391059/20276132/0aa66e82-aac1-11e6-8736-5a24644ea6fb.png">

**And on running `npm run start`**

<img width="909" alt="screen shot 2016-11-14 at 11 29 29 pm" src="https://cloud.githubusercontent.com/assets/5391059/20276160/2780a108-aac1-11e6-8508-49c4f7fe088c.png">

**Comment by philpl** [comment]
Try installing a newer version of webpack, that is at least version `2.1.0-beta.26`, since that's the peer dependency that the `webpack-dev-server` seems to need.

It might be necessary for us to update some dependencies and configs there, @alex3165.

**Comment by alex3165** [comment]
Fixed with this commit : https://github.com/alex3165/react-mapbox-gl/commit/63d5a0c5f4fe8a22e7587cbd9a91923a4621dfcb
