### ISSUE TITLE
how can i make custom components?

### ISSUE THREAD

**Issue by ilomon10** [alex3165/react-mapbox-gl#681]
i tried this code ([from this example](https://github.com/alex3165/react-mapbox-gl/issues/106#issuecomment-273717046)) but i cant get Map instance
```
import MapboxDraw from '@mapbox/mapbox-gl-draw';
import React from 'react';

export default class DrawControl extends React.Component {
  static contextTypes = {
    map: PropTypes.object,
  };

  componentWillMount() {
    const { map } = this.context;
    const Draw = new MapboxDraw();
    map.addControl(Draw);
  }

  render() {
    return null;
  }
}
```
any best practice please?

**Comment by daniel-hauser** [comment]
You need to have the `<DrawControl>` component as a child of your `<Map>` component is you want to get `map` from the react context

**Comment by daniel-hauser** [comment]
@ilomon10 - If the custom component you want to create is the `<DrawControl>`, you can use [`react-mapbox-gl-draw`](https://github.com/amaurymartiny/react-mapbox-gl-draw) insted
