### ISSUE TITLE
Usage as country/major city picker

### ISSUE THREAD

**Issue by bonbonio** [alex3165/react-mapbox-gl#687]
Hi,

Is there an example of overlaying this with the countries of the world, so that each one can be clicked (like an old fashioned image map) and then as you zoom I have thousands of cities to mark on the map using latlng coords.

The first feature must have been done already, but the second I am sure is possible with info from the docs.

Many thanks

**Comment by mklopets** [comment]
This question is better suited for StackOverflow. You can draw the outlines of countries using GeoJSON polygons, add click handlers to them and have a symbol layer to render icons over cities.
