### ISSUE TITLE
Recommended way to accessing mapbox API based on Redux state change?

### ISSUE THREAD

**Issue by Altiano** [alex3165/react-mapbox-gl#69]
My map responds to input that filter the layer. So for example when user type `foo` on another component, only features that have property bar with value foo will be shown.

Right now, to achieve that, I use `componentWillReceiveProps` for making the update after assigning `this.map` to `map` from `onStyleLoad`.

The code for `componentWillReceiveProps`:

    componentWillReceiveProps = (nextProps) => {
      const { mapFilter } = nextProps

      if (this.map && mapFilter) {
        const map = this.map
        map.setFilter('jb-business', ['==', 'bar', mapFilter])
      }
    }

Is there any better way?

**Comment by alex3165** [comment]
Hey @Altiano , thanks for reporting this issue. I think it can be handled nicely by the layer component, I have done some changes to the layer so that you can do something like this :
```
<Layer
  type="symbol"
  id="marker"
  filter=['==', 'bar', mapFilter]
  layout={{ "icon-image": "marker-15" }}>
</Layer>
```
Can you use this branch on your project and tell me if this solve your problem nicely ? https://github.com/alex3165/react-mapbox-gl/tree/feature/layer-filter.

**Comment by Altiano** [comment]
Sorry, I forgot to mention that the layer is not created in react but directly from mapbox (there are certain benefits that I need). 

But, I'll consider switching to manual code now that there is an additional `filter` property.

I'm just wondering, How about add another component to the API, something like `<ExistingLayer />` so that I can manipulate a layer that has been created directly from mapbox. Just an idea.

**Comment by alex3165** [comment]
Sorry for the late reply, I will have a look at the problem as soon as I have some time 👍, I need to investigate more to make sure there is a really need for an `<ExistingLayer />` component.

**Comment by philpl** [comment]
@Altiano What benefits do you get from creating a layer manually? I don't really see why you'd need it. 😕 

You can pass any kind of options to the `Layer` component via the `layerOptions` prop. You can also create a custom source and pass its `sourceId` if you need to. Is there anything I'm missing here? I don't really see why you'd need it to behave in any different way?

Even if you need more control over the features, that are being rendered onto a layer, you could just pass those as usual with the `Feature` sub-component and manipulate those?

**Comment by philpl** [comment]
I'll close this due to inactivity
