### ISSUE TITLE
Question: Is it possible to add 3d model to a map using three.js?

### ISSUE THREAD

**Issue by galleon** [alex3165/react-mapbox-gl#698]
Hello,

Is it possible to add a model following this example: https://bl.ocks.org/ryanbaumann/b9725e79b5b1742d92ada00ddbf5c3d3

**Comment by galleon** [comment]
Would that be possible to add a Layer based on ThreeBox?
I am new to react-mapbox-gl and would require guidance to do it ;-)

**Comment by mklopets** [comment]
Technically you can do everything possible with vanilla mapbox-gl with react-mapbox-gl. The official mapbox-gl docs have an example of using three.js: https://docs.mapbox.com/mapbox-gl-js/example/add-3d-model/

Unfortunately, I don't have personal experience with this and react-mapbox-gl doesn't have any specific support for this right now. If you believe something is missing, please feel free to create another issue for that.
