### ISSUE TITLE
fitBounds property is type [[number, number], [number, number]]

### ISSUE THREAD

**Issue by OliverEhrhardt** [alex3165/react-mapbox-gl#704]
In the documentation it states that fitBounds is of type number[][]. Source code indicates that it is of type [[number, number], [number, number]]. I'm trying to use this property as outlined in this:

[https://docs.mapbox.com/mapbox-gl-js/example/zoomto-linestring/](https://docs.mapbox.com/mapbox-gl-js/example/zoomto-linestring/)

Right now I'm calculating the bounding box myself but I'm getting unpredictable behavior and it will fly to a bounding box near the line string and then snap to the correct bounding box once the flying animation is done. 

If you know of a better solution for zooming onto a line string generated by a GeoJSONLayer it would be much appreciated!

**Comment by mklopets** [comment]
Will take a look at the type doc, but did you resolve your issue with the weird jump? If not, do you have repro code? I haven't seen something like this myself.

**Comment by mklopets** [comment]
Fixed the docs, thanks.

**Comment by mklopets** [comment]
Closing as stale
