### ISSUE TITLE
Cluster performance

### ISSUE THREAD

**Issue by akiirii** [alex3165/react-mapbox-gl#719]
When you need to render thousands of marker Cluster performance is quite low.

Current implementation can't handle that amount of markers which is required for clustering  (It don't work with Layers and features)

That means that current version of clustering is not really usable, because generally you need that to don't be crushed amount of points

It is way to use cluster with layer/source etc? Or increase performance?

**Comment by Wykks** [comment]
Yes, the recommended way to cluster is with layer / source : https://docs.mapbox.com/mapbox-gl-js/example/cluster/

Cluster with markers should be used only if you **absolutly** need HTML markers.

(You can also combine both tech, with thresholds)
