### ISSUE TITLE
Dynamically set value for "scrollZoom"

### ISSUE THREAD

**Issue by sahilvicesoftware** [alex3165/react-mapbox-gl#724]

**Comment by mklopets** [comment]
This would be a feature request for [mapbox-gl](https://github.com/mapbox/mapbox-gl-js), not this wrapper library. See [their docs](https://docs.mapbox.com/mapbox-gl-js/api/#map), `scrollZoom` is an option you must set when initializing mapbox-gl.

**Comment by sahilvicesoftware** [comment]
> This would be a feature request for [mapbox-gl](https://github.com/mapbox/mapbox-gl-js), not this wrapper library. See [their docs](https://docs.mapbox.com/mapbox-gl-js/api/#map), `scrollZoom` is an option you must set when initializing mapbox-gl.

@mklopets We can set it on initialize but i want to change its value dynamically after initialization

**Comment by mklopets** [comment]
Yes, and AFAIK, mapbox-gl doesn't allow for that (correct me if I'm wrong), so they're the ones who would have to implement it (most likely by adding a method) on their map object.

**Comment by mklopets** [comment]
Actually, sorry, I was wrong, they do allow for it. `map.scrollZoom.enable` and `map.scrollZoom.disable` should do the trick: https://docs.mapbox.com/mapbox-gl-js/api/#scrollzoomhandler

**Comment by sahilvicesoftware** [comment]
> Actually, sorry, I was wrong, they do allow for it. `map.scrollZoom.enable()` and `map.scrollZoom.disable()` should do the trick: https://docs.mapbox.com/mapbox-gl-js/api/#scrollzoomhandler

@mklopets Is this supported by this wrapper?

**Comment by mklopets** [comment]
Yes, you can do everything that mapbox-gl-js supports, because we expose the mapbox `Map` object.

See https://github.com/alex3165/react-mapbox-gl/issues/605 or our docs
