### ISSUE TITLE
Click on Popup trigger on map click event

### ISSUE THREAD

**Issue by akiirii** [alex3165/react-mapbox-gl#725]
Last update 4.3.0 (probably "Fixed mouse events on Marker and Cluster elements") occurred problem with popups, because click on Popup trigger on map click event, also it is possible to drag map by clicking on popup

It is really problematic when you fire hide popup action after clicking on map. 

In previous library version everything is ok.

**Comment by mklopets** [comment]
I'm not sure what the "correct" behaviour would be here. I suppose the popup click handler's stopPropagation should stop propagation to the map – not sure why it's not the case right now.

One option to solve your problem in the meanwhile would be to change your code that closes the popup. Inside the click handler, add an extra check:
```
map.on('click', (e) => {
  const { target } = e.originalEvent;
  const canvas = map.getCanvas();
  const shouldClosePopup = target === canvas;
  console.log('shouldClosePopup', shouldClosePopup);
});
```

`shouldClosePopup` will be false if the original mouse event's target was something else, e.g a popover.

**Comment by akiirii** [comment]
yeah, but it is only kind of work around, and also don't fix all of problems.
It is not only click, but also hover and drag, if you try copy text you actually drag map, cursor doesn't change etc

**Comment by mklopets** [comment]
I can also think of valid use cases where the popover should remain open and the map draggable when dragging on top of it. Still not sure if this is really a bug. Before v4.3.0, there was definitely a bug with markers, at least.

**Comment by redbmk** [comment]
I would say this isn’t necessarily unintended behavior, but it is a breaking change. Maybe the marker fix really should have gone to v5? Or maybe popups are a special case. What if popups have an option to prevent mouse events propagating to the map and its on by default to avoid a breaking change (e.g. 4.3.1 would go back to previous behavior with an option to pass events through)?

**Comment by mklopets** [comment]
Release [v4.5.0](https://github.com/alex3165/react-mapbox-gl/releases/tag/v4.5.0) which reverts back the default behaviour.
