### ISSUE TITLE
How to add two base map layers

### ISSUE THREAD

**Issue by giridharkl** [alex3165/react-mapbox-gl#726]
Hi,
We are exploring the possibility to move from Openlayers to  react-map-gl using Mapbox. In our implementation we have two base layers, one by Openstreet maps and another by Google maps. I tried searching for some example using react-map-gl. It works well. But I dont know, how can I add Google maps base layer.

If you could point to me a right example, that would help!

Thanks in advance

**Comment by mklopets** [comment]
Please see https://github.com/mapbox/mapbox-gl-js/issues/1791
