### ISSUE TITLE
Unmounting <Image /> throws an error

### ISSUE THREAD

**Issue by Hless** [alex3165/react-mapbox-gl#727]
### Current behaviour
Unmounting an `<Image /`> component produces the following error:
```
mapbox-gl.js:23344 Uncaught TypeError: Cannot read property 'removeImage' of undefined
    at r.removeImage (mapbox-gl.js:23344)
    at Function.Image.removeImage (image.js:96)
    at Image.componentWillUnmount (image.js:42)
    ... 
```

### Expected behaviour
Be able to unmount an Image component without errors.

### Possible solution
Also check for undefined style in when unmounting the Image component:
`if (map && getStyle()) {`

See:
https://github.com/alex3165/react-mapbox-gl/blob/498171fdc38735f7924be837bc44968c13f6678b/src/image.tsx#L74-L79

### Code to reproduce
```
<Map style="STYLE_UR"}>
    <Image id="image-marker" url="/url/to/image.png" />
    <Layer id="layer" layout={{"icon-image": "image-marker", 'icon-allow-overlap': true  }}>
         <Feature coordinates={COORDINATES} draggable={true} />
     </Layer>
</Map>
```

### Environment
```
"mapbox-gl": "^0.53.1"
"react-mapbox-gl": "^4.3.0",
```
_Note: Also tried with mapbox-gl ^0.54.0_

**Comment by mklopets** [comment]
Released your fix as [v4.5.1](https://github.com/alex3165/react-mapbox-gl/releases/tag/v4.5.1). Thanks a bunch!
