### ISSUE TITLE
How to access the underlying map object

### ISSUE THREAD

**Issue by davidascher** [alex3165/react-mapbox-gl#73]
I'm trying to add the Geolocate control  (https://www.mapbox.com/mapbox-gl-js/api/#GeolocateControl) to my map, but I'm struggling to figure how.  The React devtools tell me that `ReactMapboxGL`'s state contains the `map` object, but it seems improper to poke into the state of a child component from a container component.

What's the best way to use mapbox-gl APIs that aren't encapsulated by the reactified wrapper?

**Comment by davidascher** [comment]
Found the answer in the API doc:

```
To use the original Mapbox API use onStyleLoad property, the callback function will receive the map object as a first arguments, then you can add your own logic using mapbox gl API.
```

**Comment by alex3165** [comment]
Happy to see that the documentation is explicit enough 👍

**Comment by radeno** [comment]
It should be helpful to write example :)
