### ISSUE TITLE
Can't call triggerRepaint or other methods from mapbox api

### ISSUE THREAD

**Issue by jshuadvd** [alex3165/react-mapbox-gl#730]
Attempting to recreate [this](https://docs.mapbox.com/mapbox-gl-js/example/add-image-animated/) and keep getting the error `Map.triggerRepaint is not a function` 

Can you tell me how to access the full api with this wrapper? Or is there another way to do this?

You can view my component [here](https://gist.github.com/jshuadvd/a8db9ef494394b1f18a3f4d516501aea).

thank you!

**Comment by mklopets** [comment]
Map in your code is the react component, not the mapbox instance. For getting the mapbox instance, please see our docs about the onStyleLoad property.
