### ISSUE TITLE
Georeferencing an image

### ISSUE THREAD

**Issue by bertez** [alex3165/react-mapbox-gl#732]
Hi, 

is there any way to overlay a georeferenced image to the map using this library?

Something like this:

![image](https://user-images.githubusercontent.com/159838/57628744-cc07fe00-759a-11e9-8d2c-ad686d80632c.png)

There is a mapbox tutorial here (not mentioning the API): https://docs.mapbox.com/help/tutorials/georeferencing-imagery/

Maybe using projected layers? But I cannot find documentation on how to use them.

Thanks for your help!

**Comment by mklopets** [comment]
Everything that's doable with Mapbox is doable with react-mapbox-gl as well. See our [docs](https://github.com/alex3165/react-mapbox-gl/blob/master/docs/API.md#source) on how to use raster tiles. 

The docs also show you how to access the mapbox Map instance, on which you can use their full API, if ever needed (though I don't see why it'd be needed for this task).

**Comment by bertez** [comment]
Thank you.
