### ISSUE TITLE
Markers change the position during scroll / zoom in and zoom out . 

### ISSUE THREAD

**Issue by raedarrar** [alex3165/react-mapbox-gl#734]
Hi 

When we scroll or zoom in and Zoom out the markers at the end of the screen change their position. It's clearly visible that they are jumping to another geolocation. When I center the marker to the screen again it comes to the correct geolocation. Sometimes the marker which is on land on the zoomout position itself on the sea.

**Comment by guilhermepatriarca** [comment]
You use prop anchor?

**Comment by mklopets** [comment]
I'd also guess this is an issue with the marker's anchoring. For example, if your marker is an image that has transparent padding at its sides and it's anchored top-left, then it'll look correctly positioned on close-up zooms but far away from the real location when zoomed out.

Could you create a minimal shareable example that shows this problem?

**Comment by mklopets** [comment]
Closing as stale, will reopen if new information is provided
