### ISSUE TITLE
supercluster types error

### ISSUE THREAD

**Issue by rob137** [alex3165/react-mapbox-gl#735]
I'm using react-mapbox-gl  v4.4.0  and @types/supercluster v5.0.1.

On building / running, I get this:
``ERROR in [at-loader] ./node_modules/react-mapbox-gl/lib/cluster.d.ts:4:10 
    TS2305: Module '"../../@types/supercluster"' has no exported member 'Supercluster'.
``

Can see something similar came up [before](https://github.com/alex3165/react-mapbox-gl/issues/666#issuecomment-469242775), but I can't find any other mention of this issue.  Am I doing something wrong?

**Comment by radeno** [comment]
This project still use supercluster 3.x

**Comment by rob137** [comment]
Ah, silly me - problem solved by installing `@types/supercluster@3.0.0`.
