### ISSUE TITLE
Feature icon does not show up.

### ISSUE THREAD

**Issue by danksky** [alex3165/react-mapbox-gl#738]
The **marker-15** feature icon is not showing up. 

```
import React, { Component } from 'react';
import ReactMapboxGl, { Layer, Feature, Marker } from "react-mapbox-gl";

import '../stylesheets/StoryList.css'

const Map = ReactMapboxGl({
  accessToken: "helloaccesstoken"
});


class StoryList extends Component {

	render() {
		return (
			<div className='StoryList' >
				<div className='story-list-map' >
					<Map							
						style="mapbox://styles/mapbox/streets-v9"
						containerStyle={{
							height: `100%`,
							width: `100%`
						}}>
						<Layer
							type="symbol"
							id="marker"
							layout={{ "icon-image": "marker-15" }}>
							<Feature coordinates={[51.511459, -0.245408]} />
						</Layer>
					</Map>
				</div>
			</div>
		);
	}
}
```
<img width="472" alt="Screen Shot 2019-06-03 at 2 59 34 PM" src="https://user-images.githubusercontent.com/10901068/58837395-482cb900-8610-11e9-8839-d86b59c1ead4.png">

This is the only potentially relevant warning:
`Line 72:  Style prop value must be an object react/style-prop-object`

**Comment by danksky** [comment]
The map is automatically showing Greater London, and my coordinates were flipping the [<longitude>, <latitude>] coordinate pattern, which is apparently the practice used in GeoJSON. I found this in the documentation for [Component Properties](http://alex3165.github.io/react-mapbox-gl/documentation):

> center (Default: [ -0.2416815, 51.5285582 ]): [number, number] Center the map at the position at initialisation
> -  Must be in longitude, latitude coordinate order (as opposed to latitude, longitude) to match GeoJSON (source: https://www.mapbox.com/mapbox-gl-js/api/#lnglat).

**Comment by danksky** [comment]
A related issue has emerged: 

Upon adding 3 `Feature` component points and specifying **marker-15** (shown below) in the `Layer` component 'layout' property, I don't see the marker icon, but a small black dot, no matter the zoom. 

![image](https://camo.githubusercontent.com/34a5784cb55872bd440a8d65dd3c07669ecb270b/68747470733a2f2f63646e2e7261776769742e636f6d2f6d6170626f782f6d6170626f782d676c2d7374796c65732f6d61737465722f737072697465732f6272696768742d76392f5f7376672f6d61726b65722d31352e737667)

```
<Map							
	style="mapbox://styles/mapbox/streets-v9"
	containerStyle={{
		height: `100%`,
		width: `100%`
	}}>
	<Layer
		type="symbol"
		id="marker"
		layout={{ "icon-image": "marker-15" }}>
		<Feature coordinates={[-0.246408, 51.511459]} />
		<Feature coordinates={[-0.247408, 51.511459]} />
		<Feature coordinates={[-0.248408, 51.511459]} />
	</Layer>
	<Marker
		coordinates={[-0.2416815, 51.5395582]}
		anchor="bottom">
		<img src={'../media/images/burger.jpg'}/>
	</Marker>
</Map>
```

![image](https://user-images.githubusercontent.com/10901068/58900726-909db280-86b4-11e9-8afb-2ca67dd872ad.png)
Near-max-zoom
![image](https://user-images.githubusercontent.com/10901068/58901042-2c2f2300-86b5-11e9-8024-0f22ddfb1cc2.png)
Max zoom

**Comment by mklopets** [comment]
The `marker-15` icon doesn't exist in the style you specified. It works with, for example, `mapbox://styles/mapbox/light-v9`.

**Comment by KOSSOKO** [comment]
So formapbox://styles/mapbox/streets-v11 for example, what is the correct name of marker-15 ? I'm facing the same issue.

**Comment by martsie** [comment]
If you're having issues with the dots, try using Marker outside of layer. Marker's don't work inside the layer component.

**Comment by ejdoh1** [comment]
Had the same problem and fixed it by creating a custom map style in [Mapbox studio (MBS)](https://studio.mapbox.com/) and uploading a custom image to the style.
I used the [Google Maps marker SVG](https://upload.wikimedia.org/wikipedia/commons/d/d1/Google_Maps_pin.svg) as the custom image.
```
      <Map
        style="mapbox://styles/<userId>/<mapStyleUniqueId>" //copy-paste from MBS
        containerStyle={{
          height: "100vh",
          width: "100vw"
        }}
        center={[144.8926947,-37.871237]}
        zoom={[9]}
      >
        <Layer type="symbol" id="marker" layout={{ "icon-image": "Google_Maps_pin" }}>
          {this.getFeats()}
        </Layer>
      </Map>
```
<img width="953" alt="Screen Shot 2020-03-17 at 10 39 01 pm" src="https://user-images.githubusercontent.com/6044589/76852762-2307ef00-68a0-11ea-9fe0-29ce13c85d13.png">

**Comment by ajthinking** [comment]
Im using almost the exact example in the readme and the feature is not showing.
Tried a few styles mentioned to no effect. Any known combination that will work? Or where can I see a reference of compatible styles?

```jsx
import React from 'react';
import ReactMapboxGl, { Layer, Feature } from 'react-mapbox-gl';
import 'mapbox-gl/dist/mapbox-gl.css';
import * as mapboxgl from 'mapbox-gl'
import { inject, observer } from "mobx-react"
import 'mapbox-gl/dist/mapbox-gl.css';


const MapboxMap = ReactMapboxGl({
    accessToken:
      '.....'
  });

class Map extends React.Component {

    render() {
        return (
            <MapboxMap
                style="mapbox://styles/mapbox/streets-v9"
                containerStyle={{
                    height: '100vh',
                    width: '100vw'
                }}
                >
                <Layer type="symbol" id="marker" layout={{ 'icon-image': 'light-v9' }}>
                    <Feature coordinates={[0, 0]} />
                </Layer>
            </MapboxMap>
        )
    }
}

export default inject('store')(observer(Map));
```

**Comment by Beeze** [comment]
having a similar issue - loading a custom image with `images` prop, but the feature isn't showing up on the map. confirmed via logs the images prop is being set correctly.

```
const MapComponent = (props) => {

  const [images, setImages] = React.useState(null)
  React.useEffect(() => {
    const markerImage = new Image(30, 30)
      markerImage.src = marker
      setImages(['custom-marker', markerImage])
  }, [])

  // long, lat
  const center = [-83.0458, 42.3314] as [number, number];

  if (images === null) {
    return null
  }

  console.log(images)

  return (
    <Map
      style="mapbox://styles/mapbox/light-v9"
      center={center}
      zoom={[9]}
      containerStyle={{
        height: '100vh',
        width: '100vw'
      }}
    >
      {images.length > 0 ? (
        <Layer 
          type="symbol"
          id="marker"
          images={images}
          layout={{ 'icon-image': 'custom-marker' }}
        >
          <Feature coordinates={[-83.0458, 42.3314]} />
          <Feature coordinates={[42.3314, -83.0458]} />
        </Layer>
      ) : (
        <div></div>
      )
    }
    </Map>
  );
}
```

**Comment by FrederickEngelhardt** [comment]
Any resolutions?

**Comment by Beeze** [comment]
@alex3165 @daniel-hauser

**Comment by Beeze** [comment]
opened an issue here too https://github.com/alex3165/react-mapbox-gl/issues/920

**Comment by Ahmdrza** [comment]
still facing same issue
