### ISSUE TITLE
How to call map.panTo() and other instance members of mapboxgl.Map

### ISSUE THREAD

**Issue by danksky** [alex3165/react-mapbox-gl#739]
I would like to smoothly pan between coordinates whenever my React list components are hovered-over. How can I call **`panTo()`** and other instance members of mapboxgl.Map?

**Comment by mklopets** [comment]
You can access the mapbox map instance via either the context api or the onStyleLoad callback, both of which are documented in our docs

**Comment by ericscottmarquez** [comment]
@mklopets 

Doing this:

```javascript
          <MapContext.Consumer>
            {map => {
              console.log('map corner northEast', map.getNorthWest());
              // use `map` here
            }}
          </MapContext.Consumer>
```

is not working, it seems to work for `getCenter()` off the https://docs.mapbox.com/mapbox-gl-js/api/geography/#lnglatbounds#getnortheast part of the docs,

However, for `getNorthEast()`, including all the other functions to query the corners of the maps viewport are returning the error: 
```error
Mapview.js:147 Uncaught TypeError: map.getNorthWest is not a function
```

Am I missing something here or is it not supported in the wrapper? I'm using version 5.0.0
