### ISSUE TITLE
Popup not displayed when Feature's onClick is triggered

### ISSUE THREAD

**Issue by evan0065** [alex3165/react-mapbox-gl#745]
Hi! I am trying to display a Popup when a circle is clicked on a map. However, every time the circle is clicked, no Popup is displayed. The circle is being clicked, as I checked this simply with console.log('clicked').

Here's a snippet of my code: 

```
<Layer id='points' type='circle' >
   this.array.map((obj, i) => {
      return (
         <Feature coordinates={[0,0]} 
           onClick={() => {
              console.log('clicked') // just for debugging to see if the circle is clicked
              return (
                 <Popup coordinates={[0,0]} offset="bottom" > info </Popup>
          )}} /> // closes the Feature
      )
   })}
</Layer>
```

Am i incorrectly creating the Popup or is another error causing the Popup to not display?  I would appreciate any help regarding why the popup is not being generated!

**Comment by mklopets** [comment]
You need to have some state in your component and render the Popup component after the click. Returning a Popup from the click handler has no effect.
