### ISSUE TITLE
Closing a popup when clicking outside of it

### ISSUE THREAD

**Issue by kaitlynbrown** [alex3165/react-mapbox-gl#746]
I'd like for a popup to be closed if a user clicks anywhere outside of the popup.
I've tried adding an onClick handler to the map which closes any open popup, but the problem is that it is triggered even when I click on the popup itself. Even worse, if I try to add a button to the popup, when I try clicking on the button, the map's onClick event gets called first, causing the popup to close before the button's onClick handler is called.

What is the correct way to do this?

**Comment by kaitlynbrown** [comment]
I was able to resolve this by adding a transparent layer on top of the map when there is a popup showing, and adding an onClick handler to that layer which closes the popup

**Comment by jbeuckm** [comment]
@kaitlynbrown Did you have to draw something in the transparent layer? I added an empty layer but I don't see the onClick happening... Thank you.

**Comment by reinink** [comment]
I was able to get around this issue by stopping propagation in my marker click handler:

```js
marker.addEventListener('click', e => {
  e.stopPropagation()
  ...
```

**Comment by todd-elvers** [comment]
I've run into this exact same issue!  It really shouldn't be this hard to close popups when a user clicks outside of them.

Does anyone have an example up of either of the workarounds that @reinink or @kaitlynbrown suggested?

**Comment by abigray** [comment]
Clicking outside of a popup on the map closes the popup for me.  What's your closeOnClick value in the Popup?  If closeOnClick is set to true (the default value) the popups close when the user clicks on the map.
<Popup    
                closeOnClick={true}
...


Unfortunately for me, I need closeOnClick to be false to ensure mouseClicks reach my buttons on the popup so I need a manual way to close the popup from my onClick function.

**Comment by ScottEAdams** [comment]
I am using https://material-ui.com/components/click-away-listener/ but I guess you could use something such as https://github.com/wellyshen/react-cool-onclickoutside for the same effect

**Comment by pinplengpai** [comment]
> I am using https://material-ui.com/components/click-away-listener/ but I guess you could use something such as useClickAway from [react-use](https://github.com/streamich/react-use) or even [react-cool-onclickoutside](https://github.com/wellyshen/react-cool-onclickoutside) for the same effect

it does work!! thank you so much :)

**Comment by thomaslanenh** [comment]
Has there been any updates on this? I can't get closeOnCLick to work at all :(

**Comment by YisusMB** [comment]
Hi! i used [react-click-away-listener](https://www.npmjs.com/package/react-click-away-listener) package, and works for me, just wrap your div with this, ie:
````js
<Popup 
  // your props...
>
  <ClickAwayListener onClickAway={closePopup}>
    <div>
      {/* your component to display when popup is visible /*}
    </div>
  </ClickAwayListener}>
</Popup>
````
@disneyquesting

**Comment by jasonguro** [comment]
This worked for me when clicking anyone on the map, but it doesn't work when you click on another marker on the map, any ideas? (have multiple popups showing at once is weird).

> Clicking outside of a popup on the map closes the popup for me. I believe it's the default behavior when you set up the basic example in the ReactMapGL documentation. What's your closeOnClick value in the Popup? If closeOnClick is set to true (the default value) the popups close when the user clicks on the map. <Popup closeOnClick={true} ...
> 

@abigray
