### ISSUE TITLE
Source cannot be removed while layer is using it. And lagging...

### ISSUE THREAD

**Issue by paoe60** [alex3165/react-mapbox-gl#749]
Hello! 
The error that appears in the console when switching cities:
`Error: Source "districtName" cannot be removed while layer "districtName-border" is using it.`
Also my map lags a lot when zooming and moving =( Please tell me what am I doing wrong

Layers create like this: 
```
<Layer
   key={feature.properties.name}
   id={feature.properties.name}
  type={'fill'}
>
  <Feature
    coordinates={feature.geometry.coordinates}
    properties={feature.properties}
    onClick={this.onClick}
  />
</Layer>
```
**Code:** https://stackblitz.com/edit/react-ts-rkxk2f?file=Map.tsx

**Comment by mklopets** [comment]
You can't expect someone to debug your code, of which 90% is completely unrelated to the problem. I'm not sure what the `sourceId`s in your code are referring to. Seems like a hack. `sourceId` is generally meant to be used with `<Source>` components.

From the error, it seems that you're removing the automagical creator of a source (most likely a Feature component) before/without removing the Layer using it.

If Layers use only the data in Features inside them, no sourceId needs to be provided.
