### ISSUE TITLE
Is it possible to draw features on top of other features without re-rendering the original features?

### ISSUE THREAD

**Issue by evan0065** [alex3165/react-mapbox-gl#750]
Hi, I understand that the topic question might be a bit confusing. Here is a clarification of what I am now doing: 

1. I draw 10,000 `features` (circles) on a map. 
2. I draw another 10,000 circles on a map and it erases the original 10k circles. 

I know that I can keep an array and continuously push to it, e.g.
1. Draw the original 10k circles on the map from an array `points`.
2. Push the next 10k circles into `points` and draw all 20k circles. 

This isn't my goal because I don't want to redraw the original points on the map. My reason for drawing the circles 10k at a time is due to performance optimizations and other constraints.

So here's my question: **Can I draw the new 10k circles on the map without erasing/redrawing the original 10k points?**

Also if anyone has other ideas for the issue title then I'll gladly change it. Just couldn't think of a better one!

**Comment by mklopets** [comment]
Are you using symbols? Mapbox by default hides overlapping symbols. See [icon-allow-overlap](https://docs.mapbox.com/mapbox-gl-js/style-spec/#layout-symbol-icon-allow-overlap). It's not about the feature, but only about the method used for drawing it.

**Comment by evan0065** [comment]
@mklopets 
I'm basically creating a layer with `type="circle"` and drawing a feature within the layer. Either way, `icon-allow-overlap` does seem to be what I'm looking for. However, I implemented it in my layer and I'm receiving the error message of `unknown property "icon-allow-overlap"`. Do you have an idea why? (Please see layer code below)
```
<Layer id="points" type="circle" paint={{'circle-color': 'red', 'circle-radius': 5}} 
 layout={{'icon-allow-overlap': true}}>
     {this.state.points.map((element, i) => {  
          return (
               <Feature coordinates={[element.lon, element.lon]} /> 
          )
      })}
</Layer>
```

**Comment by mklopets** [comment]
Ah, yes, this property only applies to symbol layers. Could you provide your full code, including the place where you push the 2nd 10k circles on to the map?

**Comment by evan0065** [comment]
@mklopets 
I currently do not have access to my full code, but here's some snippets which essentially describes what I'm doing. 

```
/** In the this.request() method */
var arr = []
var arr2 = []
var total = []

// populate the first array with 10k then the second array with 10k points 
for (var i = 0; i < 20000; i++) {
     var element = {}
     element.lon = Math.random() * 80
     element.lat = Math.random() * 80
     if (i < 10000) {
          arr.push(element);
     }
     else {
          arr2.push(element);
     }
}

// basically, the following pushes are creating [arr, arr2], with each array having 10k points each
total.push(arr)
total.push(arr2)

// Set the state of 'points' with my randomly populated array
this.setState({ points : total });

/** In the actual map render */
// a whole bunch of code defining my map, map context consumer, and html objects for the ui
<Layer id="points" type="circle" paint={{'circle-color': 'red', 'circle-radius': 5}} >
     {this.state.points.map((morePoints, i) => {  
          return (
               {morePoints.map((element, i) => { 
                    return (
                         <Feature coordinates={[element.lon, element.lon]} /> 
               )}
          )
      })}
</Layer>
```

This more or less resembles my code. You can see that in this case, all the points will be drawn within the same render, so no issue is caused. But, in my real code, I am working with multiple http requests with essentially serves to populate the array with 10k points. So my first request is graphed, then I need to display the second request on top of the first. I would rather not display the code where I am making the http requests, if possible.

Let me know if I can provide any clarification, since the code does not 100% reflect my intentions, but I thought it was best to include it!

**Comment by mklopets** [comment]
I might have initially misunderstood your problem a bit.

What you can do is have two separate layers on the map, one for each of your network fetches.

```
{
  this.state.pointsA && (
    <Layer id="points-a" type="circle" paint={{ 'circle-color': 'red', 'circle-radius': 5 }}>
      {this.state.pointsA.map((point) => (
        <Feature coordinates={[point.coordinates]} />
      ))}
    </Layer>
  )
}
{
  this.state.pointsB && (
    <Layer id="points-b" type="circle" paint={{ 'circle-color': 'red', 'circle-radius': 5 }}>
      {this.state.pointsB.map((point) => (
        <Feature coordinates={[point.coordinates]} />
      ))}
    </Layer>
  )
}
```

Now, if pointsB appears in the state (after a network request), react-mapbox-gl will only create that layer, keeping the `points-a` layer as-is.

**Comment by evan0065** [comment]
@mklopets 
Sorry if my original statements were a bit misleading! The idea of creating different layers does make sense though and should definitely work. 

Just to know, is there a way this implementation could work with larger batches of points? By that, I mean, graphing 50,000 points instead of the 20,000 I previously mentioned. So in this implementation, there would be 5 different layers, each containing 10,000 points, which can become a little cumbersome.

I know that I could easily change my network requests to make the arrays `pointsA` and `pointsB` contain more points, but I'm curious to see if there's another way.

Thanks!

**Comment by evan0065** [comment]
For those looking at this in the future, I figured out an easier way instead of writing out many different layers. Basically, I'm just pushing to my array in the state, which automatically updates in my Layer and redraws it. If anyone has any questions/wants the code, feel free to comment and ask (if possible)!

**Comment by mklopets** [comment]
The reason for suggesting the two layers was that it should be slightly more performant, because mapbox doesn't have to initialize the first set of points twice.

Mapbox itself has some docs on optimizing for large data sets: https://docs.mapbox.com/help/troubleshooting/working-with-large-geojson-data/
