### ISSUE TITLE
ZoomControl passes clicks through to map

### ISSUE THREAD

**Issue by kaitlynbrown** [alex3165/react-mapbox-gl#751]
If a marker is beneath the zoom control when I click on it, the marker gets clicked too. If I click on the zoom control quickly enough to be registered as a double click, it causes the map to zoom in on that point, which would be annoying for a user just trying to zoom out quickly.

Please make it so that clicks on the zoom control are not propagated

**Comment by mklopets** [comment]
This is fixed with the `renderChildrenInPortal` prop's default value introduced in `v4.5.0`.
