### ISSUE TITLE
Upgrade to MapboxGL v1

### ISSUE THREAD

**Issue by kjkurtz** [alex3165/react-mapbox-gl#756]
Is there any current initiative to upgrade to MapboxGL v1 or newer? I need to start taking advantage of the new pricing model sometime soon and v1.0.0 or newer is required. If not, is there anything specific that is a show stopper for this upgrade to happen? I'd be happy to contribute. Thanks!

**Comment by mklopets** [comment]
Hey! No real blockers that I know of. I'll have to take a look – might be able to release a new version of react-mapbox-gl without bumping the major version – v1 didn't really bring any API-breaking changes AFAIK.

**Comment by kjkurtz** [comment]
Agreed! I read the changelog and didn't see anything alarming. I also just submitted that PR with the upgraded version. All the tests pass and things look good from my end.

**Comment by mklopets** [comment]
Thanks for the PR! Released as [`v4.6.0`](https://github.com/alex3165/react-mapbox-gl/releases/tag/v4.6.0).
