### ISSUE TITLE
How would I add layer behind another layer?

### ISSUE THREAD

**Issue by shobishani** [alex3165/react-mapbox-gl#758]
I have three to four layers one of them is Heat-map it's showing behind the Fill (polygon) layer.
I could've rendered it in sequence but user have the option to render whatever he choose so he might choose heat map layer first then polygon layer and heat map layer hides under the polygon layer.

**Comment by mklopets** [comment]
The `Layer` component has a `before` prop, which refers to another layer's id. [See docs](https://github.com/alex3165/react-mapbox-gl/blob/master/docs/API.md#layer).
