### ISSUE TITLE
Update documentation with event methods

### ISSUE THREAD

**Issue by jimbol** [alex3165/react-mapbox-gl#759]
Add docs for:
```
onClick={(map, event) => map.getBounds()}
```
and
```
onClick={(map, event) => map.getCanvas()}
```

=====

Are there other items that need to be documented? These are the two I ran into. I'm assuming the `map` object has more capability that isn't documented.

**Comment by mklopets** [comment]
This library is just a React wrapper for [mapbox-gl](https://github.com/mapbox/mapbox-gl-js). The docs of this library don't intend to duplicate the documentation of mapbox-gl-js, e.g the instance methods of the map ([docs](https://docs.mapbox.com/mapbox-gl-js/api/#map)).

Under [Layer properties docs](https://github.com/alex3165/react-mapbox-gl/blob/master/docs/API.md#properties), we actually already link to the relevant mapbox-gl-js docs.
