### ISSUE TITLE
which API react-mapbox is using?

### ISSUE THREAD

**Issue by taurni** [alex3165/react-mapbox-gl#760]
Is it the Mapbox Vector Tiles API?
How can I use it with Mapbox GL JS version to get billed by map loads?
https://docs.mapbox.com/help/account/pricing/#mapbox-gl-js-v100-and-higher

Thanks!

**Comment by mklopets** [comment]
react-mapbox-gl is currently a wrapper of mapbox-gl-js 1.x. This means the new pricing model will apply when the newest version is used.
