### ISSUE TITLE
Is this implementation right for react native?

### ISSUE THREAD

**Issue by esuarezz** [alex3165/react-mapbox-gl#768]
Can I use the 3dMap from this demo to use it in my react native impl?

**Comment by mklopets** [comment]
No, this library wraps mapbox-gl-js, which is for the web. For native, see https://github.com/mapbox/mapbox-gl-native / there are also some react native wrappers unrelated to react-mapbox-gl

**Comment by jthetzel** [comment]
@esuarezz 
For React Native, try https://github.com/react-native-mapbox-gl/maps . 
This is the actively maintained succesor to https://github.com/nitaliano/react-native-mapbox-gl .
