### ISSUE TITLE
OnContextMenu on chrome browser isn't always emitting events.

### ISSUE THREAD

**Issue by ganeshrvel** [alex3165/react-mapbox-gl#783]
Hi,

The right click context menu on chrome browser (v 77.0) isn't always emitting the onContextMenu events (https://github.com/alex3165/react-mapbox-gl/blob/master/docs/API.md#events). 
It fails to emit events at random positions. It works just fine in Firefox.

**Comment by mklopets** [comment]
This seems to rather be a problem with [mapbox-gl-js](https://github.com/mapbox/mapbox-gl-js) itself – react-mapbox-gl doesn't trigger the events itself
