### ISSUE TITLE
Supercluster types should be dependency + error in their import

### ISSUE THREAD

**Issue by henrinormak** [alex3165/react-mapbox-gl#791]
Due to the way Supercluster types are used [here](https://github.com/alex3165/react-mapbox-gl/blob/dfa49fd1556792e899ff6f8d82d92d74d01abefa/src/cluster.tsx), they should be listed as dependency/peerDependency, not just devDep. The reason is the exported State interface, which refers to the Supercluster type.

Furthermore, even after installing the supercluster types to a project, typescript still fails with the following error:

```
node_modules/react-mapbox-gl/lib/cluster.d.ts:23:13 - error TS2749: ‘Supercluster’ refers to a value, but is being used as a type here.

23     superC: Supercluster;
              ~~~~~~~~~~~~
```

If I were to alter the code in cluster.d.ts:4 to be `import * as Supercluster from 'supercluster';` then this error goes away. So probably this is caused by changes made in #731.

#735 referred to a build error that might be somewhat related to this.

**Comment by alex3165** [comment]
Hey @henrinormak I am not too sure why the examples didn't pick this up, I will have a look if I have some time, meanwhile feel free to open a pull request if you have some time with a proper fix

**Comment by henrinormak** [comment]
@alex3165 I'll see if I can whip up a PR that would fix the problem, I have not touched the codebase of react-mapbox-gl before, so it might take me a bit longer to sort this out though.

**Comment by narkowicz** [comment]
Chiming in to say this is also breaking our webpack builds (we're not transpiling `node_modules`):

```
ERROR in node_modules/react-mapbox-gl/lib/cluster.d.ts(23,13):
TS2749: 'Supercluster' refers to a value, but is being used as a type here.
Version: typescript 3.6.4
```

Changing the import in `cluster.d.ts` to `import * as Supercluster from 'supercluster';` as suggested by @henrinormak results in the following error:

```
ERROR in node_modules/react-mapbox-gl/lib/cluster.d.ts(23,13):
TS2709: Cannot use namespace 'Supercluster' as a type.
Version: typescript 3.6.4
```

**Comment by narkowicz** [comment]
As per #735 this was solved by installing `@types/supercluster@latest`... "Silly me" indeed! Original report appears correct in that the types should be production or peer dependency. 👍

**Comment by mklopets** [comment]
`esModuleInterop` solves the import issue; release [v4.8.1](https://github.com/alex3165/react-mapbox-gl/releases/tag/v4.8.1) solves the type dependency issue
