### ISSUE TITLE
How to get mapbox instance?

### ISSUE THREAD

**Issue by taurni** [alex3165/react-mapbox-gl#802]
I want to crete a new LngLatBounds() object but how will I get the mapbox instance for that?
const bbox = new mapboxgl.LngLatBounds(sw, ne);

import ReactMapboxGl, { Marker } from 'react-mapbox-gl';
const Mapbox = ReactMapboxGl({
  accessToken: process.env.MAPBOX_ACCESS_TOKEN,
  attributionControl: false,
  logoPosition: 'top-right'
});

**Comment by mklopets** [comment]
```
import { LngLatBounds } from 'mapbox-gl';
```

it's one of mapbox-gl-js's exports
