### ISSUE TITLE
Using Custom Tiles rather than Mapbox

### ISSUE THREAD

**Issue by toton6868** [alex3165/react-mapbox-gl#806]
Can I use custom tiles rather than using Mapbox Tiles? Here I am changing my own Tiles from custom style.json. But the map is not loading.
```
  <Map
    style="https://myowntiles.com/style.json"
    zoom={zoom}
    containerStyle={{
      height: "100%",
      width: "500px"
    }}>
      <Layer
        type="symbol"
        id="marker"
        layout={{ "icon-image": "marker-15" }}>
        <Feature coordinates={[-0.481747846041145, 51.3233379650232]}/>
      </Layer>
  </Map>
```

**Comment by mklopets** [comment]
We pass the `style` prop directly on to mapbox-gl-js. Here's an example from the mapbox folks about using third party tiles: https://docs.mapbox.com/mapbox-gl-js/example/third-party/

Here are the mapbox docs on the style option: https://docs.mapbox.com/mapbox-gl-js/api/#map

See our [docs](https://github.com/alex3165/react-mapbox-gl/blob/master/docs/API.md#source) for how to add sources and layers – or alternatively, the "Using the original Mapbox API" section of our docs on how to make the exact code you see in the mapbox-gl-js example work with react-mapbox-gl.
