### ISSUE TITLE
No result on queryRenderedFeatures API

### ISSUE THREAD

**Issue by MikeChenfu** [alex3165/react-mapbox-gl#807]
Hello, I try moving my `mapbox` work to the react. I met some problem.
I uses `queryRenderedFeatures` to achieve the features of one layer and the code is shown blow, but it returns empty.
```
this.map.addLayer({
        'id': "states",
        'source': "state-population",
        'source-layer': layerMatch["state-2d"][1],
        'maxzoom': this.state.zoomThreshold[0],
        'type': 'fill',
        'layout': {
          'visibility': 'visible'
           },
        'paint': {
          "fill-opacity":0.8   
        }
      }, 'waterway-label');

let featuresAll = this.map.queryRenderedFeatures({layers:['states']});
console.log(featuresAll)
```
If I change `this.map.queryRenderedFeatures({layers:['states']});` to 
`this.map.queryRenderedFeatures({lay:['states']});`, I can get the return values but it is not the `state` layer. I appreciate if anyone can help me.

**Comment by rlueder** [comment]
I'm having the same issue, if I log `map.queryRenderedFeatures()` to console I see default Mapbox layers like `admin` and `water` but not my custom layers.

**Comment by mklopets** [comment]
The load event might also work. Either way, this issue is really about mapbox-gl-js, not the react wrapper – feel free to open another one there if you're still having trouble.
