### ISSUE TITLE
Support for initial zoom/center

### ISSUE THREAD

**Issue by joshwcomeau** [alex3165/react-mapbox-gl#81]
Correct me if I'm wrong, but I believe right now there's no way to set _initial_ values for zoom or center; You either need to make them controlled values, or stick with the current default.

For a project I need a specific zoom/center on load, but I otherwise don't care about zooming/panning, so I'd just like to update the initial values set to Mapbox.

Let me know if this is a feature that you'd be interested in, I can submit a PR if I don't hit any weird issues.

**Comment by alex3165** [comment]
Hey @joshwcomeau, I don't really see what you mean here, if you pass down a `zoom` and `center` value to the Map it should work :
```
<ReactMapboxGl
  center={[0.5375194, 50.8437787]}
  zoom={[11]}
>     
```
Tested with the london-cycle example and it works as expected.

**Comment by joshwcomeau** [comment]
Hey @alex3165,

Thanks for the quick reply!

So, my issue with that is that whenever the component re-renders, the map will zoom/pan to that location. I need a map that initializes at a certain position, but then is free to be panned/zoomed, with re-renders not overwriting wherever the user has left the map.

**Comment by alex3165** [comment]
Have you tried to not break the reference equality between 2 re-render, you can keep the reference by having the center and the zoom in your state like this :
```
state = {
center: [0.5375194, 50.8437787],
zoom: [11]
}

...

<ReactMapboxGl
  center={this.state.center}
  zoom={this.state.zoom}
>

```

**Comment by joshwcomeau** [comment]
Ohhh. Right, that makes total sense. 

Sorry to have disturbed you! Happy to learn that it was my mistake :)

**Comment by alex3165** [comment]
No problem happy to solve your problem 👍

**Comment by sohibul** [comment]
But if you update the state using `setState` the reference still the same right? So the center will not move

**Comment by alex3165** [comment]
Nope, you will break the reference equality if you assign a new array :
```
this.setState({
  zoom: [new_zoom_value]
});
```

**Comment by sohibul** [comment]
You're right, i have mistake

**Comment by paulduthoit** [comment]
Hello,

What about the `map.fitBounds()` method? The state is not used in this case. It would be great to have an `initialCenter` that initiate the map with that center and don't override the next values.

Thanks

**Comment by Kranysys** [comment]
@paulduthoit I agree with you. to bypass this problem I put an initial `fitBounds` value. But it still not clean, we should be able to the inital center on the map.

**Comment by asalpha** [comment]
any updates on this? it would be very beneficial to let the user set the default center
