### ISSUE TITLE
React-Mapbox-GL keeps refreshing on state update

### ISSUE THREAD

**Issue by ronaldlangeveld** [alex3165/react-mapbox-gl#812]
I have the following simple React Component using the react-mapbox-gl wrapper. So far, it's great, however I find a small annoyance when trying to update state, using the useState hook.

    
        function Location(props) {
           const [selectedMarker, setSelectedMarker] = useState(null);
           const [markerBlock, setMarkerBlock] = useState(false)
          const {payload} = useContext(MarkerContext);
          const [latlong, setLatlong] = useState(null);
        
        
          console.log(payload);
        
            const Map = ReactMapboxGl({
                accessToken:
                  'tokenHiddenforstackoverflow',
                  
              });
        
              const getLatlng = (map, event) => {
        
                  setLatlong(event.lngLat);
              }
        
        
            return (
                <>
        <Map
          style="mapbox://styles/mapbox/satellite-streets-v9"
          containerStyle={{
            height: '100vh',
            width: '100%'
          }}
          onClick={getLatlng}
          center={[18.432723671572944, -33.926210020024826]}
        >
        <ZoomControl />
        
        </Map>
        
                </>
        
            );
        }
        
        export default Location;

Whenever I update the LatLong state, the mapbox background turns black and the whole map reloads. Not sure if a coding / structural error or a bug from Mapbox. I tried restructuring this into smaller components as well, but no difference. 

Any ideas?

**Comment by mklopets** [comment]
`Map` should be initialized using the `ReactMapboxGl` factory function only once, outside of the render function (or the functional component equivalent)

you're currently creating a new map instance per render, which is both costly and causing this bug in your app

**Comment by ronaldlangeveld** [comment]
haha thanks! Just put const Map outside the Location function and it worked fine. Cheers!
