### ISSUE TITLE
 Feature is not exported from 'react-map-gl'.

### ISSUE THREAD

**Issue by mnoster** [alex3165/react-mapbox-gl#818]
I'm using `react-map-gl` version 5.2.0 and I'm trying to use the `Feature` component but it is not being exported by the package.

I'm importing it like so:
```
import MapGL, {  Feature, Marker } from 'react-map-gl';
```

Error:
```
Attempted import error: 'Feature' is not exported from 'react-map-gl'.
```

The other components are working and available.

Is `Feature` supported?

**Comment by krisaoe** [comment]
@mnoster this is the repository for react-mapbox-gl, not react-map-gl

**Comment by mklopets** [comment]
@krisaoe is correct, you are looking at the docs of a library different from the one you are importing from.

**Comment by mnoster** [comment]
my bad
