### ISSUE TITLE
Add prop to enable the TouchZoomRotateHandler

### ISSUE THREAD

**Issue by SuiOni** [alex3165/react-mapbox-gl#82]
How is it possible to add a pinch to zoom functionality or any other zoom function for mobile?
Right now I can only zoom via mouse wheel.

I can find touch handlers in the source code but there is no documentation how to set them up for zoom.

An other option would be to add a navigation button. 
So how can i add the native mapbox-gl zoom controls in a reactive way? 

Right now I had to add 
```javascript 
map.addControl(new mapboxgl.NavigationControl());
``` 
 to the source code. 
It works but the overlays is off by one zoom level and only update after zoom is finished, so its buggy.

Thank you guys for the awesome work!

**Comment by alex3165** [comment]
Hey @SuiOni thank you for submitting the issue, I will have a look at this later this week

**Comment by philpl** [comment]
@SuiOni There is the ZoomControl component which we have instead of the NavigationControl.
However, we don't have pinch to zoom support as far as I know.

**Comment by alex3165** [comment]
I think it is worth investigating for adding the pinch to zoom functionality, I will have a look Tomorrow or Friday as I am in holidays

**Comment by philpl** [comment]
@SuiOni If you need this urgently, you should be able to add it by doing:

```js
new mapboxgl.TouchZoomRotateHandler(map)
```

**Comment by alex3165** [comment]
I have tested the examples on Chrome on iOS 10.2.1 and I am able to zoom and rotate with a pinch natively without enabling `TouchZoomRotateHandler`. Therefore I will close this issue.
