### ISSUE TITLE
Example not working

### ISSUE THREAD

**Issue by marr** [alex3165/react-mapbox-gl#83]
I saw some previous issues about the examples not working which were related to webpack version. I am a v2.1.0-beta.27 after npm installing and I receive no errors.

The server says its running on localhost:8080 but I see nothing when I view in the browser, just "The localhost page isn't working"

I tried upgrading webpack-dev-server and webpack to v2.2.0-rc.0 and that didn't help..

**Comment by alex3165** [comment]
Hey @marr I have tried to run the example from a clean clone and it worked, can you tell me which browser / node version you are using ?

**Comment by marr** [comment]
Hi Alex, I tried using node v5.11.1, 6.4.0, 7.2.0 and Safari 10.0.2 and Chrome 55.0.2883.95. It seems there may be some kind of issue on my machine, because I tried it on another machine last night and things worked fine. I'm not sure how to troubleshoot this on my machine. If you have any ideas let me know. Thanks!

**Comment by philpl** [comment]
@marr I've tried it as well, and it does still work. I'll close this for now. Can you provide more information in case it's an issue with the server or build itself? If it doesn't output an error though, it shouldn't be an issue with the example.

**Comment by marr** [comment]
I am on osx 10.11.6 (el capitan), its possible my machine just needs a clean but i found it odd this didn't show any errors it just seemed to not get any data from the server. I run another development app on localhost:8080 just fine (closed it obviously before starting this). `lsof -i:8080` was empty before starting this server, so there shouldn't be any conflict.

**Comment by philpl** [comment]
Well, I'm unsure how to help you with this :?
All we're doing is this on the webpack-dev-server:

```js
server.listen(8080, "localhost", function() {
  console.log('☕️  Server is listening on localhost:8080.');
})
```

Might be worth trying to change it to just `server.listen(8080, function() {`

**Comment by marr** [comment]
@philpl That did fix it. I wonder what the issue with specifying "localhost" is?

**Comment by philpl** [comment]
@marr It might be an issue that prevents `localhost` from resolving to `127.0.0.1` or `::1` on your machine, maybe?
