### ISSUE TITLE
Error rendering GeoJSONLayer in IE11

### ISSUE THREAD

**Issue by daschi** [alex3165/react-mapbox-gl#835]
Hello and thank you for this package, it's been very helpful in our project. I was wondering if there are known issues with rendering layers for IE11. I am able to render the map fine, but am seeing an "Access Denied" error when I try to add a GeoJSONLayer component. Has anyone found a workaround for this or understand the root of the issue?

Thanks for your help!! 

Error is on Internet Explorer 11, Windows 10
```
"react": "^16.12.0",
"react-dom": "^16.12.0",
"mapbox-gl": "^1.7.0",
"react-mapbox-gl": "^4.8.0"
```

**Comment by mklopets** [comment]
we're using `GeoJSONLayer` in production and it works well on IE11, please share a reproducible broken-on-IE11 example

**Comment by daschi** [comment]
@mklopets Thanks for the info! I was able to create an example using GeoJsonLayer that works in IE11, so this will help me debug the actual issue in my project. Once I figure out the part of the code that's causing the issue in ie11 I'll post back here.

**Comment by daschi** [comment]
For anyone who might stumble across this and is having a similar issue, the problem was not the `GeoJSONLayer`.  We were attempting to load our own images (see code example) instead of using the `Layer` component's prop for `images`. I'm not exactly sure why this was causing an issue only in IE11, but removing the `loadImage` function and using `<Layer images={images}>`instead  fixed the issue for me. 

```
map.loadImage(imageURL, (err, image) => {
    if (err) {
      onLoad(err, imageId)
      return null
    }
    if (map.hasImage(imageId)) {
      return null
    }
    map.addImage(imageId, image, options)
    onLoad(null, imageId)
  })
```

instead used this:
```
  const image = new Image(24, 24)
  image.src = imageSoureURL
  const images = [PIN_IMAGE_ID, image]

<Layer
        id={layerId}
        sourceId={sourceId}
        type='symbol'
        layout={{
          'icon-allow-overlap': true,
          'icon-image': PIN_IMAGE_ID,
          'icon-size': 1.0
        }}
        images={images}
      />
```
