### ISSUE TITLE
Is there support for the MultiLineString as a Layer type?

### ISSUE THREAD

**Issue by iakov-opensc** [alex3165/react-mapbox-gl#858]
MapBox supports the MultiLineString geometry type (see https://jsbin.com/cozudodelo/edit?html,output for example). It would be great to be able to use it in the React wrapper too.

**Comment by mklopets** [comment]
doesn't the GeoJSONLayer do what you need?

**Comment by iakov-opensc** [comment]
Yep, it actually does. Thanks!
