### ISSUE TITLE
Howto: vector tiles

### ISSUE THREAD

**Issue by MarkLyck** [alex3165/react-mapbox-gl#860]
Hi, I'm trying to get a simple map working with vector tiles.

I can easily do it with mapbox gl JS library, but I've spent an hour with react-mapbox-gl and I still can't see how to use vector tiles with this library?

The only documentation is this single line: "apiUrl: string Define a custom URL to fetch the vector tiles."

The vector tiles I want to use is the default streets one: mapbox.mapbox-streets-v8
found here: https://docs.mapbox.com/vector-tiles/reference/mapbox-streets-v8/

So I tried the following configs:

`<MapBox apiUrl="mapbox.mapbox-streets-v8">`
`<MapBox apiUrl="mapbox://mapbox.mapbox-streets-v8">`

with no luck.

Then I tried adding a "Source" like this:

```
const VectorTileOptions = {
    type: 'vector',
    tiles: ['mapbox://mapbox.mapbox-streets-v8']
};


const MapTest = () => (
        <MapBox style="mapbox://styles/mapbox/light-v10">
            <Source id="source_id" tileJsonSource={VectorTileOptions} />
        </MapBox>
    );
```

But it's still not working. I've checked through all possible related issues, but I can't find anything about using Mapbox's Vector Tiles besides that 1 line that doesn't explain much.

Can you please expand the documentation on how to use Vector Tiles with your library?

**Comment by MarkLyck** [comment]
Looks like it uses vector tiles by default but still very confusing...

**Comment by mklopets** [comment]
It uses Mapbox vector tiles by default. The "streets v8" thing is what's called the map style, and you can specify it using the "style" prop.
