### ISSUE TITLE
coloring countries

### ISSUE THREAD

**Issue by hardysabs2** [alex3165/react-mapbox-gl#870]
Not a bug - just looking for some advice.

What is the best strategy for coloring countries?  Perhaps using a DeckGL layer?  Do I need to look for country polygon data somewhere or is this something that is built in to react-mapbox-gl?

Thanks.

**Comment by mklopets** [comment]
You'll indeed need country polygon data, and can then use e.g GeoJSONLayer for displaying the polygons. Mapbox also offers a paid data set for very high-detail border polygons.

Example of a free data set: https://github.com/datasets/geo-countries

**Comment by hardysabs2** [comment]
Thank you so much.
