### ISSUE TITLE
what's the source of "icon-image" in `layout={{ "icon-image": "marker-15" }}`?

### ISSUE THREAD

**Issue by aasutossh** [alex3165/react-mapbox-gl#885]
What are some other markers? Does the docs say something about this?

**Comment by aasutossh** [comment]
Also, how do you set a custom image to the marker?

**Comment by aasutossh** [comment]
https://labs.mapbox.com/maki-icons/ found it, but some icons doesn't work.

**Comment by timothystewart6** [comment]
May want to review the docs and demos

https://github.com/alex3165/react-mapbox-gl/blob/master/docs/API.md
