### ISSUE TITLE
Popup anchor does not setup automatically when anchor is null

### ISSUE THREAD

**Issue by primozs** [alex3165/react-mapbox-gl#89]
By default anchor should setup automatically.
To make this work one way is to do this:

in popup.js
```
 render() {
...
    const anchorPrefix = 'mapboxgl-popup-anchor-';

    if (anchor) {
      defaultClassName.push(`${anchorPrefix}${anchor}`);
    }

    return (
      <ProjectedLayer
       ...
        anchorPrefix={anchorPrefix}>
        <div className="mapboxgl-popup-tip"></div>
        <div className="mapboxgl-popup-content">
          { children }
        </div>
      </ProjectedLayer>
    );
```

and in projected-layer.js
```
  render() {
    const {
     ...
      className,
      anchorPrefix,
      ...
    } = this.props;
    const { anchor } = this.state;

    ...
    const finalClassName = `${className} ${anchorPrefix}${anchor}`;

    return (
      <div
        className={finalClassName}
       ...>
        { children }
      </div>
    );
  }
```
Cheers

**Comment by primozs** [comment]
also in popup render
defaultClassName.push(`${anchorPrefix}${anchor}`);
defaultClassName.join(' ')

this makes className to grow and grow on every re-render

**Comment by philpl** [comment]
@primozs #90 should fix this, but I'm not sure where your second reference `finalClassName` is located at. By the way, links to the actual files with a line reference, like this, are really useful:

https://github.com/alex3165/react-mapbox-gl/blob/master/src/popup.js#L23

**Comment by primozs** [comment]
@philpl Hi, sorry for a bit bad example ```finalClassName ``` is just something i changed.
I just wanted to point out the issues. Cheers!
