### ISSUE TITLE
marker/feature not moving on user location change.

### ISSUE THREAD

**Issue by shaheryarJS** [alex3165/react-mapbox-gl#934]
So i have a basic map with a marker which depends on coordinates stored in state. The marker should move/rerender if the value in state changes but it dosent. Help appreciated :)
i can also link screenshots if u want.

**Comment by EricPezzulo** [comment]
How did you <Feature > to read your coodrdinates? I'm having the same problem my map not changing locations no matter what the `lng` and `lat` values are. I always start right above London.
