### ISSUE TITLE
Create a Cluster component

### ISSUE THREAD

**Issue by alex3165** [alex3165/react-mapbox-gl#98]
I think it would be worth creating a `<Cluster/>` component in order to group a bunch of markers togethers, something we could use this way:
```
<Cluster replacementMarker={<ReplacementMarker/>}>
  <Marker/>
  <Marker/>
  ...
</Cluster>
```

Cluster detect if all marker are included in `map.getBounds()`, if it is, then replace all the children `Marker` with `ReplacementMarker` where the center is the average value of all the center position of every hidden `Marker`.

Any though about it ?

**Comment by zavan** [comment]
Something like [this](https://www.mapbox.com/mapbox-gl-js/example/cluster/)?
Would be awesome.

**Comment by alex3165** [comment]
Yes but this is applied to `Symbol` which is already possible to do by passing the appropriated `layerOptions` to the `Layer` component. I want to create a Cluster component for using it with the `Marker` component using https://github.com/mapbox/supercluster

**Comment by alex3165** [comment]
WIP: https://github.com/alex3165/react-mapbox-gl/pull/100

**Comment by zavan** [comment]
Even cooler. I'll try it out!

**Comment by zavan** [comment]
@alex3165 

Simply including
```json
"react-mapbox-gl": "https://github.com/alex3165/react-mapbox-gl#feature/cluster"
```

in `package.json` doesn't work with webpack, probably beacuse when getting the package directly from github it comes without the transpiled version, only the ES6 version.

Do yo know how can I make this work?

**Comment by zavan** [comment]
Got it:

```sh
npm i -g babel-core babel-cli
```
Webpack must be able to resolve `jsnext:main`:
```js
resolve: {
  mainFields: [
    'jsnext:main',
    'main'
  ]
}
```

```sh
babel src --out-dir es
```
If not using ES6:
```sh
BABEL_ENV=commonjssimple babel src --out-dir lib
```
From: https://github.com/alex3165/react-mapbox-gl/blob/6ff6ea61e5ed7d978d104b8ec4cdd86f28f17ccc/package.json#L11-L13

**Comment by alex3165** [comment]
Merged and Released 👍
