### ISSUE TITLE
Mapbox Studio and local data

### ISSUE THREAD

**Issue by medv** [alex3165/react-mapbox-gl#99]
I didn't realise the maps world went so deep, so I am humbly asking for some help.

In Mapbox Studio I have DataSets, which are then baked into TileSets, which are then included in my main map Style. This Style contains all my areas and markers as well as some default provided things like rivers etc.

I want to pull this into my map, and of course react-mapbox-gl does this beautifully. However I will also have external data that I was hoping to eventually use as the base to merge Mapbox Studio data into and serve it all out of redis using your Layer, Marker etc components.

Right now my map/style loads with all the areas I've defined in studio and I'm pushing an array of my custom layer names (that I get from mapbox-gl api in onStyleUpdate) to redux store. I subscribe my Map component to this store list.

From that list I create some buttons that then call my action/reducer to toggle that layer by name. The maps component in componentWillUpdate  checks (by comparing props and nextProps) if one of the layers was toggled. If so, it fires mapbox-gl api call to set visibility accordingly.

This means that I have a separation of approach between my studio data and my other external data (which I would be managing in a more react way since I can loop and generate react-mapbox-gl markers and layers and include them as children to the map component). How can I do the same for the studio data since styling it all there is extremely helpful? It's all hiding behind that "style" prop on the map, can I or should I even take control of this data and paint it myself on my own terms using your component and some more abstraction?

**Comment by alex3165** [comment]
Hey @medv, it would make sense to use `react-mapbox-gl` component if your sources and layers need to interact with the user (click, hover) or any specific update logic otherwise it doesn't make sense to extract them from your JSON style.

I guess it must not be complicated to extract some data from the JSON style and convert these into component if you need it. It would be a logic that you would add before passing your JSON style to `ReactMapboxGl` component.

Is that helpful ?

**Comment by medv** [comment]
Yeah it's very helpful, thank you.

I am thinking at this point the studio itself is of limited use to us. We can use it briefly to come up with some styles and use that resulting JSON for our own component and manage all our data on our own server since we have the source GeoJSON anyway. Because all these layers I am currently baking into the studio map style should all have metadata and interactivity on our map.

Am I losing out on some spectacular never-before-seen optimisation by basically ignoring mapbox studio and dealing with all this data myself? My plan is to just chuck it into redis and then it can co-exist with my user data since there is a lot of relationship and cross-over, and then paint it all using your component.
